var annotated_dup =
[
    [ "Assets", "namespace_assets.html", [
      [ "MyScripts", "namespace_assets_1_1_my_scripts.html", [
        [ "SInt", "namespace_assets_1_1_my_scripts_1_1_s_int.html", [
          [ "Common", "namespace_assets_1_1_my_scripts_1_1_s_int_1_1_common.html", [
            [ "Calculation", "namespace_assets_1_1_my_scripts_1_1_s_int_1_1_common_1_1_calculation.html", [
              [ "PhysicsCastCommon", "class_assets_1_1_my_scripts_1_1_s_int_1_1_common_1_1_calculation_1_1_physics_cast_common.html", null ]
            ] ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "Complete", "namespace_complete.html", [
      [ "UIDirectionControl", "class_complete_1_1_u_i_direction_control.html", "class_complete_1_1_u_i_direction_control" ]
    ] ],
    [ "Examples", "namespace_examples.html", [
      [ "Command", "namespace_examples_1_1_command.html", [
        [ "ColorCreator", "class_examples_1_1_command_1_1_color_creator.html", "class_examples_1_1_command_1_1_color_creator" ],
        [ "LightActiveToggle", "class_examples_1_1_command_1_1_light_active_toggle.html", "class_examples_1_1_command_1_1_light_active_toggle" ],
        [ "LightColorChange", "class_examples_1_1_command_1_1_light_color_change.html", "class_examples_1_1_command_1_1_light_color_change" ],
        [ "LightController", "class_examples_1_1_command_1_1_light_controller.html", null ],
        [ "LightDecreaseIntensity", "class_examples_1_1_command_1_1_light_decrease_intensity.html", "class_examples_1_1_command_1_1_light_decrease_intensity" ],
        [ "LightIncreaseIntensity", "class_examples_1_1_command_1_1_light_increase_intensity.html", "class_examples_1_1_command_1_1_light_increase_intensity" ]
      ] ]
    ] ],
    [ "UnityEditor", "namespace_unity_editor.html", [
      [ "PostProcessing", "namespace_unity_editor_1_1_post_processing.html", [
        [ "PostProcessingModelEditorAttribute", "class_unity_editor_1_1_post_processing_1_1_post_processing_model_editor_attribute.html", "class_unity_editor_1_1_post_processing_1_1_post_processing_model_editor_attribute" ],
        [ "ReflectionUtils", "class_unity_editor_1_1_post_processing_1_1_reflection_utils.html", "class_unity_editor_1_1_post_processing_1_1_reflection_utils" ]
      ] ]
    ] ],
    [ "UnityEngine", "namespace_unity_engine.html", [
      [ "InputSystem", "namespace_unity_engine_1_1_input_system.html", [
        [ "Samples", "namespace_unity_engine_1_1_input_system_1_1_samples.html", [
          [ "InGameHints", "namespace_unity_engine_1_1_input_system_1_1_samples_1_1_in_game_hints.html", [
            [ "InGameHintsActions", "class_unity_engine_1_1_input_system_1_1_samples_1_1_in_game_hints_1_1_in_game_hints_actions.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_in_game_hints_1_1_in_game_hints_actions" ],
            [ "InGameHintsExample", "class_unity_engine_1_1_input_system_1_1_samples_1_1_in_game_hints_1_1_in_game_hints_example.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_in_game_hints_1_1_in_game_hints_example" ]
          ] ],
          [ "RebindUI", "namespace_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i.html", [
            [ "GamepadIconsExample", "class_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i_1_1_gamepad_icons_example.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i_1_1_gamepad_icons_example" ],
            [ "RebindActionUI", "class_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i_1_1_rebind_action_u_i.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i_1_1_rebind_action_u_i" ],
            [ "RebindIconsHelper", "class_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i_1_1_rebind_icons_helper.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_rebind_u_i_1_1_rebind_icons_helper" ]
          ] ],
          [ "InputActionVisualizer", "class_unity_engine_1_1_input_system_1_1_samples_1_1_input_action_visualizer.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_input_action_visualizer" ],
          [ "InputControlVisualizer", "class_unity_engine_1_1_input_system_1_1_samples_1_1_input_control_visualizer.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_input_control_visualizer" ],
          [ "InputVisualizer", "class_unity_engine_1_1_input_system_1_1_samples_1_1_input_visualizer.html", "class_unity_engine_1_1_input_system_1_1_samples_1_1_input_visualizer" ]
        ] ],
        [ "UI", "namespace_unity_engine_1_1_input_system_1_1_u_i.html", [
          [ "VirtualMouseInput", "class_unity_engine_1_1_input_system_1_1_u_i_1_1_virtual_mouse_input.html", "class_unity_engine_1_1_input_system_1_1_u_i_1_1_virtual_mouse_input" ]
        ] ],
        [ "InputRecorder", "class_unity_engine_1_1_input_system_1_1_input_recorder.html", "class_unity_engine_1_1_input_system_1_1_input_recorder" ]
      ] ],
      [ "PostProcessing", "namespace_unity_engine_1_1_post_processing.html", [
        [ "AmbientOcclusionComponent", "class_unity_engine_1_1_post_processing_1_1_ambient_occlusion_component.html", "class_unity_engine_1_1_post_processing_1_1_ambient_occlusion_component" ],
        [ "AmbientOcclusionModel", "class_unity_engine_1_1_post_processing_1_1_ambient_occlusion_model.html", "class_unity_engine_1_1_post_processing_1_1_ambient_occlusion_model" ],
        [ "AntialiasingModel", "class_unity_engine_1_1_post_processing_1_1_antialiasing_model.html", "class_unity_engine_1_1_post_processing_1_1_antialiasing_model" ],
        [ "BloomComponent", "class_unity_engine_1_1_post_processing_1_1_bloom_component.html", "class_unity_engine_1_1_post_processing_1_1_bloom_component" ],
        [ "BloomModel", "class_unity_engine_1_1_post_processing_1_1_bloom_model.html", "class_unity_engine_1_1_post_processing_1_1_bloom_model" ],
        [ "BuiltinDebugViewsComponent", "class_unity_engine_1_1_post_processing_1_1_builtin_debug_views_component.html", "class_unity_engine_1_1_post_processing_1_1_builtin_debug_views_component" ],
        [ "BuiltinDebugViewsModel", "class_unity_engine_1_1_post_processing_1_1_builtin_debug_views_model.html", "class_unity_engine_1_1_post_processing_1_1_builtin_debug_views_model" ],
        [ "ChromaticAberrationComponent", "class_unity_engine_1_1_post_processing_1_1_chromatic_aberration_component.html", "class_unity_engine_1_1_post_processing_1_1_chromatic_aberration_component" ],
        [ "ChromaticAberrationModel", "class_unity_engine_1_1_post_processing_1_1_chromatic_aberration_model.html", "class_unity_engine_1_1_post_processing_1_1_chromatic_aberration_model" ],
        [ "ColorGradingComponent", "class_unity_engine_1_1_post_processing_1_1_color_grading_component.html", "class_unity_engine_1_1_post_processing_1_1_color_grading_component" ],
        [ "ColorGradingCurve", "class_unity_engine_1_1_post_processing_1_1_color_grading_curve.html", "class_unity_engine_1_1_post_processing_1_1_color_grading_curve" ],
        [ "ColorGradingModel", "class_unity_engine_1_1_post_processing_1_1_color_grading_model.html", "class_unity_engine_1_1_post_processing_1_1_color_grading_model" ],
        [ "DepthOfFieldComponent", "class_unity_engine_1_1_post_processing_1_1_depth_of_field_component.html", "class_unity_engine_1_1_post_processing_1_1_depth_of_field_component" ],
        [ "DepthOfFieldModel", "class_unity_engine_1_1_post_processing_1_1_depth_of_field_model.html", "class_unity_engine_1_1_post_processing_1_1_depth_of_field_model" ],
        [ "DitheringComponent", "class_unity_engine_1_1_post_processing_1_1_dithering_component.html", "class_unity_engine_1_1_post_processing_1_1_dithering_component" ],
        [ "DitheringModel", "class_unity_engine_1_1_post_processing_1_1_dithering_model.html", "class_unity_engine_1_1_post_processing_1_1_dithering_model" ],
        [ "EyeAdaptationComponent", "class_unity_engine_1_1_post_processing_1_1_eye_adaptation_component.html", "class_unity_engine_1_1_post_processing_1_1_eye_adaptation_component" ],
        [ "EyeAdaptationModel", "class_unity_engine_1_1_post_processing_1_1_eye_adaptation_model.html", "class_unity_engine_1_1_post_processing_1_1_eye_adaptation_model" ],
        [ "FogComponent", "class_unity_engine_1_1_post_processing_1_1_fog_component.html", "class_unity_engine_1_1_post_processing_1_1_fog_component" ],
        [ "FogModel", "class_unity_engine_1_1_post_processing_1_1_fog_model.html", "class_unity_engine_1_1_post_processing_1_1_fog_model" ],
        [ "FxaaComponent", "class_unity_engine_1_1_post_processing_1_1_fxaa_component.html", "class_unity_engine_1_1_post_processing_1_1_fxaa_component" ],
        [ "GetSetAttribute", "class_unity_engine_1_1_post_processing_1_1_get_set_attribute.html", "class_unity_engine_1_1_post_processing_1_1_get_set_attribute" ],
        [ "GrainComponent", "class_unity_engine_1_1_post_processing_1_1_grain_component.html", "class_unity_engine_1_1_post_processing_1_1_grain_component" ],
        [ "GrainModel", "class_unity_engine_1_1_post_processing_1_1_grain_model.html", "class_unity_engine_1_1_post_processing_1_1_grain_model" ],
        [ "GraphicsUtils", "class_unity_engine_1_1_post_processing_1_1_graphics_utils.html", "class_unity_engine_1_1_post_processing_1_1_graphics_utils" ],
        [ "MaterialFactory", "class_unity_engine_1_1_post_processing_1_1_material_factory.html", "class_unity_engine_1_1_post_processing_1_1_material_factory" ],
        [ "MinAttribute", "class_unity_engine_1_1_post_processing_1_1_min_attribute.html", "class_unity_engine_1_1_post_processing_1_1_min_attribute" ],
        [ "MotionBlurComponent", "class_unity_engine_1_1_post_processing_1_1_motion_blur_component.html", "class_unity_engine_1_1_post_processing_1_1_motion_blur_component" ],
        [ "MotionBlurModel", "class_unity_engine_1_1_post_processing_1_1_motion_blur_model.html", "class_unity_engine_1_1_post_processing_1_1_motion_blur_model" ],
        [ "PostProcessingBehaviour", "class_unity_engine_1_1_post_processing_1_1_post_processing_behaviour.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_behaviour" ],
        [ "PostProcessingComponent", "class_unity_engine_1_1_post_processing_1_1_post_processing_component.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_component" ],
        [ "PostProcessingComponentBase", "class_unity_engine_1_1_post_processing_1_1_post_processing_component_base.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_component_base" ],
        [ "PostProcessingComponentCommandBuffer", "class_unity_engine_1_1_post_processing_1_1_post_processing_component_command_buffer.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_component_command_buffer" ],
        [ "PostProcessingComponentRenderTexture", "class_unity_engine_1_1_post_processing_1_1_post_processing_component_render_texture.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_component_render_texture" ],
        [ "PostProcessingContext", "class_unity_engine_1_1_post_processing_1_1_post_processing_context.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_context" ],
        [ "PostProcessingModel", "class_unity_engine_1_1_post_processing_1_1_post_processing_model.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_model" ],
        [ "PostProcessingProfile", "class_unity_engine_1_1_post_processing_1_1_post_processing_profile.html", "class_unity_engine_1_1_post_processing_1_1_post_processing_profile" ],
        [ "RenderTextureFactory", "class_unity_engine_1_1_post_processing_1_1_render_texture_factory.html", "class_unity_engine_1_1_post_processing_1_1_render_texture_factory" ],
        [ "ScreenSpaceReflectionComponent", "class_unity_engine_1_1_post_processing_1_1_screen_space_reflection_component.html", "class_unity_engine_1_1_post_processing_1_1_screen_space_reflection_component" ],
        [ "ScreenSpaceReflectionModel", "class_unity_engine_1_1_post_processing_1_1_screen_space_reflection_model.html", "class_unity_engine_1_1_post_processing_1_1_screen_space_reflection_model" ],
        [ "TaaComponent", "class_unity_engine_1_1_post_processing_1_1_taa_component.html", "class_unity_engine_1_1_post_processing_1_1_taa_component" ],
        [ "TrackballAttribute", "class_unity_engine_1_1_post_processing_1_1_trackball_attribute.html", "class_unity_engine_1_1_post_processing_1_1_trackball_attribute" ],
        [ "TrackballGroupAttribute", "class_unity_engine_1_1_post_processing_1_1_trackball_group_attribute.html", null ],
        [ "UserLutComponent", "class_unity_engine_1_1_post_processing_1_1_user_lut_component.html", "class_unity_engine_1_1_post_processing_1_1_user_lut_component" ],
        [ "UserLutModel", "class_unity_engine_1_1_post_processing_1_1_user_lut_model.html", "class_unity_engine_1_1_post_processing_1_1_user_lut_model" ],
        [ "VignetteComponent", "class_unity_engine_1_1_post_processing_1_1_vignette_component.html", "class_unity_engine_1_1_post_processing_1_1_vignette_component" ],
        [ "VignetteModel", "class_unity_engine_1_1_post_processing_1_1_vignette_model.html", "class_unity_engine_1_1_post_processing_1_1_vignette_model" ]
      ] ]
    ] ],
    [ "AbilityCommand", "class_ability_command.html", null ],
    [ "AINavAgentCommon", "class_a_i_nav_agent_common.html", "class_a_i_nav_agent_common" ],
    [ "Alert", "class_alert.html", "class_alert" ],
    [ "AnimationEventHelper", "class_animation_event_helper.html", "class_animation_event_helper" ],
    [ "AreaOfEffect", "class_area_of_effect.html", null ],
    [ "AStarPathFinder", "class_a_star_path_finder.html", "class_a_star_path_finder" ],
    [ "AudioFade", "class_audio_fade.html", "class_audio_fade" ],
    [ "AudioManager", "class_audio_manager.html", "class_audio_manager" ],
    [ "AutoFlipSpriteByDir", "class_auto_flip_sprite_by_dir.html", "class_auto_flip_sprite_by_dir" ],
    [ "BadScript", "class_bad_script.html", "class_bad_script" ],
    [ "BinCommandAccessorRefsBase", "class_bin_command_accessor_refs_base.html", "class_bin_command_accessor_refs_base" ],
    [ "BinCommandWithCooldown", "class_bin_command_with_cooldown.html", null ],
    [ "breakableWall", "classbreakable_wall.html", "classbreakable_wall" ],
    [ "BreakableWallBullet", "class_breakable_wall_bullet.html", null ],
    [ "ButtonRemapScreenController", "class_button_remap_screen_controller.html", "class_button_remap_screen_controller" ],
    [ "ButtonTrigger", "class_button_trigger.html", "class_button_trigger" ],
    [ "ButtonTuto", "class_button_tuto.html", "class_button_tuto" ],
    [ "CameraControl", "class_camera_control.html", "class_camera_control" ],
    [ "CameraSightPerceptionSensor2D", "class_camera_sight_perception_sensor2_d.html", "class_camera_sight_perception_sensor2_d" ],
    [ "ChainCommandData", "class_chain_command_data.html", "class_chain_command_data" ],
    [ "ChainCommandDataOld", "class_chain_command_data_old.html", "class_chain_command_data_old" ],
    [ "ChainCommandInvoker", "class_chain_command_invoker.html", "class_chain_command_invoker" ],
    [ "ChainCommandInvokerOldTypeA", "class_chain_command_invoker_old_type_a.html", "class_chain_command_invoker_old_type_a" ],
    [ "Character", "class_character.html", "class_character" ],
    [ "CharacterMove", "class_character_move.html", "class_character_move" ],
    [ "CharacterMoveClean", "class_character_move_clean.html", "class_character_move_clean" ],
    [ "CharacterMoveTurnBased", "class_character_move_turn_based.html", "class_character_move_turn_based" ],
    [ "CharacterMoveUndo", "class_character_move_undo.html", "class_character_move_undo" ],
    [ "Chase", "class_chase.html", "class_chase" ],
    [ "CloseButtonTuto", "class_close_button_tuto.html", "class_close_button_tuto" ],
    [ "CollisionByTagEvent", "class_collision_by_tag_event.html", "class_collision_by_tag_event" ],
    [ "CommandAccessorRefsBase", "class_command_accessor_refs_base.html", "class_command_accessor_refs_base" ],
    [ "CommandBase", "class_command_base.html", "class_command_base" ],
    [ "CommandCoolDownComp", "class_command_cool_down_comp.html", "class_command_cool_down_comp" ],
    [ "CommandEvent", "class_command_event.html", "class_command_event" ],
    [ "CommandEventListener", "class_command_event_listener.html", "class_command_event_listener" ],
    [ "CommandHandler", "class_command_handler.html", "class_command_handler" ],
    [ "CommandManagerOld", "class_command_manager_old.html", "class_command_manager_old" ],
    [ "CommandQueue", "class_command_queue.html", "class_command_queue" ],
    [ "CommandQueueHelper", "class_command_queue_helper.html", "class_command_queue_helper" ],
    [ "CommandSlotHolder", "class_command_slot_holder.html", "class_command_slot_holder" ],
    [ "CommandSlotsHolderManager", "class_command_slots_holder_manager.html", "class_command_slots_holder_manager" ],
    [ "CommandStack", "class_command_stack.html", "class_command_stack" ],
    [ "ConfirmPopup", "class_confirm_popup.html", "class_confirm_popup" ],
    [ "ConstraintCommon", "class_constraint_common.html", "class_constraint_common" ],
    [ "ContinueNextTuto", "class_continue_next_tuto.html", "class_continue_next_tuto" ],
    [ "ControlRebindingUI", "class_control_rebinding_u_i.html", "class_control_rebinding_u_i" ],
    [ "CustomComposite", "class_custom_composite.html", "class_custom_composite" ],
    [ "CustomDevice", "class_custom_device.html", "class_custom_device" ],
    [ "CustomDeviceState", "struct_custom_device_state.html", "struct_custom_device_state" ],
    [ "CustomDeviceUsages", "class_custom_device_usages.html", "class_custom_device_usages" ],
    [ "DayCounter", "class_day_counter.html", "class_day_counter" ],
    [ "DefaultState", "class_default_state.html", "class_default_state" ],
    [ "DestroyBySeconds", "class_destroy_by_seconds.html", "class_destroy_by_seconds" ],
    [ "DialogueSystem", "class_dialogue_system.html", "class_dialogue_system" ],
    [ "DontDestroyOnLoad", "class_dont_destroy_on_load.html", "class_dont_destroy_on_load" ],
    [ "DoxygenConfig", "class_doxygen_config.html", "class_doxygen_config" ],
    [ "DoxygenWindow", "class_doxygen_window.html", "class_doxygen_window" ],
    [ "DoxyRunner", "class_doxy_runner.html", "class_doxy_runner" ],
    [ "DoxyThreadSafeOutput", "class_doxy_thread_safe_output.html", "class_doxy_thread_safe_output" ],
    [ "EnableDisableGameObjectCommand", "class_enable_disable_game_object_command.html", "class_enable_disable_game_object_command" ],
    [ "EnemyAttack", "class_enemy_attack.html", "class_enemy_attack" ],
    [ "EnemyFinder", "class_enemy_finder.html", "class_enemy_finder" ],
    [ "EnemyHealth", "class_enemy_health.html", "class_enemy_health" ],
    [ "EnemyMovement", "class_enemy_movement.html", null ],
    [ "EventEditor", "class_event_editor.html", "class_event_editor" ],
    [ "ExtendedScriptableObjectDrawer", "class_extended_scriptable_object_drawer.html", "class_extended_scriptable_object_drawer" ],
    [ "Extensions", "class_extensions.html", "class_extensions" ],
    [ "FileReadWrite", "class_file_read_write.html", "class_file_read_write" ],
    [ "FishMaterial", "class_fish_material.html", null ],
    [ "Flee", "class_flee.html", "class_flee" ],
    [ "FlockAI", "class_flock_a_i.html", "class_flock_a_i" ],
    [ "FSMBaseState", "class_f_s_m_base_state.html", "class_f_s_m_base_state" ],
    [ "FSMSystemBase", "class_f_s_m_system_base.html", "class_f_s_m_system_base" ],
    [ "GameEvent", "class_game_event.html", "class_game_event" ],
    [ "GameEventListener", "class_game_event_listener.html", "class_game_event_listener" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "GameObjActivePauseSync", "class_game_obj_active_pause_sync.html", "class_game_obj_active_pause_sync" ],
    [ "GameObjSpawnHelper", "class_game_obj_spawn_helper.html", "class_game_obj_spawn_helper" ],
    [ "GameplayManager", "class_gameplay_manager.html", "class_gameplay_manager" ],
    [ "GenericDictionary", "class_generic_dictionary.html", "class_generic_dictionary" ],
    [ "GenericDictionaryPropertyDrawer", "class_generic_dictionary_property_drawer.html", "class_generic_dictionary_property_drawer" ],
    [ "HealthBar", "class_health_bar.html", "class_health_bar" ],
    [ "HoldKeyInputTuto", "class_hold_key_input_tuto.html", "class_hold_key_input_tuto" ],
    [ "HomingBullet", "class_homing_bullet.html", "class_homing_bullet" ],
    [ "Hull", "class_hull.html", "class_hull" ],
    [ "ICommand", "interface_i_command.html", "interface_i_command" ],
    [ "ICommandOWS", "interface_i_command_o_w_s.html", "interface_i_command_o_w_s" ],
    [ "IgnoreChildCollision", "class_ignore_child_collision.html", null ],
    [ "InitCustomDeviceUsages", "class_init_custom_device_usages.html", null ],
    [ "InputCommand", "class_input_command.html", "class_input_command" ],
    [ "InputHandlerOld_NewInputSystem", "class_input_handler_old___new_input_system.html", "class_input_handler_old___new_input_system" ],
    [ "InputManager", "class_input_manager.html", null ],
    [ "InputManagerTurnBased", "class_input_manager_turn_based.html", null ],
    [ "InstalledUpgradeSaveData", "class_installed_upgrade_save_data.html", "class_installed_upgrade_save_data" ],
    [ "IntroChoice", "class_intro_choice.html", "class_intro_choice" ],
    [ "Introduction", "class_introduction.html", "class_introduction" ],
    [ "Inventory", "class_inventory.html", "class_inventory" ],
    [ "inventoryNew", "classinventory_new.html", "classinventory_new" ],
    [ "IStateBehavior", "interface_i_state_behavior.html", null ],
    [ "item", "classitem.html", "classitem" ],
    [ "ItemContainer", "class_item_container.html", "class_item_container" ],
    [ "ItemContainerSaveData", "class_item_container_save_data.html", "class_item_container_save_data" ],
    [ "ItemDatabase", "class_item_database.html", "class_item_database" ],
    [ "itemNew", "classitem_new.html", "classitem_new" ],
    [ "ItemSaveIO", "class_item_save_i_o.html", "class_item_save_i_o" ],
    [ "ItemSaveManager", "class_item_save_manager.html", "class_item_save_manager" ],
    [ "itemSlots", "classitem_slots.html", "classitem_slots" ],
    [ "ItemSlotSaveData", "class_item_slot_save_data.html", "class_item_slot_save_data" ],
    [ "itemSlotsNew", "classitem_slots_new.html", "classitem_slots_new" ],
    [ "ItemToolTip", "class_item_tool_tip.html", "class_item_tool_tip" ],
    [ "Key_CtrlG_SnapToGround", "class_key___ctrl_g___snap_to_ground.html", "class_key___ctrl_g___snap_to_ground" ],
    [ "KeyInputTuto", "class_key_input_tuto.html", "class_key_input_tuto" ],
    [ "LastInHeirarchy", "class_last_in_heirarchy.html", null ],
    [ "LineRendererDrawer", "class_line_renderer_drawer.html", "class_line_renderer_drawer" ],
    [ "LookAtCameraMain", "class_look_at_camera_main.html", "class_look_at_camera_main" ],
    [ "MapLocation", "class_map_location.html", "class_map_location" ],
    [ "MathCommon", "class_math_common.html", "class_math_common" ],
    [ "Maze", "class_maze.html", "class_maze" ],
    [ "MeterTank", "class_meter_tank.html", "class_meter_tank" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "Movement", "class_movement.html", null ],
    [ "NavAgentTestAutoSetMouseDestination", "class_nav_agent_test_auto_set_mouse_destination.html", null ],
    [ "NavAgentTestAutoSetRandomDestination", "class_nav_agent_test_auto_set_random_destination.html", "class_nav_agent_test_auto_set_random_destination" ],
    [ "NavAgentTestAutoSetWASDMovement", "class_nav_agent_test_auto_set_w_a_s_d_movement.html", null ],
    [ "NavMeshCustomMove", "class_nav_mesh_custom_move.html", "class_nav_mesh_custom_move" ],
    [ "NextStageBarrier", "class_next_stage_barrier.html", null ],
    [ "NPCAISystemTypeA", "class_n_p_c_a_i_system_type_a.html", "class_n_p_c_a_i_system_type_a" ],
    [ "OnAllUnityEventCall", "class_on_all_unity_event_call.html", "class_on_all_unity_event_call" ],
    [ "OnEnableEventCallTimer", "class_on_enable_event_call_timer.html", "class_on_enable_event_call_timer" ],
    [ "OnEnablePlayBGM", "class_on_enable_play_b_g_m.html", "class_on_enable_play_b_g_m" ],
    [ "OnEnablePlaySFX", "class_on_enable_play_s_f_x.html", "class_on_enable_play_s_f_x" ],
    [ "OutpostChoices", "class_outpost_choices.html", "class_outpost_choices" ],
    [ "OxygenTank", "class_oxygen_tank.html", "class_oxygen_tank" ],
    [ "ParamStateBehavior", "class_param_state_behavior.html", "class_param_state_behavior" ],
    [ "PathDraw", "class_path_draw.html", "class_path_draw" ],
    [ "PathMarker", "class_path_marker.html", "class_path_marker" ],
    [ "PatrolByRandomPos", "class_patrol_by_random_pos.html", "class_patrol_by_random_pos" ],
    [ "PatrolByWaypoints", "class_patrol_by_waypoints.html", "class_patrol_by_waypoints" ],
    [ "PauseMenu", "class_pause_menu.html", null ],
    [ "PauseMenuScripts", "class_pause_menu_scripts.html", "class_pause_menu_scripts" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerAttack", "class_player_attack.html", "class_player_attack" ],
    [ "PlayerBullet", "class_player_bullet.html", "class_player_bullet" ],
    [ "PlayerBulletProperties", "class_player_bullet_properties.html", "class_player_bullet_properties" ],
    [ "PlayerData", "class_player_data.html", "class_player_data" ],
    [ "PlayerHealth", "class_player_health.html", "class_player_health" ],
    [ "PlayerMovement", "class_player_movement.html", "class_player_movement" ],
    [ "PlayerPrefTextSync", "class_player_pref_text_sync.html", "class_player_pref_text_sync" ],
    [ "PlayerSkills", "class_player_skills.html", "class_player_skills" ],
    [ "PlayerUpgrades", "class_player_upgrades.html", "class_player_upgrades" ],
    [ "PlayTestSpeedUp", "class_play_test_speed_up.html", "class_play_test_speed_up" ],
    [ "PolyColToMesh", "class_poly_col_to_mesh.html", null ],
    [ "PressureStageChecker", "class_pressure_stage_checker.html", "class_pressure_stage_checker" ],
    [ "PreviousPosition", "class_previous_position.html", "class_previous_position" ],
    [ "QuickOpenInventory", "class_quick_open_inventory.html", "class_quick_open_inventory" ],
    [ "QuickPauseFix", "class_quick_pause_fix.html", null ],
    [ "RandomEnemy", "class_random_enemy.html", "class_random_enemy" ],
    [ "RandomSpawner", "class_random_spawner.html", "class_random_spawner" ],
    [ "RawMaterial", "class_raw_material.html", null ],
    [ "RebindResetAllBindings", "class_rebind_reset_all_bindings.html", "class_rebind_reset_all_bindings" ],
    [ "RebindSaveLoad", "class_rebind_save_load.html", "class_rebind_save_load" ],
    [ "RebindUISampleActionsModified", "class_rebind_u_i_sample_actions_modified.html", "class_rebind_u_i_sample_actions_modified" ],
    [ "RequirementChecker", "class_requirement_checker.html", "class_requirement_checker" ],
    [ "Resource", "class_resource.html", "class_resource" ],
    [ "RigidBody2DAutoAddRelativeForceUp", "class_rigid_body2_d_auto_add_relative_force_up.html", "class_rigid_body2_d_auto_add_relative_force_up" ],
    [ "SaveHandler", "class_save_handler.html", "class_save_handler" ],
    [ "SaveSystem", "class_save_system.html", "class_save_system" ],
    [ "ScenearioScreenHandler", "class_sceneario_screen_handler.html", "class_sceneario_screen_handler" ],
    [ "SceneAsyncManager", "class_scene_async_manager.html", "class_scene_async_manager" ],
    [ "SceneBetweenStages", "class_scene_between_stages.html", "class_scene_between_stages" ],
    [ "SceneHandler", "class_scene_handler.html", "class_scene_handler" ],
    [ "SceneTransitioning", "class_scene_transitioning.html", "class_scene_transitioning" ],
    [ "SceneTransitionsToOutpost", "class_scene_transitions_to_outpost.html", "class_scene_transitions_to_outpost" ],
    [ "ScrollRectCommon", "class_scroll_rect_common.html", "class_scroll_rect_common" ],
    [ "SelfRepair", "class_self_repair.html", "class_self_repair" ],
    [ "SerializableQueueList", "class_serializable_queue_list.html", "class_serializable_queue_list" ],
    [ "SetMaterialColorCommand", "class_set_material_color_command.html", "class_set_material_color_command" ],
    [ "SetParamStateData", "class_set_param_state_data.html", "class_set_param_state_data" ],
    [ "ShellExplosion", "class_shell_explosion.html", "class_shell_explosion" ],
    [ "SimpleController_UsingActionAsset", "class_simple_controller___using_action_asset.html", "class_simple_controller___using_action_asset" ],
    [ "SimpleController_UsingActions", "class_simple_controller___using_actions.html", "class_simple_controller___using_actions" ],
    [ "SimpleController_UsingPlayerInput", "class_simple_controller___using_player_input.html", "class_simple_controller___using_player_input" ],
    [ "SimpleController_UsingState", "class_simple_controller___using_state.html", "class_simple_controller___using_state" ],
    [ "SimpleControls", "class_simple_controls.html", "class_simple_controls" ],
    [ "SimpleMultiplayerPlayer", "class_simple_multiplayer_player.html", "class_simple_multiplayer_player" ],
    [ "Singleton", "class_singleton.html", "class_singleton" ],
    [ "SingleTonOnClickHelper", "class_single_ton_on_click_helper.html", "class_single_ton_on_click_helper" ],
    [ "Sound", "class_sound.html", "class_sound" ],
    [ "SpawnFlockManager", "class_spawn_flock_manager.html", "class_spawn_flock_manager" ],
    [ "Stat", "class_stat.html", "class_stat" ],
    [ "StdioCommon", "class_stdio_common.html", "class_stdio_common" ],
    [ "storage", "classstorage.html", "classstorage" ],
    [ "SyncTextWithTextMeshPro", "class_sync_text_with_text_mesh_pro.html", "class_sync_text_with_text_mesh_pro" ],
    [ "TankHealth", "class_tank_health.html", "class_tank_health" ],
    [ "TankManager", "class_tank_manager.html", "class_tank_manager" ],
    [ "TankMovement", "class_tank_movement.html", "class_tank_movement" ],
    [ "TankShooting", "class_tank_shooting.html", "class_tank_shooting" ],
    [ "TanksInputActions", "class_tanks_input_actions.html", "class_tanks_input_actions" ],
    [ "TestDialogue", "class_test_dialogue.html", "class_test_dialogue" ],
    [ "Testing", "class_testing.html", null ],
    [ "TextAnimation", "class_text_animation.html", "class_text_animation" ],
    [ "TimedParamStateBehavior", "class_timed_param_state_behavior.html", "class_timed_param_state_behavior" ],
    [ "Transform2DAutoLookAtObj2D", "class_transform2_d_auto_look_at_obj2_d.html", "class_transform2_d_auto_look_at_obj2_d" ],
    [ "TransformAutoFakeParent", "class_transform_auto_fake_parent.html", "class_transform_auto_fake_parent" ],
    [ "TransformAutoRelative", "class_transform_auto_relative.html", "class_transform_auto_relative" ],
    [ "TransformAutoRotate", "class_transform_auto_rotate.html", "class_transform_auto_rotate" ],
    [ "TransformCommon", "class_transform_common.html", "class_transform_common" ],
    [ "TransformPosShake", "class_transform_pos_shake.html", "class_transform_pos_shake" ],
    [ "TriggerTransitionTuto", "class_trigger_transition_tuto.html", "class_trigger_transition_tuto" ],
    [ "Turbine", "class_turbine.html", "class_turbine" ],
    [ "turbineUnique", "classturbine_unique.html", "classturbine_unique" ],
    [ "TutoManager", "class_tuto_manager.html", "class_tuto_manager" ],
    [ "TutoOutpostDialogue", "class_tuto_outpost_dialogue.html", "class_tuto_outpost_dialogue" ],
    [ "Tutorial", "class_tutorial.html", "class_tutorial" ],
    [ "UI_SkillTree", "class_u_i___skill_tree.html", "class_u_i___skill_tree" ],
    [ "UICommandList", "class_u_i_command_list.html", "class_u_i_command_list" ],
    [ "UIHPSliderColor", "class_u_i_h_p_slider_color.html", "class_u_i_h_p_slider_color" ],
    [ "UIShowHideToggle", "class_u_i_show_hide_toggle.html", "class_u_i_show_hide_toggle" ],
    [ "UIToggleSaveToPlayerPrefs", "class_u_i_toggle_save_to_player_prefs.html", "class_u_i_toggle_save_to_player_prefs" ],
    [ "UIVolumeSlider", "class_u_i_volume_slider.html", "class_u_i_volume_slider" ],
    [ "UpgradeChecker", "class_upgrade_checker.html", "class_upgrade_checker" ],
    [ "UpgradeDatabase", "class_upgrade_database.html", "class_upgrade_database" ],
    [ "UpgradeHolder", "class_upgrade_holder.html", "class_upgrade_holder" ],
    [ "UpgradeSaveData", "class_upgrade_save_data.html", "class_upgrade_save_data" ],
    [ "UpgradeSaveIO", "class_upgrade_save_i_o.html", "class_upgrade_save_i_o" ],
    [ "UpgradeSaveManager", "class_upgrade_save_manager.html", "class_upgrade_save_manager" ],
    [ "Vector2Common", "class_vector2_common.html", "class_vector2_common" ],
    [ "Vector3Common", "class_vector3_common.html", "class_vector3_common" ],
    [ "WaypointPath", "class_waypoint_path.html", "class_waypoint_path" ],
    [ "WaypointPathMaker", "class_waypoint_path_maker.html", "class_waypoint_path_maker" ],
    [ "Weapon", "class_weapon.html", "class_weapon" ]
];