UnityEngine::InputSystem::Samples::RebindUI::RebindActionUI
InputActionReference UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.actionReference
Reference to the action that is to be rebound.
string UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.bindingId
ID (in string form) of the binding that is to be rebound on the action.
InputBinding.id
Referenced by UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResolveActionAndBinding.
InputBinding.DisplayStringOptions UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.displayStringOptions
Referenced by UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.UpdateBindingDisplay.
Text UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.actionLabel
Text component that receives the name of the action.
Optional.
Text UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.bindingText
Text component that receives the display string of the binding.
Can be null in which case the component entirely relies on updateBindingUIEvent.
Referenced by UnityEngine.InputSystem.Samples.RebindUI.RebindIconsHelper.OnUpdateBindingDisplay, UnityEngine.InputSystem.Samples.RebindUI.GamepadIconsExample.OnUpdateBindingDisplay.
Text UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.rebindPrompt
Optional text component that receives a text prompt when waiting for a control to be actuated.
startRebindEvent, rebindOverlay
GameObject UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.rebindOverlay
Optional UI that is activated when an interactive rebind is started and deactivated when the rebind is finished.
This is normally used to display an overlay over the current UI while the system is waiting for a control to be actuated. If neither rebindPrompt nor rebindOverlay is set, the component will temporarily replaced the bindingText (if not null) with "Waiting...". startRebindEvent, rebindPrompt
UpdateBindingUIEvent UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.updateBindingUIEvent
Event that is triggered every time the UI updates to reflect the current binding.
This can be used to tie custom visualizations to bindings.
Referenced by UnityEngine.InputSystem.Samples.RebindUI.RebindIconsHelper.OnEnable, UnityEngine.InputSystem.Samples.RebindUI.GamepadIconsExample.OnEnable.
InteractiveRebindEvent UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.startRebindEvent
Event that is triggered when an interactive rebind is started on the action.
InteractiveRebindEvent UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.stopRebindEvent
Event that is triggered when an interactive rebind has been completed or canceled.
InputActionRebindingExtensions.RebindingOperation UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ongoingRebind
When an interactive rebind is in progress, this is the rebind operation controller.
Otherwise, it is null.
InputActionReference UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_Action
string UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_BindingId
InputBinding.DisplayStringOptions UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_DisplayStringOptions
Text UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_ActionLabel
Text UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_BindingText
GameObject UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_RebindOverlay
Text UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_RebindText
UpdateBindingUIEvent UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_UpdateBindingUIEvent
InteractiveRebindEvent UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_RebindStartEvent
InteractiveRebindEvent UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_RebindStopEvent
InputActionRebindingExtensions.RebindingOperation UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.m_RebindOperation
List<RebindActionUI> UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.s_RebindActionUIs
bool UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResolveActionAndBinding(out InputAction action, out int bindingIndex)
Return the action and binding index for the binding that is targeted by the component according to
action bindingIndex
References UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.bindingId.
Referenced by UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResetToDefault, UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.StartInteractiveRebind.
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.UpdateBindingDisplay()
Trigger a refresh of the currently displayed binding.
References UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.displayStringOptions.
Referenced by UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResetToDefault.
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResetToDefault()
Remove currently applied binding overrides.
References UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResolveActionAndBinding, UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.UpdateBindingDisplay.
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.StartInteractiveRebind()
Initiate an interactive rebind that lets the player actuate a control to choose a new binding for the action.
References UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.ResolveActionAndBinding.
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.PerformInteractiveRebind(InputAction action, int bindingIndex, bool allCompositeParts=false)
bool UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.CheckDuplicateBindings(InputAction action, int bindingIndex, bool allCompositeParts=false)
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.Start()
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.UpdateActionLabel()
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.OnEnable()
void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.OnDisable()
static void UnityEngine.InputSystem.Samples.RebindUI.RebindActionUI.OnActionChange(object obj, InputActionChange change)