CommandQueueHelper
GameObject CommandQueueHelper.commandOwnerRootObj
GenericDictionary<string, CommandQueue> CommandQueueHelper.commandQueuesDictionary
Referenced by CheckSequence, ChainCommandInvokerOldTypeA.CheckSequenceOld.
int CommandQueueHelper.CurrentTick
Referenced by CheckSequence.
float CommandQueueHelper.maxDefaultAllowedTimeDifferenceCheck
Referenced by CheckSequence.
void CommandQueueHelper.Start()
void CommandQueueHelper.OnDisable()
void CommandQueueHelper.Update()
bool CommandQueueHelper.CheckSequence(string entryQueueName, string[] sequence, string[] Sequence_Query, string[] ignoreCategory, int maxDuration, CommandBase chainCommand)
References CommandBase.aName, commandQueuesDictionary, CurrentTick, maxDefaultAllowedTimeDifferenceCheck.
Referenced by CheckSequence, ChainCommandInvokerOldTypeA.CheckSequenceOld.
bool CommandQueueHelper.CheckSequence(string entryQueueName, ChainCommandData c)
References ChainCommandData.chainCommandSlot, CheckSequence, CommandSlotHolder.commandInstanceInSlot, commandQueuesDictionary, ChainCommandData.holdDownSequence, ChainCommandData.ignoreCategory, ChainCommandData.Sequence, ChainCommandData.Sequence_Query.
void CommandQueueHelper.ExecCommand_InputSystem(InputAction.CallbackContext context, InputCommand curCommand, string queueDictionaryElementName="Primary")
References ExecCommand_Press, InputCommand.OnInput.
Referenced by InputHandlerOld_NewInputSystem.OnCommandSlot0, InputHandlerOld_NewInputSystem.OnCommandSlot1, InputHandlerOld_NewInputSystem.OnCommandSlot2, InputHandlerOld_NewInputSystem.OnCommandSlot3, InputHandlerOld_NewInputSystem.OnDPadAxisHorizontal, InputHandlerOld_NewInputSystem.OnDPadAxisVertical, CommandSlotHolder.OnInput, InputHandlerOld_NewInputSystem.OnLeftStickAxisHorizontal, InputHandlerOld_NewInputSystem.OnLeftStickAxisVertical, InputHandlerOld_NewInputSystem.OnSecondaryCommandSlot4, InputHandlerOld_NewInputSystem.OnSecondaryCommandSlot5, InputHandlerOld_NewInputSystem.OnSelect, InputHandlerOld_NewInputSystem.OnStart, InputHandlerOld_NewInputSystem.OnTertiaryCommandSlotAxis6, InputHandlerOld_NewInputSystem.OnTertiaryCommandSlotAxis7.
void CommandQueueHelper.ExecCommand_SimulateInputSystem(bool IsPressedThisFrame, float axis, InputCommand curCommand, string queueDictionaryElementName="Primary")
References ExecCommand_Press, InputCommand.execExtraInfo, InputCommand.ExecExtraInfo.m_Axis, InputCommand.SetExecInfo.
Referenced by CommandSlotHolder.OnSimulateInput.
void CommandQueueHelper.ExecCommand_SimulateInputSystem(bool IsPressedThisFrame, InputCommand curCommand, string queueDictionaryElementName="Primary")
References ExecCommand_Press, InputCommand.execExtraInfo, InputCommand.ExecExtraInfo.m_Axis, InputCommand.SetExecInfo.
void CommandQueueHelper.ExecCommand_Press(InputCommand curCommand, string queueDictionaryElementName="Primary")
References InputCommand.execExtraInfo, InputCommand.ExecExtraInfo.m_ExecButtonPressedThisFrame.
Referenced by ExecCommand_InputSystem, ExecCommand_SimulateInputSystem.
void CommandQueueHelper.ExecCommand_HoldRelease(InputCommand curCommand)
References CommandBase.aName, InputCommand.execExtraInfo, InputCommand.ExecExtraInfo.m_ExecButtonDown.