PauseMenuScripts
GameObject PauseMenuScripts.pauseMenu
Referenced by DisablePause.
bool PauseMenuScripts.isPaused
Referenced by ClosePauseMenu, OnInput, OpenPauseMenu.
bool PauseMenuScripts.isPauseMenuOn
Referenced by ClosePauseMenu, OnInput.
Character PauseMenuScripts.character
Referenced by OnInput.
UnityEvent PauseMenuScripts.onUnPause
Referenced by ClosePauseMenu.
void PauseMenuScripts.Awake()
void PauseMenuScripts.Update()
void PauseMenuScripts.DisablePause()
References pauseMenu.
void PauseMenuScripts.OpenPauseMenu()
References isPaused.
Referenced by QuickOpenInventory.AttemptOpenInventory.
void PauseMenuScripts.ClosePauseMenu()
References isPaused, isPauseMenuOn, onUnPause.
Referenced by QuickOpenInventory.AttemptOpenInventory, SceneTransitionsToOutpost.Confirm, QuitGame.
void PauseMenuScripts.QuitGame()
References ClosePauseMenu.
void PauseMenuScripts.OnInput(InputAction.CallbackContext context)
References character, isPaused, isPauseMenuOn.