storage
List<item> storage.startingItems
GameObject storage.itemsParentGameObject
Sprite storage.lockSprite
int storage.startingItemsAmount
Inventory storage.inventoryUpgrade
itemSlots storage.itemSlotPrefab
UpgradeHolder storage.upgradeHolder
override void storage.Awake()
References UpgradeHolder.InventoryUpgrade, SetInventoryUpgrade.
void storage.SetInventoryUpgrade(Inventory inventoryUpgrade)
References Inventory.GetNumberOfSlots, ItemContainer.ItemSlots.
Referenced by Awake, UI_SkillTree.StartBuyingUpgrade.
List< itemSlots > storage.GetListOfItemsInInventory()
References ItemContainer.ItemSlots.
Referenced by RequirementChecker.CheckRequirement, PlayerSkills.IsRequirementMet.
void storage.OnValidate()
void storage.SetStartingItems()