SetParamStateData
string SetParamStateData.paramName
Referenced by SetAnimatorParamDatas.
EAnimParamType SetParamStateData.animParamType
Referenced by SetAnimatorParamDatas.
bool SetParamStateData.setDefaultState
Referenced by SetAnimatorParamDatas.
int SetParamStateData.ifIsIntParamType_NewInt
Referenced by SetAnimatorParamDatas.
float SetParamStateData.ifIsFloatParamType_NewFloat
static void SetParamStateData.SetAnimatorParamDatas(SetParamStateData data, Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
References animParamType, ifIsIntParamType_NewInt, paramName, setDefaultState.
Referenced by ParamStateBehavior.OnStateEnter, TimedParamStateBehavior.OnStateEnter, TimedParamStateBehavior.OnStateExit, TimedParamStateBehavior.OnStateUpdate.
static void SetParamStateData.SetAnimatorParamDatas(SetParamStateData data, Animator animator)
References animParamType, ifIsIntParamType_NewInt, paramName, setDefaultState.
static void SetParamStateData.SetAnimatorParamDatas(SetParamStateData data, Animator animator, bool isInvertBOOL, AnimatorStateInfo stateInfo, int layerIndex)
References animParamType, ifIsIntParamType_NewInt, paramName, setDefaultState.
static void SetParamStateData.SetAnimatorParamDatas(SetParamStateData data, Animator animator, bool isInvertBOOL)
References animParamType, ifIsIntParamType_NewInt, paramName, setDefaultState.