CommandQueue
SerializableQueueList<string> CommandQueue._commandNamesHistory
Referenced by CommandManagerOld.CheckSequence, Clear, Contains, Dequeue, DisplayLogText, Enqueue, Remove, RemoveAt.
SerializableQueueList<float> CommandQueue._commandTimeStamps
Referenced by Clear, Dequeue, Enqueue, RemoveAt.
SerializableQueueList<CommandBase> CommandQueue._commandHistory
Referenced by CommandManagerOld.CheckSequence, Clear, Dequeue, Enqueue, OnUpdate, RemoveAt, UndoLastCommand.
int CommandQueue.maxCount
Referenced by OnUpdate.
Text CommandQueue.LogText
Referenced by DisplayLogText.
int CommandQueue.Count
Referenced by Enqueue, OnUpdate.
void CommandQueue.OnUpdate()
References _commandHistory, Count, Dequeue, DisplayLogText, maxCount.
void CommandQueue.DisplayLogText()
References _commandNamesHistory, LogText.
Referenced by OnUpdate.
void CommandQueue.Enqueue(CommandBase command)
References _commandHistory, _commandNamesHistory, _commandTimeStamps, CommandBase.aName, Count, OnQueueModified, CommandBase.TimeStamp.
Referenced by TryExecuteCommand.
CommandBase CommandQueue.Dequeue()
References _commandHistory, _commandNamesHistory, _commandTimeStamps, OnQueueModified.
Referenced by OnUpdate, UndoLastCommand.
void CommandQueue.OnQueueModified()
Referenced by Clear, Dequeue, Enqueue, RemoveAt.
CommandBase CommandQueue.TryExecuteCommand(CommandBase command, bool willInstanteACloneSO=false)
References CommandBase.Info._DebugLog, CommandBase.CreateNewInstanceOfSelf, Enqueue, CommandBase.info.
virtual void CommandQueue.UndoLastCommand()
References _commandHistory, Dequeue, CommandBase.Undo.
void CommandQueue.Remove(CommandBase c)
References _commandNamesHistory, CommandBase.aName, RemoveAt.
void CommandQueue.RemoveAt(int index)
References _commandHistory, _commandNamesHistory, _commandTimeStamps, OnQueueModified.
Referenced by Remove.
bool CommandQueue.Contains(string commandName)
References _commandNamesHistory.
void CommandQueue.Clear()
References _commandHistory, _commandNamesHistory, _commandTimeStamps, OnQueueModified.