InputCommand
ExecExtraInfo InputCommand.execExtraInfo
Referenced by CommandQueueHelper.ExecCommand_HoldRelease, CommandQueueHelper.ExecCommand_Press, CommandQueueHelper.ExecCommand_SimulateInputSystem, ExecDown, ExecDownCharging, ExecPress, ExecRelease, SetExecInfo.
bool InputCommand.isExecChargedStyle
Referenced by ExecDown.
bool InputCommand.isFullChargeAutoRelease
Slider InputCommand.m_AimSlider
Referenced by ExecDownCharging, OnEnable.
float InputCommand.m_MinLaunchForce
Referenced by ExecRelease, OnEnable.
float InputCommand.m_MaxLaunchForce
Referenced by OnEnable.
float InputCommand.m_MaxChargeTime
Referenced by OnEnable.
float InputCommand.m_CurrentLaunchForce
float InputCommand.m_ChargeSpeed
void InputCommand.SetExecExtraInfoByExecExtraInfo(ExecExtraInfo ex2)
References InputCommand.ExecExtraInfo.m_ExecButtonDown, InputCommand.ExecExtraInfo.m_ExecButtonPressedThisFrame, SetExecInfo.
override void InputCommand.OnEnable()
References m_AimSlider, m_MaxChargeTime, m_MaxLaunchForce, m_MinLaunchForce.
void InputCommand.SetExecInfo(bool IsPress)
References CommandBase.CooldownInfo.castState, CommandBase.cooldownInfo, execExtraInfo, InputCommand.ExecExtraInfo.m_ExecButtonDown, InputCommand.ExecExtraInfo.m_ExecButtonPressedThisFrame, InputCommand.ExecExtraInfo.m_ExecButtonReleasedThisFrame, InputCommand.ExecExtraInfo.m_Execd.
Referenced by CommandQueueHelper.ExecCommand_SimulateInputSystem, OnInput, SetExecExtraInfoByExecExtraInfo, TryExecCommand.
override void InputCommand.TryExecCommand()
References SetExecInfo.
override void InputCommand.ExecPress()
References CommandBase.Info._DebugLog, CommandBase.ExecutionInfo.curExecState, execExtraInfo, CommandBase.execInfo, CommandBase.info, InputCommand.ExecExtraInfo.m_Axis.
override void InputCommand.ExecDown()
References CommandBase.Info._DebugLog, CommandBase.aName, CommandBase.ExecutionInfo.curExecState, ExecDownCharging, execExtraInfo, CommandBase.execInfo, CommandBase.info, isExecChargedStyle, InputCommand.ExecExtraInfo.m_Axis, InputCommand.ExecExtraInfo.m_Execd.
override void InputCommand.ExecDownCharging()
References CommandBase.Info._DebugLog, CommandBase.aName, CommandBase.ExecutionInfo.curExecState, execExtraInfo, CommandBase.execInfo, CommandBase.info, m_AimSlider, InputCommand.ExecExtraInfo.m_Axis.
Referenced by ExecDown.
override void InputCommand.ExecRelease()
References CommandBase.Info._DebugLog, CommandBase.aName, CommandBase.ExecutionInfo.curExecState, execExtraInfo, CommandBase.execInfo, CommandBase.info, InputCommand.ExecExtraInfo.m_Axis, InputCommand.ExecExtraInfo.m_ExecButtonDown, InputCommand.ExecExtraInfo.m_ExecButtonPressedThisFrame, InputCommand.ExecExtraInfo.m_ExecButtonReleasedThisFrame, InputCommand.ExecExtraInfo.m_Execd, m_MinLaunchForce.
override void InputCommand.Execd()
override void InputCommand.OnExternalUpdate()
void InputCommand.OnInput(InputAction.CallbackContext context)
References CommandBase.Info._DebugLog, CommandBase.info, InputCommand.ExecExtraInfo.m_Axis, SetExecInfo.
Referenced by CommandQueueHelper.ExecCommand_InputSystem.
void InputCommand.OnInput(InputValue value)
References SetExecInfo.
void InputCommand.HandleInputSystem()