FSMBaseState
readonly FSMSystemBase FSMBaseState._system
Referenced by Chase.Chase, Flee.Flee, FSMBaseState, OnEnterState, Alert.OnEnterState, OnExitState, OnStayState, OnUpdate, PatrolByRandomPos.PatrolByRandomPos, PatrolByWaypoints.PatrolByWaypoints, PatrolByRandomPos.PerformStateBehaviour, PatrolByWaypoints.PerformStateBehaviour.
string FSMBaseState._aName
virtual string FSMBaseState.aName
Referenced by FSMBaseState, OnEnterState, OnExitState, OnStayState, OnUpdate.
virtual FSMExecutionState FSMBaseState.ExecutionState
FSMExecutionState FSMBaseState._ExecutionState
Referenced by OnEnable, OnEnterState, OnExitState, OnUpdate.
float FSMBaseState.OnEnterTimeStamp
Referenced by OnEnterState.
float FSMBaseState.ElapsedTime
Referenced by OnEnterState, OnUpdate.
FSMBaseState.FSMBaseState(FSMSystemBase system)
References _system, aName.
virtual bool FSMBaseState.OnEnterState()
References _ExecutionState, _system, aName, ElapsedTime, FSMSystemBase.isDebugLog, OnEnterTimeStamp.
Referenced by FSMSystemBase.Awake, FSMSystemBase.TryEnterState.
virtual void FSMBaseState.OnUpdate()
References _ExecutionState, _system, aName, ElapsedTime, FSMSystemBase.isDebugLog, OnStayState.
Referenced by FSMSystemBase.Update.
virtual void FSMBaseState.OnStayState()
References _system, aName, FSMSystemBase.isDebugLog.
Referenced by OnUpdate.
virtual bool FSMBaseState.OnExitState()
References _ExecutionState, _system, aName, FSMSystemBase.isDebugLog.
Referenced by FSMSystemBase.TryEnterState.
void FSMBaseState.OnEnable()
References _ExecutionState.
void FSMBaseState.OnDisable()