SceneAsyncManager
SceneAsyncManager SceneAsyncManager.instance
bool SceneAsyncManager.isForceMouseAlwaysVisible
Referenced by SetMouseVisibility.
bool SceneAsyncManager.isNextSceneFullyLoaded
bool SceneAsyncManager.isWaitForAsyncFinishLoading
AsyncOperation SceneAsyncManager.asyncLoad
void SceneAsyncManager.Awake()
void SceneAsyncManager.LoadScene(string sceneName)
Referenced by LoadLevel, LoadLevelByIndex, LoadNextLevel, RestartLevel.
void SceneAsyncManager.LoadLevel(string Name)
References LoadScene.
void SceneAsyncManager.RestartLevel()
References LoadScene.
void SceneAsyncManager.RequestQuit()
void SceneAsyncManager.LoadNextLevel()
References LoadScene.
int SceneAsyncManager.GetCurrentLevelIndex()
void SceneAsyncManager.LoadLevelByIndex(int index)
References LoadScene.
void SceneAsyncManager.SetMouseVisibility(bool isVisible)
References isForceMouseAlwaysVisible.
void SceneAsyncManager.PauseLevel()
References GameplayManager.CurrGameplayState, GameplayManager.instance.
void SceneAsyncManager.unPauseLevel()
References GameplayManager.CurrGameplayState, GameplayManager.instance.
void SceneAsyncManager.MakeInstance()
IEnumerator SceneAsyncManager.LoadAsyncScene(string sceneName)
void SceneAsyncManager.Update()
string SceneAsyncManager.GetSceneNameFromIndex(int BuildIndex)