PlayerUpgrades
item [] PlayerUpgrades.fishMaterialTypeRequirement
item [] PlayerUpgrades.rawMaterialTypeRequirement
int [] PlayerUpgrades.fishMaterialAmountRequirement
int [] PlayerUpgrades.rawMaterialAmountRequirement
bool PlayerUpgrades.isUniqueFeatureUsed
Referenced by IsUniqueFeatureUsed.
bool PlayerUpgrades.isLowTierUpgrade
Referenced by IsLowTierUpgrade.
string PlayerUpgrades.ID
Referenced by UpgradeDatabase.GetUpgradeReference.
item[] PlayerUpgrades.GetFishMaterialTypeRequirement()
Referenced by RequirementChecker.CheckRequirement, PlayerSkills.SetRequirements.
item[] PlayerUpgrades.GetRawMaterialTypeRequirement()
Referenced by RequirementChecker.CheckRequirement, PlayerSkills.SetRequirements.
int[] PlayerUpgrades.GetFishMaterialAmountRequirement()
Referenced by RequirementChecker.CheckRequirement, PlayerSkills.SetRequirements.
int[] PlayerUpgrades.GetRawMaterialAmountRequirement()
Referenced by RequirementChecker.CheckRequirement, PlayerSkills.SetRequirements.
bool PlayerUpgrades.IsUniqueFeatureUsed()
References isUniqueFeatureUsed.
Referenced by PlayerMovement.IsInvincible.
bool PlayerUpgrades.IsLowTierUpgrade()
References isLowTierUpgrade.
Referenced by PlayerMovement.IsInvincible.
virtual PlayerUpgrades PlayerUpgrades.GetCopy()
Referenced by UpgradeDatabase.GetUpgradeCopy.