NPCAISystemTypeA
NPCAITypeAReactinStyle NPCAISystemTypeA.reactionStyle
Referenced by Update.
List<FSMBaseState> NPCAISystemTypeA.possibleStatesSOInstance
Referenced by Awake, GetStateSOInstanceByName.
List<string> NPCAISystemTypeA.possibleStatesNames
Referenced by Awake, GetStateSOInstanceByName.
CommandSlotsHolderManager NPCAISystemTypeA.commandSlotsHolderManager
Referenced by Awake.
NavMeshAgent NPCAISystemTypeA.agent
Referenced by Awake.
CameraSightPerceptionSensor2D NPCAISystemTypeA.sensor
Referenced by Update.
WaypointPath NPCAISystemTypeA.waypointComp
Referenced by Awake.
bool NPCAISystemTypeA.isUseWaypoint
Referenced by Awake, HandleEnterPatrolState.
RotationConstraint NPCAISystemTypeA.rotationConstraint
Referenced by Awake.
Transform NPCAISystemTypeA.target
override void NPCAISystemTypeA.Awake()
References FSMSystemBase._curState, agent, Chase, commandSlotsHolderManager, Flee, HandleEnterPatrolState, isUseWaypoint, possibleStatesNames, possibleStatesSOInstance, rotationConstraint, waypointComp.
override void NPCAISystemTypeA.Update()
References Chase, Flee, GetStateSOInstanceByName, HandleEnterPatrolState, reactionStyle, sensor, FSMSystemBase.TryEnterState, CameraSightPerceptionSensor2D.visibleRenderers.
void NPCAISystemTypeA.HandleEnterPatrolState()
References GetStateSOInstanceByName, isUseWaypoint, FSMSystemBase.TryEnterState.
Referenced by Awake, Update.
void NPCAISystemTypeA.TryEnterStateByName(string nextStateName)
References GetStateSOInstanceByName, FSMSystemBase.TryEnterState.
FSMBaseState NPCAISystemTypeA.GetStateSOInstanceByName(string stateName)
References possibleStatesNames, possibleStatesSOInstance.
Referenced by HandleEnterPatrolState, TryEnterStateByName, Update.
void NPCAISystemTypeA.OnEnable()
void NPCAISystemTypeA.OnDrawGizmos()