AudioManager
AudioManager AudioManager.instance
Referenced by SingleTonOnClickHelper.AudioManPlayBGM, SingleTonOnClickHelper.AudioManPlaySFX, SingleTonOnClickHelper.AudioManResetVolumeSettingsToDefault, SingleTonOnClickHelper.AudioManSaveVolumeSettingsPlayerPrefs, PlayerMovement.Command_Interact, UIVolumeSlider.OnBGMVolumeSliderValueChanged, PlayerBullet.OnHitBox, UIVolumeSlider.OnOverallVolumeSliderValueChanged, UIVolumeSlider.OnSFXVolumeSliderValueChanged, TestDialogue.StartUpdating.
float AudioManager.defaultSFXMasterVolume
Referenced by ResetVolumeSettingsToDefault.
float AudioManager.defaultBGMMasterVolume
Referenced by ResetVolumeSettingsToDefault.
float AudioManager.defaultOverallVolume
Referenced by ResetVolumeSettingsToDefault.
bool AudioManager.isVolumeSettingSaved
Referenced by LoadVolumeSettingsPlayerPrefs, SaveVolumeSettingsPlayerPrefs.
bool AudioManager.isApplicationRunInBackground
float AudioManager.SFXMasterVolume
Referenced by LoadVolumeSettingsPlayerPrefs, UIVolumeSlider.OnSFXVolumeSliderValueChanged, ResetVolumeSettingsToDefault, SaveVolumeSettingsPlayerPrefs.
float AudioManager.BGMMasterVolume
Referenced by LoadVolumeSettingsPlayerPrefs, UIVolumeSlider.OnBGMVolumeSliderValueChanged, ResetVolumeSettingsToDefault, SaveVolumeSettingsPlayerPrefs.
float AudioManager.overallVolume
Referenced by LoadVolumeSettingsPlayerPrefs, UIVolumeSlider.OnOverallVolumeSliderValueChanged, ResetVolumeSettingsToDefault, SaveVolumeSettingsPlayerPrefs.
Sound AudioManager.currSFX
Referenced by PlaySFX.
Sound AudioManager.currBGM
Referenced by PlayBGM, PlayBGMFadeTransition.
GameObject AudioManager.multiAudioSourceObj
Referenced by PlayBGM, PlayBGMFadeTransition, PlaySFX.
List<Sound> AudioManager.soundsSFX
Referenced by PlaySFX.
List<Sound> AudioManager.soundsBGM
Referenced by PlayBGM, PlayBGMFadeTransition, StopBGM, StopBGMFadeOutTransition.
Transform AudioManager.sfxChild
Transform AudioManager.bgmChild
string AudioManager.currSceneName
float AudioManager.bgmFadeInDuration
float AudioManager.bgmFadeOutDuration
void AudioManager.Awake()
void AudioManager.OnEnable()
void AudioManager.Update()
void AudioManager.InitNewAudioSFXSource(Sound s)
void AudioManager.InitNewAudioBGMSource(Sound s)
void AudioManager.OnSceneChanged()
void AudioManager.ResetVolumeSettingsToDefault()
References BGMMasterVolume, defaultBGMMasterVolume, defaultOverallVolume, defaultSFXMasterVolume, overallVolume, SFXMasterVolume.
Referenced by SingleTonOnClickHelper.AudioManResetVolumeSettingsToDefault.
void AudioManager.LoadVolumeSettingsPlayerPrefs()
References BGMMasterVolume, isVolumeSettingSaved, overallVolume, SFXMasterVolume.
void AudioManager.SaveVolumeSettingsPlayerPrefs()
References BGMMasterVolume, isVolumeSettingSaved, overallVolume, SFXMasterVolume.
Referenced by SingleTonOnClickHelper.AudioManSaveVolumeSettingsPlayerPrefs, UIVolumeSlider.OnBGMVolumeSliderValueChanged, UIVolumeSlider.OnOverallVolumeSliderValueChanged, UIVolumeSlider.OnSFXVolumeSliderValueChanged.
void AudioManager.PlaySFX(string sfxName)
References currSFX, Sound.isAllowMultiAudioSrcInstance, multiAudioSourceObj, soundsSFX, Sound.source.
Referenced by SingleTonOnClickHelper.AudioManPlaySFX, PlayerMovement.Command_Interact, PlayerBullet.OnHitBox, TestDialogue.StartUpdating.
void AudioManager.PlayBGM(string bgmName)
References currBGM, Sound.isAllowMultiAudioSrcInstance, multiAudioSourceObj, Sound.name, soundsBGM, Sound.source.
Referenced by SingleTonOnClickHelper.AudioManPlayBGM.
void AudioManager.StopBGM(string name)
References soundsBGM, Sound.source.
void AudioManager.PlayBGMFadeTransition(string name)
References currBGM, AudioFade.FadeIn, Sound.isAllowMultiAudioSrcInstance, multiAudioSourceObj, Sound.name, soundsBGM, Sound.source, StopBGMFadeOutTransition.
void AudioManager.StopBGMFadeOutTransition(string name)
References AudioFade.FadeOut, soundsBGM.
Referenced by PlayBGMFadeTransition.