UnityEngine::PostProcessing::GraphicsUtils
bool UnityEngine.PostProcessing.GraphicsUtils.isLinearColorSpace
bool UnityEngine.PostProcessing.GraphicsUtils.supportsDX11
Texture2D UnityEngine.PostProcessing.GraphicsUtils.whiteTexture
Mesh UnityEngine.PostProcessing.GraphicsUtils.quad
Referenced by UnityEngine.PostProcessing.AmbientOcclusionComponent.PopulateCommandBuffer.
Texture2D UnityEngine.PostProcessing.GraphicsUtils.s_WhiteTexture
Mesh UnityEngine.PostProcessing.GraphicsUtils.s_Quad
static void UnityEngine.PostProcessing.GraphicsUtils.Blit(Material material, int pass)
Referenced by UnityEngine.PostProcessing.DepthOfFieldComponent.Prepare, UnityEngine.PostProcessing.TaaComponent.Render.
static void UnityEngine.PostProcessing.GraphicsUtils.ClearAndBlit(Texture source, RenderTexture destination, Material material, int pass, bool clearColor=true, bool clearDepth=false)
static void UnityEngine.PostProcessing.GraphicsUtils.Destroy(UnityObject obj)
Referenced by UnityEngine.PostProcessing.GraphicsUtils.Dispose, UnityEngine.PostProcessing.MaterialFactory.Dispose, UnityEngine.PostProcessing.ChromaticAberrationComponent.OnDisable, UnityEngine.PostProcessing.ColorGradingComponent.OnDisable, UnityEngine.PostProcessing.EyeAdaptationComponent.OnDisable, UnityEngine.PostProcessing.GrainComponent.OnDisable, UnityEngine.PostProcessing.GrainComponent.Prepare.
static void UnityEngine.PostProcessing.GraphicsUtils.Dispose()
References UnityEngine.PostProcessing.GraphicsUtils.Destroy.