PlayerSkills
SkillType
EventHandler<OnSkillUnlockedEventArgs> PlayerSkills.OnSkillUnlocked
List<SkillType> PlayerSkills.unlockedSkillTypeList
int PlayerSkills.skillPoints
item [] PlayerSkills.fishR
item [] PlayerSkills.rawR
int [] PlayerSkills.fishNumR
int [] PlayerSkills.rawNumR
storage PlayerSkills.inv
PlayerUpgrades PlayerSkills.upg
readonly List<item> PlayerSkills.itemsToRemove
Action PlayerSkills.OnSetRequirementForPopup
PlayerSkills.PlayerSkills()
void PlayerSkills.GetCurrentUpgrades(UpgradeHolder upgradeHolder)
References UpgradeHolder.GetHullUpgrades, UpgradeHolder.GetInventoryUpgrades, UpgradeHolder.GetOxygenTankUpgrades, UpgradeHolder.GetSelfRepairUpgrades, UpgradeHolder.GetTurbineUpgrades, UpgradeHolder.GetWeaponUpgrades, UpgradeHolder.HullUpgrade, UpgradeHolder.InventoryUpgrade, UpgradeHolder.OxygenTankUpgrade, UpgradeHolder.SelfRepairUpgrade, UpgradeHolder.TurbineUpgrade, UpgradeHolder.WeaponUpgrade.
void PlayerSkills.SetRequirements(storage inv, PlayerUpgrades upg)
References PlayerUpgrades.GetFishMaterialAmountRequirement, PlayerUpgrades.GetFishMaterialTypeRequirement, PlayerUpgrades.GetRawMaterialAmountRequirement, PlayerUpgrades.GetRawMaterialTypeRequirement.
bool PlayerSkills.IsRequirementMet()
References itemSlots.Amount, storage.GetListOfItemsInInventory, itemSlots.Item.
Referenced by TryUnlockSkill.
void PlayerSkills.RemoveAllUsedResources()
References ItemContainer.removeItemWithAmount.
Referenced by TryUnlockSkill.
int PlayerSkills.GetSkillPoints()
bool PlayerSkills.IsSkillUnlocked(SkillType skillType)
Referenced by CanUnlock.
bool PlayerSkills.CanUnlock(SkillType skillType)
References GetSkillRequirement, IsSkillUnlocked.
Referenced by TryUnlockSkill.
SkillType PlayerSkills.GetSkillRequirement(SkillType skillType)
Referenced by CanUnlock.
bool PlayerSkills.TryUnlockSkill(SkillType skillType)
References CanUnlock, IsRequirementMet, RemoveAllUsedResources.
void PlayerSkills.UnlockSkill(SkillType skillType)