DoxyRunner
DoxyThreadSafeOutput DoxyRunner.SafeOutput
List<string> DoxyRunner.DoxyLog
Action<int> DoxyRunner.onCompleteCallBack
Referenced by DoxyRunner, RunThreadedDoxy.
string DoxyRunner.EXE
Referenced by DoxyRunner, RunThreadedDoxy.
string [] DoxyRunner.Args
Referenced by DoxyRunner, RunThreadedDoxy.
string DoxyRunner.WorkingFolder
DoxyRunner.DoxyRunner(string exepath, string[] args, DoxyThreadSafeOutput safeoutput, Action< int > callback)
References Args, EXE, onCompleteCallBack.
void DoxyRunner.updateOuputString(string output)
References DoxyThreadSafeOutput.WriteLine.
Referenced by RunThreadedDoxy.
void DoxyRunner.RunThreadedDoxy()
References Args, EXE, onCompleteCallBack, Run, DoxyThreadSafeOutput.SetFinished, updateOuputString, DoxyThreadSafeOutput.WriteFullLog.
Referenced by DoxygenWindow.RunDoxygen.
static int DoxyRunner.Run(Action< string > output, TextReader input, string exe, params string[] args)
Runs the specified executable with the provided arguments and returns the process' exit code.
output Recieves the output of either std/err or std/out input Provides the line-by-line input that will be written to std/in, null for empty exe The executable to run, may be unqualified or contain environment variables args The list of unescaped arguments to provide to the executable Returns process' exit code after the program exits System.IO.FileNotFoundException Raised when the exe was not found System.ArgumentNullException Raised when one of the arguments is null System.ArgumentOutOfRangeException Raised if an argument contains '\0', '\r', or ' '
References EscapeArguments, FindExePath.
Referenced by RunThreadedDoxy.
static string DoxyRunner.EscapeArguments(params string[] args)
Quotes all arguments that contain whitespace, or begin with a quote and returns a single argument string for use with Process.Start().
args A list of strings for arguments, may not contain null, '\0', '\r', or ' ' The combined list of escaped/quoted strings System.ArgumentNullException Raised when one of the arguments is null System.ArgumentOutOfRangeException Raised if an argument contains '\0', '\r', or ' '
Referenced by Run.
static string DoxyRunner.FindExePath(string exe)
Expands environment variables and, if unqualified, locates the exe in the working directory or the evironment's path.
exe The name of the executable file The fully-qualified path to the file System.IO.FileNotFoundException Raised when the exe was not found
Referenced by Run.