AINavAgentCommon
static Vector3 AINavAgentCommon.RandomPosition(Vector3 origin, float radius)
Referenced by PatrolByRandomPos.PerformStateBehaviour, NavAgentTestAutoSetRandomDestination.SetNewDestination.
static bool AINavAgentCommon.HasAgentReachedDestination(NavMeshAgent mNavMeshAgent)
Referenced by PatrolByRandomPos.OnStayState, PatrolByWaypoints.OnStayState.