UnityEngine::PostProcessing::ColorGradingComponent
const int UnityEngine.PostProcessing.ColorGradingComponent.k_InternalLogLutSize
const int UnityEngine.PostProcessing.ColorGradingComponent.k_CurvePrecision
const float UnityEngine.PostProcessing.ColorGradingComponent.k_CurveStep
Texture2D UnityEngine.PostProcessing.ColorGradingComponent.m_GradingCurves
override bool UnityEngine.PostProcessing.ColorGradingComponent.active
float UnityEngine.PostProcessing.ColorGradingComponent.StandardIlluminantY(float x)
Vector3 UnityEngine.PostProcessing.ColorGradingComponent.CIExyToLMS(float x, float y)
Vector3 UnityEngine.PostProcessing.ColorGradingComponent.CalculateColorBalance(float temperature, float tint)
Texture2D UnityEngine.PostProcessing.ColorGradingComponent.GetCurveTexture()
bool UnityEngine.PostProcessing.ColorGradingComponent.IsLogLutValid(RenderTexture lut)
void UnityEngine.PostProcessing.ColorGradingComponent.GenerateLut()
static Color UnityEngine.PostProcessing.ColorGradingComponent.NormalizeColor(Color c)
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.ClampVector(Vector3 v, float min, float max)
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.GetLiftValue(Color lift)
Referenced by UnityEngine.PostProcessing.ColorGradingComponent.CalculateLiftGammaGain.
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.GetGammaValue(Color gamma)
Referenced by UnityEngine.PostProcessing.ColorGradingComponent.CalculateLiftGammaGain.
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.GetGainValue(Color gain)
Referenced by UnityEngine.PostProcessing.ColorGradingComponent.CalculateLiftGammaGain.
static void UnityEngine.PostProcessing.ColorGradingComponent.CalculateLiftGammaGain(Color lift, Color gamma, Color gain, out Vector3 outLift, out Vector3 outGamma, out Vector3 outGain)
References UnityEngine.PostProcessing.ColorGradingComponent.GetGainValue, UnityEngine.PostProcessing.ColorGradingComponent.GetGammaValue, UnityEngine.PostProcessing.ColorGradingComponent.GetLiftValue.
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.GetSlopeValue(Color slope)
Referenced by UnityEngine.PostProcessing.ColorGradingComponent.CalculateSlopePowerOffset.
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.GetPowerValue(Color power)
Referenced by UnityEngine.PostProcessing.ColorGradingComponent.CalculateSlopePowerOffset.
static Vector3 UnityEngine.PostProcessing.ColorGradingComponent.GetOffsetValue(Color offset)
Referenced by UnityEngine.PostProcessing.ColorGradingComponent.CalculateSlopePowerOffset.
static void UnityEngine.PostProcessing.ColorGradingComponent.CalculateSlopePowerOffset(Color slope, Color power, Color offset, out Vector3 outSlope, out Vector3 outPower, out Vector3 outOffset)
References UnityEngine.PostProcessing.ColorGradingComponent.GetOffsetValue, UnityEngine.PostProcessing.ColorGradingComponent.GetPowerValue, UnityEngine.PostProcessing.ColorGradingComponent.GetSlopeValue.
override void UnityEngine.PostProcessing.ColorGradingComponent.Prepare(Material uberMaterial)
void UnityEngine.PostProcessing.ColorGradingComponent.OnGUI()
override void UnityEngine.PostProcessing.ColorGradingComponent.OnDisable()
References UnityEngine.PostProcessing.GraphicsUtils.Destroy.