CommandBase
CastState
Info CommandBase.info
Referenced by InputCommand.ExecDown, InputCommand.ExecDownCharging, InputCommand.ExecPress, InputCommand.ExecRelease, Init, InputCommand.OnInput, CommandQueue.TryExecuteCommand.
InstanceInfoRuntime CommandBase.instanceInfo
Referenced by CalculateElapsedTime, CreateNewInstanceOfSelf, Execd, ExecDown, ExecDownCharging, ExecPress, EnableDisableGameObjectCommand.ExecPress, SetMaterialColorCommand.ExecPress, ExecRelease, Init, InitGameObj, OnDisable, OnEnable, CommandEventListener.OnEventRaised, OnExternalUpdate, TryExecCommand.
CooldownInfo CommandBase.cooldownInfo
Referenced by HandleCooldown, InputCommand.SetExecInfo.
ExecutionInfo CommandBase.execInfo
Referenced by Execd, ExecDown, InputCommand.ExecDown, ExecDownCharging, InputCommand.ExecDownCharging, ExecPress, InputCommand.ExecPress, ExecRelease, InputCommand.ExecRelease, CommandEventListener.Init, OnDisable, OnEnable.
virtual string CommandBase.aName
Referenced by CommandQueueHelper.CheckSequence, CommandManagerOld.CheckSequence, CommandQueue.Enqueue, CommandQueueHelper.ExecCommand_HoldRelease, InputCommand.ExecDown, InputCommand.ExecDownCharging, InputCommand.ExecRelease, Init, CommandQueue.Remove.
virtual float CommandBase.TimeStamp
Referenced by CommandQueue.Enqueue.
virtual float CommandBase.ElapsedTime
virtual int CommandBase.id
Referenced by Init.
virtual void CommandBase.Activate(GameObject ownerRootParentObj=null)
Referenced by HandleCooldown.
virtual void CommandBase.BeginCooldown(GameObject ownerRootParentObj=null)
Referenced by HandleCooldown.
virtual void CommandBase.StayCooldown(GameObject ownerRootParentObj=null)
Referenced by HandleCooldown.
virtual void CommandBase.EndCooldown(GameObject ownerRootParentObj=null)
Referenced by HandleCooldown.
void CommandBase.HandleCooldown(GameObject ownerRootParentObj)
References Activate, BeginCooldown, CommandBase.CooldownInfo.castState, cooldownInfo, CommandBase.CooldownInfo.cooldownTime, CommandBase.CooldownInfo.curCoolDownTimeElapsed, EndCooldown, CommandBase.CooldownInfo.isCastingNow, StayCooldown.
Referenced by OnExternalUpdate.
virtual void CommandBase.TryExecCommand()
References CommandBase.InstanceInfoRuntime._isEnabled, CommandBase.InstanceInfoRuntime.ElapsedTime, instanceInfo, CommandBase.InstanceInfoRuntime.TimeStamp.
virtual void CommandBase.OnExternalUpdate()
References CommandBase.InstanceInfoRuntime._isEnabled, CalculateElapsedTime, CommandBase.InstanceInfoRuntime.commandOwnerRootObj, HandleCooldown, instanceInfo.
virtual void CommandBase.CalculateElapsedTime()
References CommandBase.InstanceInfoRuntime._isEnabled, CommandBase.InstanceInfoRuntime.ElapsedTime, instanceInfo.
Referenced by OnExternalUpdate.
virtual void CommandBase.ExecPress()
References CommandBase.InstanceInfoRuntime.commandOwnerRootObj, CommandBase.ExecutionInfo.curExecState, execInfo, CommandBase.ExecutionInfo.ExecPressEvent, CommandBase.ExecutionInfo.ExecPressHolderEvent, instanceInfo, CommandEvent.Raise.
virtual void CommandBase.ExecDown()
References CommandBase.InstanceInfoRuntime.commandOwnerRootObj, CommandBase.ExecutionInfo.curExecState, CommandBase.ExecutionInfo.ExecDownEvent, CommandBase.ExecutionInfo.ExecDownHolderEvent, execInfo, instanceInfo, CommandEvent.Raise.
virtual void CommandBase.ExecDownCharging()
References CommandBase.InstanceInfoRuntime.commandOwnerRootObj, CommandBase.ExecutionInfo.curExecState, CommandBase.ExecutionInfo.ExecDownChargingEvent, CommandBase.ExecutionInfo.ExecDownChargingHolderEvent, execInfo, instanceInfo, CommandEvent.Raise.
virtual void CommandBase.ExecRelease()
References CommandBase.InstanceInfoRuntime.commandOwnerRootObj, CommandBase.ExecutionInfo.curExecState, execInfo, CommandBase.ExecutionInfo.ExecReleaseEvent, CommandBase.ExecutionInfo.ExecReleaseHolderEvent, instanceInfo, CommandEvent.Raise.
virtual void CommandBase.Execd()
References CommandBase.InstanceInfoRuntime.commandOwnerRootObj, CommandBase.ExecutionInfo.curExecState, CommandBase.ExecutionInfo.ExecdEvent, CommandBase.ExecutionInfo.ExecdHolderEvent, execInfo, instanceInfo, CommandEvent.Raise.
virtual void CommandBase.InitGameObj(GameObject ownerRootParentObj)
References CommandBase.InstanceInfoRuntime.commandOwnerRootObj, instanceInfo.
virtual void CommandBase.Init()
References CommandBase.Info._aName, CommandBase.InstanceInfoRuntime._id, aName, id, info, instanceInfo.
Referenced by OnEnable.
virtual CommandBase CommandBase.CreateNewInstanceOfSelf(GameObject newInstigatorObjRef=null)
References instanceInfo, CommandBase.InstanceInfoRuntime.isSoInstance.
Referenced by CommandQueue.TryExecuteCommand.
virtual void CommandBase.Awake()
virtual void CommandBase.OnEnable()
References CommandBase.InstanceInfoRuntime._isEnabled, CommandBase.InstanceInfoRuntime._isExecuted, CommandBase.ExecutionInfo.curExecState, execInfo, Init, instanceInfo.
virtual void CommandBase.OnDisable()
References CommandBase.InstanceInfoRuntime._isEnabled, CommandBase.ExecutionInfo.curExecState, execInfo, instanceInfo.
virtual void CommandBase.OnDestroy()
virtual void CommandBase.Undo()
Referenced by CommandQueue.UndoLastCommand.