ItemContainer
List<itemSlots> ItemContainer.ItemSlots
Referenced by addItem, Awake, CheckIfSlotIsEmpty, Clear, storage.GetListOfItemsInInventory, IsFull, ItemSaveManager.LoadInventory, removeItem, removeItemWithAmount, ItemSaveManager.SaveInventory, storage.SetInventoryUpgrade.
Action<itemSlots> ItemContainer.OnPointerEnterEvent
Referenced by Awake.
Action<itemSlots> ItemContainer.OnPointerExitEvent
Referenced by Awake.
Action<itemSlots> ItemContainer.OnLeftClickEvent
Referenced by Awake.
Action<itemSlots> ItemContainer.OnBeginDragEvent
Referenced by Awake.
Action<itemSlots> ItemContainer.OnEndDragEvent
Referenced by Awake.
Action<itemSlots> ItemContainer.OnDragEvent
Referenced by Awake.
Action<itemSlots> ItemContainer.OnDropEvent
Referenced by Awake.
int ItemContainer.passRemaining
virtual void ItemContainer.Awake()
References ItemSlots, OnBeginDragEvent, OnDragEvent, OnDropEvent, OnEndDragEvent, OnLeftClickEvent, OnPointerEnterEvent, OnPointerExitEvent.
bool ItemContainer.CheckIfSlotIsEmpty(item item)
References item.ID, ItemSlots, item.maxStack.
Referenced by PlayerMovement.Command_Interact.
bool ItemContainer.addItem(item item)
References item.ID, ItemSlots, item.maxStack.
Referenced by PlayerMovement.Command_Interact.
bool ItemContainer.removeItem(item item)
References ItemSlots.
bool ItemContainer.discardItem(itemSlots item)
Referenced by Character.BeginDiscard.
bool ItemContainer.removeItemWithAmount(item item, int amount)
References ItemSlots.
Referenced by PlayerSkills.RemoveAllUsedResources.
bool ItemContainer.IsFull()
References ItemSlots.
void ItemContainer.Clear()
References ItemSlots.
Referenced by ItemSaveManager.LoadInventory.
void ItemContainer.EventHelper(itemSlots itemSlot, Action< itemSlots > action)