CommandEvent
GameObject CommandEvent.instigatorObj
Referenced by Raise.
virtual void CommandEvent.Raise(GameObject instigatorObjRef)
References instigatorObj, GameEvent.Raise.
Referenced by CommandBase.Execd, CommandBase.ExecDown, CommandBase.ExecDownCharging, CommandBase.ExecPress, CommandBase.ExecRelease.