CharacterMove
List<Move> CharacterMove.commandList
int CharacterMove.index
float CharacterMove.verticalOffset
Vector3 CharacterMove.startPoint
PathDraw CharacterMove.pathDrawer
void CharacterMove.Start()
void CharacterMove.AddCommand(Move command)
References Move.Execute, UpdateLine.
void CharacterMove.UndoCommand()
References UpdateLine.
void CharacterMove.RedoCommand()
References UpdateLine.
void CharacterMove.UpdateLine()
References PathDraw.UpdateLine.
Referenced by AddCommand, RedoCommand, UndoCommand.