InputHandlerOld_NewInputSystem
List<CommandBase> InputHandlerOld_NewInputSystem.inputCommands
Referenced by GetCommandByNameInCommandList, CommandEventListener.InitTypeA.
GameObject InputHandlerOld_NewInputSystem.instigatorObj
List<string> InputHandlerOld_NewInputSystem.inputCommandsNames
CommandQueueHelper InputHandlerOld_NewInputSystem._commandQueueHelper
virtual CommandQueueHelper InputHandlerOld_NewInputSystem.commandQueueHelper
void InputHandlerOld_NewInputSystem.Awake()
void InputHandlerOld_NewInputSystem.Update()
CommandBase InputHandlerOld_NewInputSystem.GetCommandByNameInCommandList(string commandName)
References inputCommands.
Referenced by OnCommandSlot0, OnCommandSlot1, OnCommandSlot2, OnCommandSlot3, OnDPadAxisHorizontal, OnDPadAxisVertical, OnLeftStickAxisHorizontal, OnLeftStickAxisVertical, OnSecondaryCommandSlot4, OnSecondaryCommandSlot5, OnSelect, OnStart, OnTertiaryCommandSlotAxis6, OnTertiaryCommandSlotAxis7.
void InputHandlerOld_NewInputSystem.OnCommandSlot0(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnCommandSlot1(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnCommandSlot2(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnCommandSlot3(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnSecondaryCommandSlot4(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnSecondaryCommandSlot5(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnTertiaryCommandSlotAxis6(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnTertiaryCommandSlotAxis7(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnSelect(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnStart(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnDPadAxisHorizontal(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnDPadAxisVertical(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnLeftStickAxisHorizontal(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnLeftStickAxisVertical(InputAction.CallbackContext context)
References CommandQueueHelper.ExecCommand_InputSystem, GetCommandByNameInCommandList.
void InputHandlerOld_NewInputSystem.OnRightStickAxisHorizontal(InputAction.CallbackContext context)
void InputHandlerOld_NewInputSystem.OnRightStickAxisVertical(InputAction.CallbackContext context)