Weapon
PlayerBullet Weapon.playerBullet
float Weapon.attackRate
float Weapon.attackDamage
float Weapon.attackSpeed
float Weapon.GetAttackRate()
Referenced by PlayerAttack.SimulateShoot.
float Weapon.GetAttackDamage()
Referenced by PlayerAttack.SimulateShoot.
float Weapon.GetAttackSpeed()
Referenced by PlayerAttack.SimulateShoot.
PlayerBullet Weapon.GetPlayerBullet()