SerializableQueueList
List<T> SerializableQueueList< T >.queueList
Referenced by SerializableQueueList< T >.Add, SerializableQueueList< T >.Clear, SerializableQueueList< T >.Contains, SerializableQueueList< T >.Dequeue, SerializableQueueList< T >.Peek, SerializableQueueList< T >.Remove, SerializableQueueList< T >.RemoveAt, SerializableQueueList< T >.ToArray.
virtual int SerializableQueueList< T >.Count
void SerializableQueueList< T >.Enqueue(T t)
References SerializableQueueList< T >.Add.
T SerializableQueueList< T >.Dequeue()
References SerializableQueueList< T >.queueList, SerializableQueueList< T >.RemoveAt.
void SerializableQueueList< T >.OnQueueModified()
Referenced by SerializableQueueList< T >.Add, SerializableQueueList< T >.Remove, SerializableQueueList< T >.RemoveAt.
void SerializableQueueList< T >.Clear()
References SerializableQueueList< T >.queueList.
T SerializableQueueList< T >.Peek()
References SerializableQueueList< T >.queueList.
T[] SerializableQueueList< T >.ToArray()
References SerializableQueueList< T >.queueList.
void SerializableQueueList< T >.Add(T t)
References SerializableQueueList< T >.OnQueueModified, SerializableQueueList< T >.queueList.
Referenced by SerializableQueueList< T >.Enqueue.
bool SerializableQueueList< T >.Remove(T t)
References SerializableQueueList< T >.OnQueueModified, SerializableQueueList< T >.queueList.
void SerializableQueueList< T >.RemoveAt(int i)
References SerializableQueueList< T >.OnQueueModified, SerializableQueueList< T >.queueList.
Referenced by SerializableQueueList< T >.Dequeue.
bool SerializableQueueList< T >.Contains(T t)
References SerializableQueueList< T >.queueList.