GenericDictionary
List<KeyValuePair> GenericDictionary< TKey, TValue >.list
Dictionary<TKey, int> GenericDictionary< TKey, TValue >.indexByKey
Dictionary<TKey, TValue> GenericDictionary< TKey, TValue >.dict
bool GenericDictionary< TKey, TValue >.keyCollision
TValue GenericDictionary< TKey, TValue >.this[TKey key]
ICollection<TKey> GenericDictionary< TKey, TValue >.Keys
ICollection<TValue> GenericDictionary< TKey, TValue >.Values
int GenericDictionary< TKey, TValue >.Count
bool GenericDictionary< TKey, TValue >.IsReadOnly
void GenericDictionary< TKey, TValue >.OnBeforeSerialize()
void GenericDictionary< TKey, TValue >.OnAfterDeserialize()
References GenericDictionary< TKey, TValue >.ContainsKey.
void GenericDictionary< TKey, TValue >.Add(TKey key, TValue value)
Referenced by GenericDictionary< TKey, TValue >.Add.
bool GenericDictionary< TKey, TValue >.ContainsKey(TKey key)
Referenced by GenericDictionary< TKey, TValue >.OnAfterDeserialize.
bool GenericDictionary< TKey, TValue >.Remove(TKey key)
Referenced by GenericDictionary< TKey, TValue >.Remove.
bool GenericDictionary< TKey, TValue >.TryGetValue(TKey key, out TValue value)
void GenericDictionary< TKey, TValue >.Add(KeyValuePair< TKey, TValue > pair)
References GenericDictionary< TKey, TValue >.Add.
void GenericDictionary< TKey, TValue >.Clear()
bool GenericDictionary< TKey, TValue >.Contains(KeyValuePair< TKey, TValue > pair)
void GenericDictionary< TKey, TValue >.CopyTo(KeyValuePair< TKey, TValue >[] array, int arrayIndex)
bool GenericDictionary< TKey, TValue >.Remove(KeyValuePair< TKey, TValue > pair)
References GenericDictionary< TKey, TValue >.Remove.
IEnumerator< KeyValuePair< TKey, TValue > > GenericDictionary< TKey, TValue >.GetEnumerator()
void GenericDictionary< TKey, TValue >.UpdateIndexes(int removedIndex)
IEnumerator IEnumerable. GenericDictionary< TKey, TValue >.GetEnumerator()