DoxyThreadSafeOutput
ReaderWriterLockSlim DoxyThreadSafeOutput.outputLock
string DoxyThreadSafeOutput.CurrentOutput
List<string> DoxyThreadSafeOutput.FullLog
bool DoxyThreadSafeOutput.Finished
bool DoxyThreadSafeOutput.Started
string DoxyThreadSafeOutput.ReadLine()
void DoxyThreadSafeOutput.SetFinished()
Referenced by DoxyRunner.RunThreadedDoxy.
void DoxyThreadSafeOutput.SetStarted()
Referenced by DoxygenWindow.RunDoxygen.
bool DoxyThreadSafeOutput.isStarted()
bool DoxyThreadSafeOutput.isFinished()
List< string > DoxyThreadSafeOutput.ReadFullLog()
void DoxyThreadSafeOutput.WriteFullLog(List< string > newLog)
Referenced by DoxyRunner.RunThreadedDoxy.
void DoxyThreadSafeOutput.WriteLine(string newOutput)
Referenced by DoxyRunner.updateOuputString.