TutoManager
List<Tutorial> TutoManager.tutorials
Referenced by TutoSequence.
Text TutoManager.dialogue
Referenced by NextTutorial, TutoComplete.
TutoManager TutoManager.tuto
Tutorial TutoManager.current
TutoManager TutoManager.instance
Referenced by ButtonTuto.CheckIfHappening, CloseButtonTuto.CheckIfHappening, ContinueNextTuto.CheckIfHappening, HoldKeyInputTuto.CheckIfHappening, KeyInputTuto.CheckIfHappening, TriggerTransitionTuto.OnTriggerEnter2D.
void TutoManager.Start()
void TutoManager.Update()
Tutorial TutoManager.TutoSequence(int order)
References tutorials.
Referenced by NextTutorial.
void TutoManager.NextTutorial(int onSequence)
References dialogue, TutoComplete, Tutorial.tutoDialogue, TutoSequence.
Referenced by EndTuto.
void TutoManager.TutoComplete()
References dialogue.
Referenced by NextTutorial.
void TutoManager.EndTuto()
References NextTutorial, Tutorial.sequence.
Referenced by ButtonTuto.CheckIfHappening, CloseButtonTuto.CheckIfHappening, ContinueNextTuto.CheckIfHappening, HoldKeyInputTuto.CheckIfHappening, KeyInputTuto.CheckIfHappening, TriggerTransitionTuto.OnTriggerEnter2D.