FSMSystemBase
FSMBaseState FSMSystemBase._curState
Referenced by Awake, NPCAISystemTypeA.Awake, TryEnterState, Update.
FSMBaseState FSMSystemBase._prevState
FSMBaseState FSMSystemBase._startingState
Referenced by Awake.
bool FSMSystemBase.isDebugLog
Referenced by FSMBaseState.OnEnterState, FSMBaseState.OnExitState, FSMBaseState.OnStayState, FSMBaseState.OnUpdate, PatrolByWaypoints.PerformStateBehaviour.
virtual void FSMSystemBase.Awake()
References _curState, _startingState, FSMBaseState.OnEnterState.
virtual void FSMSystemBase.Update()
References _curState, FSMBaseState.OnUpdate.
virtual void FSMSystemBase.TryEnterState(FSMBaseState nextState)
References _curState, FSMBaseState.OnEnterState, FSMBaseState.OnExitState.
Referenced by NPCAISystemTypeA.HandleEnterPatrolState, NPCAISystemTypeA.TryEnterStateByName, NPCAISystemTypeA.Update.