RebindUISampleActionsModified::IGameplaySampleUnusedActions
void RebindUISampleActionsModified.IGameplaySampleUnusedActions.OnMove(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.GameplaySampleUnusedActions.SetCallbacks.
void RebindUISampleActionsModified.IGameplaySampleUnusedActions.OnLook(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.GameplaySampleUnusedActions.SetCallbacks.
void RebindUISampleActionsModified.IGameplaySampleUnusedActions.OnInteract(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.GameplaySampleUnusedActions.SetCallbacks.