RebindUISampleActionsModified::IVector2AxisActions
void RebindUISampleActionsModified.IVector2AxisActions.OnNewaction(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.Vector2AxisActions.SetCallbacks.
void RebindUISampleActionsModified.IVector2AxisActions.OnLeftStickAxis2D(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.Vector2AxisActions.SetCallbacks.
void RebindUISampleActionsModified.IVector2AxisActions.OnRightStickAxis2D(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.Vector2AxisActions.SetCallbacks.
void RebindUISampleActionsModified.IVector2AxisActions.OnDPadAxis2D(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.Vector2AxisActions.SetCallbacks.