TanksInputActions::IUIActions
void TanksInputActions.IUIActions.OnNavigate(InputAction.CallbackContext context)
Referenced by TanksInputActions.UIActions.SetCallbacks.
void TanksInputActions.IUIActions.OnSubmit(InputAction.CallbackContext context)
Referenced by TanksInputActions.UIActions.SetCallbacks.
void TanksInputActions.IUIActions.OnCancel(InputAction.CallbackContext context)
Referenced by TanksInputActions.UIActions.SetCallbacks.
void TanksInputActions.IUIActions.OnPoint(InputAction.CallbackContext context)
Referenced by TanksInputActions.UIActions.SetCallbacks.
void TanksInputActions.IUIActions.OnClick(InputAction.CallbackContext context)
Referenced by TanksInputActions.UIActions.SetCallbacks.