RebindUISampleActionsModified::IUIMainActions
void RebindUISampleActionsModified.IUIMainActions.OnNavigate(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.UIMainActions.SetCallbacks.
void RebindUISampleActionsModified.IUIMainActions.OnSubmit(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.UIMainActions.SetCallbacks.
void RebindUISampleActionsModified.IUIMainActions.OnCancel(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.UIMainActions.SetCallbacks.
void RebindUISampleActionsModified.IUIMainActions.OnPoint(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.UIMainActions.SetCallbacks.
void RebindUISampleActionsModified.IUIMainActions.OnClick(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.UIMainActions.SetCallbacks.