RebindUISampleActionsModified::IPlayerMainActions
void RebindUISampleActionsModified.IPlayerMainActions.OnCommandSlot0(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnCommandSlot1(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnCommandSlot2(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnCommandSlot3(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnSecondaryCommandSlot4(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnSecondaryCommandSlot5(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnTertiaryCommandSlotAxis6(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnTertiaryCommandSlotAxis7(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnStart(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnSelect(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnDPadAxisHorizontal(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnDPadAxisVertical(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnLeftStickAxisHorizontal(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnLeftStickAxisVertical(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnRightStickAxisHorizontal(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.
void RebindUISampleActionsModified.IPlayerMainActions.OnRightStickAxisVertical(InputAction.CallbackContext context)
Referenced by RebindUISampleActionsModified.PlayerMainActions.SetCallbacks.