TanksInputActions::IPlayerActions
void TanksInputActions.IPlayerActions.OnGas(InputAction.CallbackContext context)
Referenced by TanksInputActions.PlayerActions.SetCallbacks.
void TanksInputActions.IPlayerActions.OnBrake(InputAction.CallbackContext context)
Referenced by TanksInputActions.PlayerActions.SetCallbacks.
void TanksInputActions.IPlayerActions.OnTurret(InputAction.CallbackContext context)
Referenced by TanksInputActions.PlayerActions.SetCallbacks.
void TanksInputActions.IPlayerActions.OnFire(InputAction.CallbackContext context)
Referenced by TanksInputActions.PlayerActions.SetCallbacks.
void TanksInputActions.IPlayerActions.OnPause(InputAction.CallbackContext context)
Referenced by TanksInputActions.PlayerActions.SetCallbacks.