.TH "AStarPathFinder" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AStarPathFinder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMaze\fP \fBmaze\fP"
.br
.ti -1c
.RI "Color \fBclosedColor\fP"
.br
.ti -1c
.RI "Color \fBopenColor\fP"
.br
.ti -1c
.RI "GameObject \fBstart\fP"
.br
.ti -1c
.RI "GameObject \fBend\fP"
.br
.ti -1c
.RI "GameObject \fBpathP\fP"
.br
.ti -1c
.RI "GameObject \fBenemy\fP"
.br
.ti -1c
.RI "GameObject \fBplayer\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Color AStarPathFinder\&.closedColor"

.SS "GameObject AStarPathFinder\&.end"

.SS "GameObject AStarPathFinder\&.enemy"

.SS "\fBMaze\fP AStarPathFinder\&.maze"

.SS "Color AStarPathFinder\&.openColor"

.SS "GameObject AStarPathFinder\&.pathP"

.SS "GameObject AStarPathFinder\&.player"

.SS "GameObject AStarPathFinder\&.start"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
