.TH "AudioFade" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioFade
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static IEnumerator \fBFadeOut\fP (\fBSound\fP sound, float fadingTime, Func< float, float, float, float > Interpolate)"
.br
.ti -1c
.RI "static IEnumerator \fBFadeIn\fP (\fBSound\fP sound, float fadingTime, Func< float, float, float, float > Interpolate)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static IEnumerator AudioFade\&.FadeIn (\fBSound\fP sound, float fadingTime, Func< float, float, float, float > Interpolate)\fC [static]\fP"

.SS "static IEnumerator AudioFade\&.FadeOut (\fBSound\fP sound, float fadingTime, Func< float, float, float, float > Interpolate)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
