.TH "AutoFlipSpriteByDir" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoFlipSpriteByDir
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBClampRotation2\fP (float angle, float min, float max)"
.br
.ti -1c
.RI "bool \fBIsWithinArbitaryRot\fP (float angle, float min, float max)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SpriteRenderer \fBsprite\fP"
.br
.ti -1c
.RI "Rigidbody2D \fBrb\fP"
.br
.ti -1c
.RI "bool \fBhasRb\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float AutoFlipSpriteByDir\&.ClampRotation2 (float angle, float min, float max)"

.SS "bool AutoFlipSpriteByDir\&.IsWithinArbitaryRot (float angle, float min, float max)"

.SH "Member Data Documentation"
.PP 
.SS "bool AutoFlipSpriteByDir\&.hasRb"

.SS "Rigidbody2D AutoFlipSpriteByDir\&.rb"

.SS "SpriteRenderer AutoFlipSpriteByDir\&.sprite"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
