.TH "breakableWall" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breakableWall
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBbulletPrefab\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpar\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpar2\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpar3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GameObject breakableWall\&.bulletPrefab"

.SS "ParticleSystem breakableWall\&.par"

.SS "ParticleSystem breakableWall\&.par2"

.SS "ParticleSystem breakableWall\&.par3"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
