.TH "CameraSightPerceptionSensor2D" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraSightPerceptionSensor2D
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshRenderersList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< SpriteRenderer > \fBrenderers\fP"
.br
.ti -1c
.RI "List< Transform > \fBvisibleRenderers\fP"
.br
.ti -1c
.RI "List< Camera > \fBcameras\fP"
.br
.ti -1c
.RI "GameObject \fBownerRootObj\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CameraSightPerceptionSensor2D\&.RefreshRenderersList ()"

.SH "Member Data Documentation"
.PP 
.SS "List<Camera> CameraSightPerceptionSensor2D\&.cameras"

.SS "GameObject CameraSightPerceptionSensor2D\&.ownerRootObj"

.SS "List<SpriteRenderer> CameraSightPerceptionSensor2D\&.renderers"

.SS "List<Transform> CameraSightPerceptionSensor2D\&.visibleRenderers"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
