.TH "CameraControl" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraControl
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetStartPositionAndSize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBm_DampTime\fP = 0\&.2f"
.br
.ti -1c
.RI "float \fBm_ScreenEdgeBuffer\fP = 4f"
.br
.ti -1c
.RI "float \fBm_MinSize\fP = 6\&.5f"
.br
.ti -1c
.RI "Transform[] \fBm_Targets\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CameraControl\&.SetStartPositionAndSize ()"

.SH "Member Data Documentation"
.PP 
.SS "float CameraControl\&.m_DampTime = 0\&.2f"

.SS "float CameraControl\&.m_MinSize = 6\&.5f"

.SS "float CameraControl\&.m_ScreenEdgeBuffer = 4f"

.SS "Transform [] CameraControl\&.m_Targets"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
