.TH "ChainCommandData" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainCommandData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommandSlotHolder\fP \fBchainCommandSlot\fP"
.br
.ti -1c
.RI "string[] \fBSequence\fP"
.br
.ti -1c
.RI "string[] \fBSequence_Query\fP"
.br
.ti -1c
.RI "string[] \fBholdDownSequence\fP"
.br
.ti -1c
.RI "string[] \fBignoreCategory\fP"
.br
.ti -1c
.RI "string[] \fBnegativeEdgeSequence\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCommandSlotHolder\fP ChainCommandData\&.chainCommandSlot"

.SS "string [] ChainCommandData\&.holdDownSequence"

.SS "string [] ChainCommandData\&.ignoreCategory"

.SS "string [] ChainCommandData\&.negativeEdgeSequence"

.SS "string [] ChainCommandData\&.Sequence"

.SS "string [] ChainCommandData\&.Sequence_Query"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
