.TH "ChainCommandInvokerOldTypeA" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainCommandInvokerOldTypeA
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckSequenceOld\fP (string entryQueueName, \fBChainCommandDataOld\fP c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBChainCommandDataOld\fP > \fBchainCommandDatas\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBCommandQueueHelper\fP \fBcommandQueueHelper\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool ChainCommandInvokerOldTypeA\&.CheckSequenceOld (string entryQueueName, \fBChainCommandDataOld\fP c)"

.SH "Member Data Documentation"
.PP 
.SS "List<\fBChainCommandDataOld\fP> ChainCommandInvokerOldTypeA\&.chainCommandDatas"

.SH "Property Documentation"
.PP 
.SS "virtual \fBCommandQueueHelper\fP ChainCommandInvokerOldTypeA\&.commandQueueHelper\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
