.TH "ChainCommandDataOld" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainCommandDataOld
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommandBase\fP \fBcommand\fP"
.br
.ti -1c
.RI "string[] \fBSequence\fP"
.br
.ti -1c
.RI "GameObject \fBinstigatorObj\fP"
.br
.ti -1c
.RI "string[] \fBSequence_Query\fP"
.br
.ti -1c
.RI "int[] \fBSequence_Axis\fP"
.br
.ti -1c
.RI "string[] \fBholdDownSequence\fP"
.br
.ti -1c
.RI "string \fBignoreCategory\fP"
.br
.ti -1c
.RI "string[] \fBnegativeEdgeSequence\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCommandBase\fP ChainCommandDataOld\&.command"

.SS "string [] ChainCommandDataOld\&.holdDownSequence"

.SS "string ChainCommandDataOld\&.ignoreCategory"

.SS "GameObject ChainCommandDataOld\&.instigatorObj"

.SS "string [] ChainCommandDataOld\&.negativeEdgeSequence"

.SS "string [] ChainCommandDataOld\&.Sequence"

.SS "int [] ChainCommandDataOld\&.Sequence_Axis"

.SS "string [] ChainCommandDataOld\&.Sequence_Query"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
