.TH "CharacterMove" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterMove
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddCommand\fP (\fBMove\fP command)"
.br
.ti -1c
.RI "void \fBUndoCommand\fP ()"
.br
.ti -1c
.RI "void \fBRedoCommand\fP ()"
.br
.ti -1c
.RI "void \fBUpdateLine\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CharacterMove\&.AddCommand (\fBMove\fP command)"

.SS "void CharacterMove\&.RedoCommand ()"

.SS "void CharacterMove\&.UndoCommand ()"

.SS "void CharacterMove\&.UpdateLine ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
