.TH "CollisionByTagEvent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollisionByTagEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnHitbox\fP (GameObject other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< string > \fBallowedTags\fP"
.br
.ti -1c
.RI "bool \fBfilterByAllowedTags\fP = true"
.br
.ti -1c
.RI "bool \fBisCallOnCollisionEnter2D\fP"
.br
.ti -1c
.RI "bool \fBisCallOnTriggerEnter2D\fP"
.br
.ti -1c
.RI "List< string > \fBdisallowedTags\fP"
.br
.ti -1c
.RI "List< string > \fBignorePhysicsForTargetTags\fP"
.br
.ti -1c
.RI "List< Collider2D > \fBignoreTargetCols\fP = new List<Collider2D>()"
.br
.ti -1c
.RI "UnityEvent \fBOnHitBox_Event\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CollisionByTagEvent\&.OnHitbox (GameObject other)"

.SH "Member Data Documentation"
.PP 
.SS "List<string> CollisionByTagEvent\&.allowedTags"

.SS "List<string> CollisionByTagEvent\&.disallowedTags"

.SS "bool CollisionByTagEvent\&.filterByAllowedTags = true"

.SS "List<string> CollisionByTagEvent\&.ignorePhysicsForTargetTags"

.SS "List<Collider2D> CollisionByTagEvent\&.ignoreTargetCols = new List<Collider2D>()"

.SS "bool CollisionByTagEvent\&.isCallOnCollisionEnter2D"

.SS "bool CollisionByTagEvent\&.isCallOnTriggerEnter2D"

.SS "UnityEvent CollisionByTagEvent\&.OnHitBox_Event"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
