.TH "CommandBase.Info" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandBase.Info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_aName\fP"
.br
.ti -1c
.RI "string \fBquery\fP"
.br
.ti -1c
.RI "Sprite \fBaSprite\fP"
.br
.ti -1c
.RI "bool \fB_DebugLog\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string CommandBase\&.Info\&._aName"

.SS "bool CommandBase\&.Info\&._DebugLog"

.SS "Sprite CommandBase\&.Info\&.aSprite"

.SS "string CommandBase\&.Info\&.query"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
