.TH "CommandCoolDownComp" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandCoolDownComp
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBCommandBase\fP selectedAbility, GameObject weaponHolder)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBdarkMask\fP"
.br
.ti -1c
.RI "Text \fBcoolDownTextDisplay\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CommandCoolDownComp\&.Initialize (\fBCommandBase\fP selectedAbility, GameObject weaponHolder)"

.SH "Member Data Documentation"
.PP 
.SS "Text CommandCoolDownComp\&.coolDownTextDisplay"

.SS "Image CommandCoolDownComp\&.darkMask"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
