.TH "CommandBase.CooldownInfo" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandBase.CooldownInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBcooldownTime\fP"
.br
.ti -1c
.RI "float \fBcurCoolDownTimeElapsed\fP"
.br
.ti -1c
.RI "\fBCastState\fP \fBcastState\fP"
.br
.ti -1c
.RI "bool \fBisCastingNow\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCastState\fP CommandBase\&.CooldownInfo\&.castState"

.SS "float CommandBase\&.CooldownInfo\&.cooldownTime"

.SS "float CommandBase\&.CooldownInfo\&.curCoolDownTimeElapsed"

.SS "bool CommandBase\&.CooldownInfo\&.isCastingNow"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
