.TH "CommandBase.InstanceInfoRuntime" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandBase.InstanceInfoRuntime
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fB_isExecuted\fP"
.br
.ti -1c
.RI "bool \fB_isEnabled\fP"
.br
.ti -1c
.RI "int \fB_id\fP"
.br
.ti -1c
.RI "float \fBTimeStamp\fP"
.br
.ti -1c
.RI "float \fBElapsedTime\fP"
.br
.ti -1c
.RI "GameObject \fBcommandOwnerRootObj\fP"
.br
.ti -1c
.RI "GameObject \fBcommandTargetObj\fP"
.br
.ti -1c
.RI "\fBCommandAccessorRefsBase\fP \fBcommandAccessorRefsComp\fP"
.br
.ti -1c
.RI "bool \fBisSoInstance\fP"
.br
.ti -1c
.RI "List< string > \fBUsedToExecChainCommands\fP"
.br
.ti -1c
.RI "string \fBprevPrimaryCommandName\fP"
.br
.ti -1c
.RI "\fBCommandBase\fP \fBprevPrimaryCommand\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int CommandBase\&.InstanceInfoRuntime\&._id"

.SS "bool CommandBase\&.InstanceInfoRuntime\&._isEnabled"

.SS "bool CommandBase\&.InstanceInfoRuntime\&._isExecuted"

.SS "\fBCommandAccessorRefsBase\fP CommandBase\&.InstanceInfoRuntime\&.commandAccessorRefsComp"

.SS "GameObject CommandBase\&.InstanceInfoRuntime\&.commandOwnerRootObj"

.SS "GameObject CommandBase\&.InstanceInfoRuntime\&.commandTargetObj"

.SS "float CommandBase\&.InstanceInfoRuntime\&.ElapsedTime"

.SS "bool CommandBase\&.InstanceInfoRuntime\&.isSoInstance"

.SS "\fBCommandBase\fP CommandBase\&.InstanceInfoRuntime\&.prevPrimaryCommand"

.SS "string CommandBase\&.InstanceInfoRuntime\&.prevPrimaryCommandName"

.SS "float CommandBase\&.InstanceInfoRuntime\&.TimeStamp"

.SS "List<string> CommandBase\&.InstanceInfoRuntime\&.UsedToExecChainCommands"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
