.TH "CommandBase" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject, and \fBICommand\fP\&.
.PP
Inherited by \fBBinCommandWithCooldown\fP, and \fBInputCommand\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCooldownInfo\fP"
.br
.ti -1c
.RI "class \fBExecutionInfo\fP"
.br
.ti -1c
.RI "struct \fBInfo\fP"
.br
.ti -1c
.RI "struct \fBInstanceInfoRuntime\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCastState\fP { \fBready\fP, \fBactive\fP, \fBcooldown\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBActivate\fP (GameObject ownerRootParentObj=null)"
.br
.ti -1c
.RI "virtual void \fBBeginCooldown\fP (GameObject ownerRootParentObj=null)"
.br
.ti -1c
.RI "virtual void \fBStayCooldown\fP (GameObject ownerRootParentObj=null)"
.br
.ti -1c
.RI "virtual void \fBEndCooldown\fP (GameObject ownerRootParentObj=null)"
.br
.ti -1c
.RI "void \fBHandleCooldown\fP (GameObject ownerRootParentObj)"
.br
.ti -1c
.RI "virtual void \fBTryExecCommand\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnExternalUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBCalculateElapsedTime\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecPress\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecDown\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecDownCharging\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecRelease\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecd\fP ()"
.br
.ti -1c
.RI "virtual void \fBInitGameObj\fP (GameObject ownerRootParentObj)"
.br
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual \fBCommandBase\fP \fBCreateNewInstanceOfSelf\fP (GameObject newInstigatorObjRef=null)"
.br
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "virtual void \fBUndo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "\fBInstanceInfoRuntime\fP \fBinstanceInfo\fP"
.br
.ti -1c
.RI "\fBCooldownInfo\fP \fBcooldownInfo\fP"
.br
.ti -1c
.RI "\fBExecutionInfo\fP \fBexecInfo\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBaName\fP\fC [getset]\fP"
.br
.ti -1c
.RI "virtual float \fBTimeStamp\fP\fC [getset]\fP"
.br
.ti -1c
.RI "virtual float \fBElapsedTime\fP\fC [getset]\fP"
.br
.ti -1c
.RI "virtual int \fBid\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCommandBase\&.CastState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIready \fP\fP
.TP
\fB\fIactive \fP\fP
.TP
\fB\fIcooldown \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "virtual void CommandBase\&.Activate (GameObject ownerRootParentObj = \fCnull\fP)\fC [virtual]\fP"

.SS "virtual void CommandBase\&.Awake ()\fC [virtual]\fP"

.SS "virtual void CommandBase\&.BeginCooldown (GameObject ownerRootParentObj = \fCnull\fP)\fC [virtual]\fP"

.SS "virtual void CommandBase\&.CalculateElapsedTime ()\fC [virtual]\fP"

.SS "virtual \fBCommandBase\fP CommandBase\&.CreateNewInstanceOfSelf (GameObject newInstigatorObjRef = \fCnull\fP)\fC [virtual]\fP"

.SS "virtual void CommandBase\&.EndCooldown (GameObject ownerRootParentObj = \fCnull\fP)\fC [virtual]\fP"

.SS "virtual void CommandBase\&.Execd ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "virtual void CommandBase\&.ExecDown ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "virtual void CommandBase\&.ExecDownCharging ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "virtual void CommandBase\&.ExecPress ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP, \fBEnableDisableGameObjectCommand\fP, and \fBSetMaterialColorCommand\fP\&.
.SS "virtual void CommandBase\&.ExecRelease ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "void CommandBase\&.HandleCooldown (GameObject ownerRootParentObj)"

.SS "virtual void CommandBase\&.Init ()\fC [virtual]\fP"

.SS "virtual void CommandBase\&.InitGameObj (GameObject ownerRootParentObj)\fC [virtual]\fP"

.SS "virtual void CommandBase\&.OnDestroy ()\fC [virtual]\fP"

.SS "virtual void CommandBase\&.OnDisable ()\fC [virtual]\fP"

.SS "virtual void CommandBase\&.OnEnable ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "virtual void CommandBase\&.OnExternalUpdate ()\fC [virtual]\fP"

.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "virtual void CommandBase\&.StayCooldown (GameObject ownerRootParentObj = \fCnull\fP)\fC [virtual]\fP"

.SS "virtual void CommandBase\&.TryExecCommand ()\fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Reimplemented in \fBInputCommand\fP\&.
.SS "virtual void CommandBase\&.Undo ()\fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCooldownInfo\fP CommandBase\&.cooldownInfo"

.SS "\fBExecutionInfo\fP CommandBase\&.execInfo"

.SS "\fBInfo\fP CommandBase\&.info"

.SS "\fBInstanceInfoRuntime\fP CommandBase\&.instanceInfo"

.SH "Property Documentation"
.PP 
.SS "virtual string CommandBase\&.aName\fC [get]\fP, \fC [set]\fP"

.SS "virtual float CommandBase\&.ElapsedTime\fC [get]\fP, \fC [set]\fP"

.SS "virtual int CommandBase\&.id\fC [get]\fP, \fC [set]\fP"

.SS "virtual float CommandBase\&.TimeStamp\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
