.TH "CommandSlotsHolderManager" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandSlotsHolderManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandSlotHolder\fP \fBFindCommandSlotByName\fP (string commandName)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBCommandSlotHolder\fP > \fBcommandSlotsInChild\fP"
.br
.ti -1c
.RI "List< string > \fBcommandSlotsNames\fP = new List<string>()"
.br
.ti -1c
.RI "GameObject \fBcommandOwnerRootObj\fP"
.br
.ti -1c
.RI "int \fBPlayerNumber\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBCommandQueueHelper\fP \fBcommandHelper\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBCommandSlotHolder\fP CommandSlotsHolderManager\&.FindCommandSlotByName (string commandName)"

.SH "Member Data Documentation"
.PP 
.SS "GameObject CommandSlotsHolderManager\&.commandOwnerRootObj"

.SS "List<\fBCommandSlotHolder\fP> CommandSlotsHolderManager\&.commandSlotsInChild"

.SS "List<string> CommandSlotsHolderManager\&.commandSlotsNames = new List<string>()"

.SS "int CommandSlotsHolderManager\&.PlayerNumber"

.SH "Property Documentation"
.PP 
.SS "virtual \fBCommandQueueHelper\fP CommandSlotsHolderManager\&.commandHelper\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
