.TH "ConstraintCommon" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstraintCommon
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBResetCSrcToSingleTargetParent\fP (ParentConstraint parentConstraint, Transform targetTrans)"
.br
.ti -1c
.RI "static void \fBSetFirstCSourceSnapTargetParent\fP (ParentConstraint parentConstraint, Transform targetTrans)"
.br
.ti -1c
.RI "static ConstraintSource \fBNewCSourceParent\fP (Transform srcTransform, float weight)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static ConstraintSource ConstraintCommon\&.NewCSourceParent (Transform srcTransform, float weight)\fC [static]\fP"

.SS "static void ConstraintCommon\&.ResetCSrcToSingleTargetParent (ParentConstraint parentConstraint, Transform targetTrans)\fC [static]\fP"

.SS "static void ConstraintCommon\&.SetFirstCSourceSnapTargetParent (ParentConstraint parentConstraint, Transform targetTrans)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
