.TH "CustomComposite" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomComposite
.SH SYNOPSIS
.br
.PP
.PP
Inherits InputBindingComposite< Vector2 >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override Vector2 \fBReadValue\fP (ref InputBindingCompositeContext context)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmultiplier\fP"
.br
.ti -1c
.RI "int \fBstick\fP"
.br
.ti -1c
.RI "float \fBscaleFactor\fP = 1"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override Vector2 CustomComposite\&.ReadValue (ref InputBindingCompositeContext context)"

.SH "Member Data Documentation"
.PP 
.SS "int CustomComposite\&.multiplier"

.SS "float CustomComposite\&.scaleFactor = 1"

.SS "int CustomComposite\&.stick"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
