.TH "CustomDeviceUsages" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomDeviceUsages
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBgamepadIndex\fP"
.br
.ti -1c
.RI "string \fBusageTag\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CustomDeviceUsages\&.OnDisable ()\fC [protected]\fP"

.SS "void CustomDeviceUsages\&.OnEnable ()\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int CustomDeviceUsages\&.gamepadIndex"

.SS "string CustomDeviceUsages\&.usageTag"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
