.TH "DayCounter" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DayCounter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCountDays\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdays\fP = 0"
.br
.ti -1c
.RI "Text \fBdayCounter\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBDayCounter\fP \fBinstance\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DayCounter\&.CountDays ()"

.SH "Member Data Documentation"
.PP 
.SS "Text DayCounter\&.dayCounter"

.SS "int DayCounter\&.days = 0"

.SS "\fBDayCounter\fP DayCounter\&.instance\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
