.TH "DefaultState" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultState
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFSMBaseState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultState\fP (\fBFSMSystemBase\fP system)"
.br
.ti -1c
.RI "override bool \fBOnEnterState\fP ()"
.br
.ti -1c
.RI "override bool \fBOnExitState\fP ()"
.br
.ti -1c
.RI "override void \fBOnUpdate\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DefaultState\&.DefaultState (\fBFSMSystemBase\fP system)"

.SH "Member Function Documentation"
.PP 
.SS "override bool DefaultState\&.OnEnterState ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFSMBaseState\fP\&.
.SS "override bool DefaultState\&.OnExitState ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFSMBaseState\fP\&.
.SS "override void DefaultState\&.OnUpdate ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFSMBaseState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
