.TH "DialogueSystem" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogueSystem
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDIALOGUE_ELEMENTS\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartTalking\fP (string speech, string speaker='')"
.br
.ti -1c
.RI "void \fBStopTalking\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDIALOGUE_ELEMENTS\fP \fBdialogueElements\fP"
.br
.ti -1c
.RI "bool \fBisWaitingForUserInput\fP = false"
.br
.ti -1c
.RI "Text \fBpressContinue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBDialogueSystem\fP \fBinstance\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisTalking\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DialogueSystem\&.StartTalking (string speech, string speaker = \fC''\fP)"

.SS "void DialogueSystem\&.StopTalking ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBDIALOGUE_ELEMENTS\fP DialogueSystem\&.dialogueElements"

.SS "\fBDialogueSystem\fP DialogueSystem\&.instance\fC [static]\fP"

.SS "bool DialogueSystem\&.isWaitingForUserInput = false"

.SS "Text DialogueSystem\&.pressContinue"

.SH "Property Documentation"
.PP 
.SS "bool DialogueSystem\&.isTalking\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
