.TH "DialogueSystem.DIALOGUE_ELEMENTS" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogueSystem.DIALOGUE_ELEMENTS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtextBox\fP"
.br
.ti -1c
.RI "Text \fBscientistName\fP"
.br
.ti -1c
.RI "Text \fBdialogues\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Text DialogueSystem\&.DIALOGUE_ELEMENTS\&.dialogues"

.SS "Text DialogueSystem\&.DIALOGUE_ELEMENTS\&.scientistName"

.SS "GameObject DialogueSystem\&.DIALOGUE_ELEMENTS\&.textBox"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
