.TH "DontDestroyOnLoad" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DontDestroyOnLoad
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisDestroyObjWithIdenticalName\fP = true"
.br
.ti -1c
.RI "bool \fBisDontDestroyOnLoadActivatedYet\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool DontDestroyOnLoad\&.isDestroyObjWithIdenticalName = true"

.SS "bool DontDestroyOnLoad\&.isDontDestroyOnLoadActivatedYet"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
