.TH "Examples.Command.LightDecreaseIntensity" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Examples.Command.LightDecreaseIntensity
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBICommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightDecreaseIntensity\fP (Light light)"
.br
.ti -1c
.RI "void \fBTryExecCommand\fP ()"
.br
.ti -1c
.RI "void \fBUndo\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Examples\&.Command\&.LightDecreaseIntensity\&.LightDecreaseIntensity (Light light)"

.SH "Member Function Documentation"
.PP 
.SS "void Examples\&.Command\&.LightDecreaseIntensity\&.TryExecCommand ()"

.PP
Implements \fBICommand\fP\&.
.SS "void Examples\&.Command\&.LightDecreaseIntensity\&.Undo ()"

.PP
Implements \fBICommand\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
