.TH "Examples.Command" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Examples.Command \- Utility script that creates a random color for us and returns it\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColorCreator\fP"
.br
.ti -1c
.RI "class \fBLightActiveToggle\fP"
.br
.ti -1c
.RI "class \fBLightColorChange\fP"
.br
.ti -1c
.RI "class \fBLightController\fP"
.br
.ti -1c
.RI "class \fBLightDecreaseIntensity\fP"
.br
.ti -1c
.RI "class \fBLightIncreaseIntensity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility script that creates a random color for us and returns it\&. 

This class is used to test our \fBCommand\fP Stack functionality\&.
.PP
Example of a \fBCommand\fP for our Light\&.
.PP
Example of a \fBCommand\fP for the light\&.
.PP
Example of a command for the light\&.
.PP
An example \fBCommand\fP for our light that turns on and off the light component\&.
.PP
We assign a new color to the light, and change it back when we're done\&. 
.PP
We decrease its intensity, and undo our decrease on undo 
.PP
We increase the intensity, and on Undo, we revert our increase\&. 
.PP
You can use key inputs to execute commands through the \fBCommand\fP Stack \fBCommand\fP Stack tracks history, so Undo button will undo our last command 
.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
