.TH "Extensions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Extensions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShuffle< T >\fP (this IList< T > list)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void Extensions\&.Shuffle< T > (this IList< T > list)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
