.TH "FileReadWrite" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileReadWrite
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBWriteToBinaryFile< T >\fP (string filePath, T objectToWrite)"
.br
.ti -1c
.RI "static T \fBReadFromBinaryFile< T >\fP (string filePath)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static T FileReadWrite\&.ReadFromBinaryFile< T > (string filePath)\fC [static]\fP"

.SS "static void FileReadWrite\&.WriteToBinaryFile< T > (string filePath, T objectToWrite)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
