.TH "Flee" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flee
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFSMBaseState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlee\fP (\fBFSMSystemBase\fP system)"
.br
.ti -1c
.RI "override bool \fBOnEnterState\fP ()"
.br
.ti -1c
.RI "override bool \fBOnExitState\fP ()"
.br
.ti -1c
.RI "override void \fBOnStayState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhasSetDestination\fP"
.br
.ti -1c
.RI "Transform \fBtarget\fP"
.br
.ti -1c
.RI "float \fBnewSpeed\fP = 30f"
.br
.ti -1c
.RI "float \fBnewAgularSpeed\fP = 500f"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Flee\&.Flee (\fBFSMSystemBase\fP system)"

.SH "Member Function Documentation"
.PP 
.SS "override bool Flee\&.OnEnterState ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFSMBaseState\fP\&.
.SS "override bool Flee\&.OnExitState ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFSMBaseState\fP\&.
.SS "override void Flee\&.OnStayState ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFSMBaseState\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Flee\&.hasSetDestination"

.SS "float Flee\&.newAgularSpeed = 500f"

.SS "float Flee\&.newSpeed = 30f"

.SS "Transform Flee\&.target"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
