.TH "GameEventListener" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameEventListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBCommandEventListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnEventRaised\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameEvent\fP \fBEvent\fP"
.br
.ti -1c
.RI "UnityEvent \fBResponse\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void GameEventListener\&.OnEventRaised ()\fC [virtual]\fP"

.PP
Reimplemented in \fBCommandEventListener\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameEvent\fP GameEventListener\&.Event"

.SS "UnityEvent GameEventListener\&.Response"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
