.TH "GameEvent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBCommandEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBRaise\fP ()"
.br
.ti -1c
.RI "virtual void \fBRegisterListener\fP (\fBGameEventListener\fP listener)"
.br
.ti -1c
.RI "virtual void \fBUnregisterListener\fP (\fBGameEventListener\fP listener)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void GameEvent\&.Raise ()\fC [virtual]\fP"

.SS "virtual void GameEvent\&.RegisterListener (\fBGameEventListener\fP listener)\fC [virtual]\fP"

.SS "virtual void GameEvent\&.UnregisterListener (\fBGameEventListener\fP listener)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
