.TH "GameObjSpawnHelper" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameObjSpawnHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSpawnAllObjs\fP ()"
.br
.ti -1c
.RI "void \fBSpawnRandomObj\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< GameObject > \fBobjsToSpawn\fP"
.br
.ti -1c
.RI "bool \fBisUseThisObjPos\fP = true"
.br
.ti -1c
.RI "Vector3 \fBspawnPos\fP"
.br
.ti -1c
.RI "bool \fBisUseThisObjRotEuler\fP = true"
.br
.ti -1c
.RI "Vector3 \fBspawnRotEuler\fP"
.br
.ti -1c
.RI "List< GameObject > \fBspawnedObjs\fP"
.br
.ti -1c
.RI "int \fBspawnedObjsMaxCount\fP = 3"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void GameObjSpawnHelper\&.SpawnAllObjs ()"

.SS "void GameObjSpawnHelper\&.SpawnRandomObj ()"

.SS "void GameObjSpawnHelper\&.Update ()"

.SH "Member Data Documentation"
.PP 
.SS "bool GameObjSpawnHelper\&.isUseThisObjPos = true"

.SS "bool GameObjSpawnHelper\&.isUseThisObjRotEuler = true"

.SS "List<GameObject> GameObjSpawnHelper\&.objsToSpawn"

.SS "List<GameObject> GameObjSpawnHelper\&.spawnedObjs"

.SS "int GameObjSpawnHelper\&.spawnedObjsMaxCount = 3"

.SS "Vector3 GameObjSpawnHelper\&.spawnPos"

.SS "Vector3 GameObjSpawnHelper\&.spawnRotEuler"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
