.TH "C:/_SSDSPEEDUP/2021/clone/gps1_manadesigner/GPS1-Manadesigner/Assets/Scripts/Editor/_Utils/SerializableDataStructures/GenericDictionaryPropertyDrawer.cs" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/clone/gps1_manadesigner/GPS1-Manadesigner/Assets/Scripts/Editor/_Utils/SerializableDataStructures/GenericDictionaryPropertyDrawer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenericDictionaryPropertyDrawer\fP"
.br
.RI "Draws the generic dictionary a bit nicer than Unity would natively (not as many expand-arrows and better spacing between KeyValue pairs)\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
