.TH "GenericDictionaryPropertyDrawer" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericDictionaryPropertyDrawer \- Draws the generic dictionary a bit nicer than Unity would natively (not as many expand-arrows and better spacing between KeyValue pairs)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGUI\fP (Rect pos, SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Draws the generic dictionary a bit nicer than Unity would natively (not as many expand-arrows and better spacing between KeyValue pairs)\&. 

Also renders a warning-box if there are duplicate keys in the dictionary\&. 
.SH "Member Function Documentation"
.PP 
.SS "override float GenericDictionaryPropertyDrawer\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.SS "override void GenericDictionaryPropertyDrawer\&.OnGUI (Rect pos, SerializedProperty property, GUIContent label)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
