.TH "HomingBullet" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomingBullet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlayerBullet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHeatSeekEnemy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnemyHealth\fP[] \fBenemies\fP"
.br
.ti -1c
.RI "\fBEnemyHealth\fP \fBtargetedEnemy\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void HomingBullet\&.HeatSeekEnemy ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBEnemyHealth\fP [] HomingBullet\&.enemies"

.SS "\fBEnemyHealth\fP HomingBullet\&.targetedEnemy"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
