.TH "ICommandOWS" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICommandOWS
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMove\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecute\fP ()"
.br
.ti -1c
.RI "void \fBUndo\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ICommandOWS\&.Execute ()"

.PP
Implemented in \fBMove\fP\&.
.SS "void ICommandOWS\&.Undo ()"

.PP
Implemented in \fBMove\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
