.TH "ICommand" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICommand
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCommandBase\fP, \fBExamples\&.Command\&.LightActiveToggle\fP, \fBExamples\&.Command\&.LightColorChange\fP, \fBExamples\&.Command\&.LightDecreaseIntensity\fP, and \fBExamples\&.Command\&.LightIncreaseIntensity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTryExecCommand\fP ()"
.br
.ti -1c
.RI "void \fBUndo\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ICommand\&.TryExecCommand ()"

.PP
Implemented in \fBExamples\&.Command\&.LightActiveToggle\fP, \fBExamples\&.Command\&.LightColorChange\fP, \fBExamples\&.Command\&.LightDecreaseIntensity\fP, \fBExamples\&.Command\&.LightIncreaseIntensity\fP, \fBCommandBase\fP, and \fBInputCommand\fP\&.
.SS "void ICommand\&.Undo ()"

.PP
Implemented in \fBExamples\&.Command\&.LightActiveToggle\fP, \fBExamples\&.Command\&.LightColorChange\fP, \fBExamples\&.Command\&.LightDecreaseIntensity\fP, \fBExamples\&.Command\&.LightIncreaseIntensity\fP, and \fBCommandBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
