.TH "InputCommand.ExecExtraInfo" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputCommand.ExecExtraInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBm_PlayerNumber\fP"
.br
.ti -1c
.RI "bool \fBm_Execd\fP"
.br
.ti -1c
.RI "bool \fBm_ExecButtonPressedThisFrame\fP"
.br
.ti -1c
.RI "bool \fBm_ExecButtonReleasedThisFrame\fP"
.br
.ti -1c
.RI "bool \fBm_ExecButtonDown\fP"
.br
.ti -1c
.RI "float \fBm_Axis\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float InputCommand\&.ExecExtraInfo\&.m_Axis"

.SS "bool InputCommand\&.ExecExtraInfo\&.m_ExecButtonDown"

.SS "bool InputCommand\&.ExecExtraInfo\&.m_ExecButtonPressedThisFrame"

.SS "bool InputCommand\&.ExecExtraInfo\&.m_ExecButtonReleasedThisFrame"

.SS "bool InputCommand\&.ExecExtraInfo\&.m_Execd"

.SS "int InputCommand\&.ExecExtraInfo\&.m_PlayerNumber"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
