.TH "Introduction" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Introduction
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExplainAgain\fP ()"
.br
.ti -1c
.RI "void \fBEndBrief\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBintroPanel\fP"
.br
.ti -1c
.RI "GameObject \fBchoicePanel\fP"
.br
.ti -1c
.RI "GameObject \fBscientistTalk\fP"
.br
.ti -1c
.RI "GameObject \fBscientistIdle\fP"
.br
.ti -1c
.RI "GameObject \fBglasses\fP"
.br
.ti -1c
.RI "int \fBindex\fP = 0"
.br
.ti -1c
.RI "bool \fBaskAgain\fP = false"
.br
.ti -1c
.RI "bool \fBhasUnderstand\fP = false"
.br
.ti -1c
.RI "string[] \fBintro\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBIntroduction\fP \fBinstance\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Introduction\&.EndBrief ()"

.SS "void Introduction\&.ExplainAgain ()"

.SH "Member Data Documentation"
.PP 
.SS "bool Introduction\&.askAgain = false"

.SS "GameObject Introduction\&.choicePanel"

.SS "GameObject Introduction\&.glasses"

.SS "bool Introduction\&.hasUnderstand = false"

.SS "int Introduction\&.index = 0"

.SS "\fBIntroduction\fP Introduction\&.instance\fC [static]\fP"

.SS "string [] Introduction\&.intro"

.SS "GameObject Introduction\&.introPanel"

.SS "GameObject Introduction\&.scientistIdle"

.SS "GameObject Introduction\&.scientistTalk"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
