.TH "ItemSlotSaveData" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemSlotSaveData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemSlotSaveData\fP (string id, int amount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBItemID\fP"
.br
.ti -1c
.RI "int \fBAmount\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ItemSlotSaveData\&.ItemSlotSaveData (string id, int amount)"

.SH "Member Data Documentation"
.PP 
.SS "int ItemSlotSaveData\&.Amount"

.SS "string ItemSlotSaveData\&.ItemID"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
