.TH "ItemSaveIO" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemSaveIO
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSaveItems\fP (\fBItemContainerSaveData\fP items, string fileName)"
.br
.ti -1c
.RI "static \fBItemContainerSaveData\fP \fBLoadItems\fP (string fileName)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBItemContainerSaveData\fP ItemSaveIO\&.LoadItems (string fileName)\fC [static]\fP"

.SS "static void ItemSaveIO\&.SaveItems (\fBItemContainerSaveData\fP items, string fileName)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
