.TH "ItemDatabase" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemDatabase
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBitem\fP \fBGetItemReference\fP (string itemID)"
.br
.ti -1c
.RI "\fBitem\fP \fBGetItemCopy\fP (string itemID)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBitem\fP ItemDatabase\&.GetItemCopy (string itemID)"

.SS "\fBitem\fP ItemDatabase\&.GetItemReference (string itemID)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
