.TH "itemSlotsNew" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
itemSlotsNew
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBitemNew\fP \fBItem\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBAmount\fP\fC [getset]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "System\&.Action< \fBitemNew\fP > \fBOnRightClickEvent\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void itemSlotsNew\&.OnPointerClick (PointerEventData eventData)"

.SH "Property Documentation"
.PP 
.SS "int itemSlotsNew\&.Amount\fC [get]\fP, \fC [set]\fP"

.SS "\fBitemNew\fP itemSlotsNew\&.Item\fC [get]\fP, \fC [set]\fP"

.SH "Event Documentation"
.PP 
.SS "System\&.Action<\fBitemNew\fP> itemSlotsNew\&.OnRightClickEvent"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
