.TH "itemNew" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
itemNew
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBitemNew\fP \fBgetCopy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBresourceName\fP"
.br
.ti -1c
.RI "Sprite \fBSprite\fP"
.br
.ti -1c
.RI "int \fBMaxStack\fP = 10"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBitemNew\fP itemNew\&.getCopy ()\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int itemNew\&.MaxStack = 10"

.SS "string itemNew\&.resourceName"

.SS "Sprite itemNew\&.Sprite"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
