.TH "item" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
item
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBitem\fP \fBgetCopy\fP ()"
.br
.ti -1c
.RI "virtual void \fBDestroy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBresourceName\fP"
.br
.ti -1c
.RI "Sprite \fBIcon\fP"
.br
.ti -1c
.RI "string \fBitemDescription\fP"
.br
.ti -1c
.RI "int \fBmaxStack\fP = 2"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBID\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void item\&.Destroy ()\fC [virtual]\fP"

.SS "virtual \fBitem\fP item\&.getCopy ()\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Sprite item\&.Icon"

.SS "string item\&.itemDescription"

.SS "int item\&.maxStack = 2"

.SS "string item\&.resourceName"

.SH "Property Documentation"
.PP 
.SS "string item\&.ID\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
