.TH "MapLocation" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapLocation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapLocation\fP (int _x, int _y)"
.br
.ti -1c
.RI "Vector2 \fBToVector\fP ()"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMapLocation\fP \fBoperator+\fP (\fBMapLocation\fP a, \fBMapLocation\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MapLocation\&.MapLocation (int _x, int _y)"

.SH "Member Function Documentation"
.PP 
.SS "override bool MapLocation\&.Equals (object obj)"

.SS "override int MapLocation\&.GetHashCode ()"

.SS "static \fBMapLocation\fP MapLocation\&.operator+ (\fBMapLocation\fP a, \fBMapLocation\fP b)\fC [static]\fP"

.SS "Vector2 MapLocation\&.ToVector ()"

.SH "Member Data Documentation"
.PP 
.SS "int MapLocation\&.x"

.SS "int MapLocation\&.y"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
