.TH "MathCommon" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MathCommon
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBCalculateSliderValuePercentage\fP (Slider sliderUI, float currValue, float maxValue, float lerpTime)"
.br
.ti -1c
.RI "static float \fBCalculateLerpValuePercentage\fP (float currValue, float maxValue, float lerpTime)"
.br
.ti -1c
.RI "static Vector3 \fBlerpLinearVector3\fP (Vector3 start, Vector3 end, float timeStartedLerping, float lerpTime=1)"
.br
.ti -1c
.RI "static float \fBlerpLinearFloat\fP (float startVal, float endVal, float timeStartedLerping, float lerpTime=1)"
.br
.ti -1c
.RI "static Color \fBColorParseHex\fP (string hexValue)"
.br
.ti -1c
.RI "static Color \fBColorInvert\fP (Color color)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static float MathCommon\&.CalculateLerpValuePercentage (float currValue, float maxValue, float lerpTime)\fC [static]\fP"

.SS "static float MathCommon\&.CalculateSliderValuePercentage (Slider sliderUI, float currValue, float maxValue, float lerpTime)\fC [static]\fP"

.SS "static Color MathCommon\&.ColorInvert (Color color)\fC [static]\fP"

.SS "static Color MathCommon\&.ColorParseHex (string hexValue)\fC [static]\fP"

.SS "static float MathCommon\&.lerpLinearFloat (float startVal, float endVal, float timeStartedLerping, float lerpTime = \fC1\fP)\fC [static]\fP"

.SS "static Vector3 MathCommon\&.lerpLinearVector3 (Vector3 start, Vector3 end, float timeStartedLerping, float lerpTime = \fC1\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
