.TH "Move" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Move
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBICommandOWS\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMove\fP (Transform objectToMove, Vector3 direction, float distance=1f)"
.br
.ti -1c
.RI "void \fBExecute\fP ()"
.br
.ti -1c
.RI "void \fBUndo\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetMove\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Move\&.Move (Transform objectToMove, Vector3 direction, float distance = \fC1f\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void Move\&.Execute ()"

.PP
Implements \fBICommandOWS\fP\&.
.SS "Vector3 Move\&.GetMove ()"

.SS "void Move\&.Undo ()"

.PP
Implements \fBICommandOWS\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
