.TH "NavAgentTestAutoSetRandomDestination" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavAgentTestAutoSetRandomDestination
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetNewDestination\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NavMeshAgent \fBagent\fP"
.br
.ti -1c
.RI "float \fBradius\fP = 25"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void NavAgentTestAutoSetRandomDestination\&.SetNewDestination ()"

.SH "Member Data Documentation"
.PP 
.SS "NavMeshAgent NavAgentTestAutoSetRandomDestination\&.agent"

.SS "float NavAgentTestAutoSetRandomDestination\&.radius = 25"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
