.TH "OnAllUnityEventCall" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OnAllUnityEventCall
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlayEventToCall\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBeventToCall\fP"
.br
.ti -1c
.RI "bool \fBisPlayOnEnable\fP = true"
.br
.ti -1c
.RI "bool \fBisPlayOnStart\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnAwake\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnUpdate\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnFixedUpdate\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnLateUpdate\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnGUI\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnDisable\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnDestroy\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnApplicationPause\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTransformChildrenChanged\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTransformParentChanged\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnBeforeTransformParentChanged\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionEnter\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionExit\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionStay\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerEnter\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerExit\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerStay\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionEnter2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionExit2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionStay2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerEnter2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerExit2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerStay2D\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void OnAllUnityEventCall\&.PlayEventToCall ()"

.SH "Member Data Documentation"
.PP 
.SS "UnityEvent OnAllUnityEventCall\&.eventToCall"

.SS "bool OnAllUnityEventCall\&.isPlayOnApplicationPause = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnAwake = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnBeforeTransformParentChanged = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionEnter = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionEnter2D = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionExit = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionExit2D = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionStay = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionStay2D = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnDestroy = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnDisable = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnEnable = true"

.SS "bool OnAllUnityEventCall\&.isPlayOnFixedUpdate = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnGUI = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnLateUpdate = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnStart = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTransformChildrenChanged = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTransformParentChanged = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerEnter = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerEnter2D = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerExit = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerExit2D = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerStay = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerStay2D = false"

.SS "bool OnAllUnityEventCall\&.isPlayOnUpdate = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
