.TH "OnEnableEventCallTimer" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OnEnableEventCallTimer
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBResetTimer\fP ()"
.br
.ti -1c
.RI "void \fBPlayEventToCall\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBtimerInSeconds\fP = 3f"
.br
.ti -1c
.RI "bool \fBisUseIntervalTimer\fP"
.br
.ti -1c
.RI "bool \fBisAllowDisable\fP = false"
.br
.ti -1c
.RI "bool \fBisCountUpTimer\fP = false"
.br
.ti -1c
.RI "bool \fBisTimerHasLimit\fP = true"
.br
.ti -1c
.RI "Text \fBtimerText\fP"
.br
.ti -1c
.RI "bool \fBisLoopTimer\fP"
.br
.ti -1c
.RI "bool \fBisUseRandomRangeTimerInSeconds\fP"
.br
.ti -1c
.RI "float \fBminTimerInSeconds\fP"
.br
.ti -1c
.RI "float \fBmaxTimerInSeconds\fP"
.br
.ti -1c
.RI "float \fBtargetTime\fP"
.br
.ti -1c
.RI "UnityEvent \fBeventToCall\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void OnEnableEventCallTimer\&.PlayEventToCall ()"

.SS "void OnEnableEventCallTimer\&.ResetTimer ()"

.SH "Member Data Documentation"
.PP 
.SS "UnityEvent OnEnableEventCallTimer\&.eventToCall"

.SS "bool OnEnableEventCallTimer\&.isAllowDisable = false"

.SS "bool OnEnableEventCallTimer\&.isCountUpTimer = false"

.SS "bool OnEnableEventCallTimer\&.isLoopTimer"

.SS "bool OnEnableEventCallTimer\&.isTimerHasLimit = true"

.SS "bool OnEnableEventCallTimer\&.isUseIntervalTimer"

.SS "bool OnEnableEventCallTimer\&.isUseRandomRangeTimerInSeconds"

.SS "float OnEnableEventCallTimer\&.maxTimerInSeconds"

.SS "float OnEnableEventCallTimer\&.minTimerInSeconds"

.SS "float OnEnableEventCallTimer\&.targetTime"

.SS "float OnEnableEventCallTimer\&.timerInSeconds = 3f"

.SS "Text OnEnableEventCallTimer\&.timerText"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
