.TH "OutpostChoices" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutpostChoices
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTalkWithScientist\fP ()"
.br
.ti -1c
.RI "void \fBEnablePanels\fP ()"
.br
.ti -1c
.RI "void \fBReturnSea\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBdefaultPanel\fP"
.br
.ti -1c
.RI "GameObject \fBnewsPanel\fP"
.br
.ti -1c
.RI "GameObject \fBscientistIdleAnim\fP"
.br
.ti -1c
.RI "GameObject \fBscientistTalkAnim\fP"
.br
.ti -1c
.RI "GameObject \fBcoverPanel\fP"
.br
.ti -1c
.RI "Text \fBnameText\fP"
.br
.ti -1c
.RI "Text \fBtextBox\fP"
.br
.ti -1c
.RI "bool \fBisActive\fP = false"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBOutpostChoices\fP \fBinstance\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void OutpostChoices\&.EnablePanels ()"

.SS "void OutpostChoices\&.ReturnSea ()"

.SS "void OutpostChoices\&.TalkWithScientist ()"

.SH "Member Data Documentation"
.PP 
.SS "GameObject OutpostChoices\&.coverPanel"

.SS "GameObject OutpostChoices\&.defaultPanel"

.SS "\fBOutpostChoices\fP OutpostChoices\&.instance\fC [static]\fP"

.SS "bool OutpostChoices\&.isActive = false"

.SS "Text OutpostChoices\&.nameText"

.SS "GameObject OutpostChoices\&.newsPanel"

.SS "GameObject OutpostChoices\&.scientistIdleAnim"

.SS "GameObject OutpostChoices\&.scientistTalkAnim"

.SS "Text OutpostChoices\&.textBox"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
