.TH "OxygenTank" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OxygenTank
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlayerUpgrades\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetOxygenSupplyAmount\fP ()"
.br
.ti -1c
.RI "float \fBGetDefaultOxygenDepletionRate\fP ()"
.br
.ti -1c
.RI "float \fBGetOxygenDepletionRate\fP (int stage)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "float OxygenTank\&.GetDefaultOxygenDepletionRate ()"

.SS "float OxygenTank\&.GetOxygenDepletionRate (int stage)"

.SS "float OxygenTank\&.GetOxygenSupplyAmount ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
