.TH "PathMarker" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PathMarker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPathMarker\fP (\fBMapLocation\fP l, float g, float h, float f, GameObject \fBmarker\fP, \fBPathMarker\fP p)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMapLocation\fP \fBlocation\fP"
.br
.ti -1c
.RI "float \fBG\fP"
.br
.ti -1c
.RI "float \fBH\fP"
.br
.ti -1c
.RI "float \fBF\fP"
.br
.ti -1c
.RI "GameObject \fBmarker\fP"
.br
.ti -1c
.RI "\fBPathMarker\fP \fBparent\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PathMarker\&.PathMarker (\fBMapLocation\fP l, float g, float h, float f, GameObject marker, \fBPathMarker\fP p)"

.SH "Member Function Documentation"
.PP 
.SS "override bool PathMarker\&.Equals (object obj)"

.SS "override int PathMarker\&.GetHashCode ()"

.SH "Member Data Documentation"
.PP 
.SS "float PathMarker\&.F"

.SS "float PathMarker\&.G"

.SS "float PathMarker\&.H"

.SS "\fBMapLocation\fP PathMarker\&.location"

.SS "GameObject PathMarker\&.marker"

.SS "\fBPathMarker\fP PathMarker\&.parent"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
