.TH "PlayerBulletProperties" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerBulletProperties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBbulletDamage\fP"
.br
.ti -1c
.RI "float \fBbulletSpeed\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float PlayerBulletProperties\&.bulletDamage"

.SS "float PlayerBulletProperties\&.bulletSpeed"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
