.TH "Player" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBPlayerAttack\fP, \fBPlayerHealth\fP, and \fBPlayerMovement\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SpriteRenderer \fBsprite\fP"
.br
.ti -1c
.RI "Rigidbody2D \fBplayerRigidbody2D\fP"
.br
.ti -1c
.RI "bool \fBisDead\fP = false"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool Player\&.isDead = false\fC [protected]\fP"

.SS "Rigidbody2D Player\&.playerRigidbody2D\fC [protected]\fP"

.SS "SpriteRenderer Player\&.sprite\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
