.TH "PlayerSkills.OnSkillUnlockedEventArgs" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerSkills.OnSkillUnlockedEventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSkillType\fP \fBskillType\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBSkillType\fP PlayerSkills\&.OnSkillUnlockedEventArgs\&.skillType"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
