.TH "PlayerUpgrades" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerUpgrades
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBHull\fP, \fBInventory\fP, \fBOxygenTank\fP, \fBSelfRepair\fP, \fBTurbine\fP, and \fBWeapon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBitem\fP[] \fBGetFishMaterialTypeRequirement\fP ()"
.br
.ti -1c
.RI "\fBitem\fP[] \fBGetRawMaterialTypeRequirement\fP ()"
.br
.ti -1c
.RI "int[] \fBGetFishMaterialAmountRequirement\fP ()"
.br
.ti -1c
.RI "int[] \fBGetRawMaterialAmountRequirement\fP ()"
.br
.ti -1c
.RI "bool \fBIsUniqueFeatureUsed\fP ()"
.br
.ti -1c
.RI "bool \fBIsLowTierUpgrade\fP ()"
.br
.ti -1c
.RI "virtual \fBPlayerUpgrades\fP \fBGetCopy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBisUniqueFeatureUsed\fP"
.br
.ti -1c
.RI "bool \fBisLowTierUpgrade\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBPlayerUpgrades\fP PlayerUpgrades\&.GetCopy ()\fC [virtual]\fP"

.SS "int[] PlayerUpgrades\&.GetFishMaterialAmountRequirement ()"

.SS "\fBitem\fP[] PlayerUpgrades\&.GetFishMaterialTypeRequirement ()"

.SS "int[] PlayerUpgrades\&.GetRawMaterialAmountRequirement ()"

.SS "\fBitem\fP[] PlayerUpgrades\&.GetRawMaterialTypeRequirement ()"

.SS "bool PlayerUpgrades\&.IsLowTierUpgrade ()"

.SS "bool PlayerUpgrades\&.IsUniqueFeatureUsed ()"

.SH "Member Data Documentation"
.PP 
.SS "string PlayerUpgrades\&.ID"

.SS "bool PlayerUpgrades\&.isLowTierUpgrade\fC [protected]\fP"

.SS "bool PlayerUpgrades\&.isUniqueFeatureUsed\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
