.TH "PlayerHealth" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerHealth
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHull\fP \fBGetHull\fP ()"
.br
.ti -1c
.RI "void \fBGetDamage\fP (float damage)"
.br
.ti -1c
.RI "void \fBKillPlayer\fP ()"
.br
.ti -1c
.RI "void \fBDeletePersistentPathDirAndPlayerPrefs\fP ()"
.br
.ti -1c
.RI "void \fBOnInputSecondaryCommandSlot4\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBsaveHealth\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBhealth\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnHPDeplete\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnKO\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void PlayerHealth\&.DeletePersistentPathDirAndPlayerPrefs ()"

.SS "void PlayerHealth\&.GetDamage (float damage)"

.SS "\fBHull\fP PlayerHealth\&.GetHull ()"

.SS "void PlayerHealth\&.KillPlayer ()"

.SS "void PlayerHealth\&.OnInputSecondaryCommandSlot4 (InputAction\&.CallbackContext context)"

.SS "void PlayerHealth\&.saveHealth ()"

.SH "Member Data Documentation"
.PP 
.SS "float PlayerHealth\&.health"

.SS "UnityEvent PlayerHealth\&.OnHPDeplete"

.SS "UnityEvent PlayerHealth\&.OnKO"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
