.TH "PlayerBullet" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerBullet
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBBreakableWallBullet\fP, and \fBHomingBullet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnHitBox\fP (GameObject other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPlayerBulletProperties\fP \fBPlayerBulletProperties\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBBulletDamage\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBBulletSpeed\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void PlayerBullet\&.OnHitBox (GameObject other)"

.SS "void PlayerBullet\&.Start ()\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBPlayerBulletProperties\fP PlayerBullet\&.PlayerBulletProperties"

.SH "Property Documentation"
.PP 
.SS "float PlayerBullet\&.BulletDamage\fC [get]\fP, \fC [set]\fP"

.SS "float PlayerBullet\&.BulletSpeed\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
