.TH "PressureStageChecker" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PressureStageChecker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetStage\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int PressureStageChecker\&.GetStage ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
