.TH "PreviousPosition" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreviousPosition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSceneTransitioning\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBplayer\fP"
.br
.ti -1c
.RI "float \fBposX\fP"
.br
.ti -1c
.RI "float \fBposY\fP"
.br
.ti -1c
.RI "string \fBpreviousSceneName\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void PreviousPosition\&.Start ()\fC [virtual]\fP"

.PP
Reimplemented from \fBSceneTransitioning\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform PreviousPosition\&.player"

.SS "float PreviousPosition\&.posX"

.SS "float PreviousPosition\&.posY"

.SS "string PreviousPosition\&.previousSceneName"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
