.TH "RandomEnemy" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomEnemy
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBspawnEnemy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Collider2D[] \fBcolliders\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "Vector2 \fBpos\fP = new Vector2(0,0)"
.br
.ti -1c
.RI "GameObject \fBquad\fP"
.br
.ti -1c
.RI "List< GameObject > \fBenemyPool\fP"
.br
.ti -1c
.RI "int \fBnumberToSpawn\fP"
.br
.ti -1c
.RI "LayerMask \fBmask\fP"
.br
.ti -1c
.RI "float \fBspawnRad\fP = 5"
.br
.ti -1c
.RI "float \fBspawnCollisionCheckRadius\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void RandomEnemy\&.spawnEnemy ()"

.SH "Member Data Documentation"
.PP 
.SS "Collider2D [] RandomEnemy\&.colliders"

.SS "List<GameObject> RandomEnemy\&.enemyPool"

.SS "LayerMask RandomEnemy\&.mask"

.SS "int RandomEnemy\&.numberToSpawn"

.SS "Vector2 RandomEnemy\&.pos = new Vector2(0,0)"

.SS "GameObject RandomEnemy\&.quad"

.SS "float RandomEnemy\&.radius"

.SS "float RandomEnemy\&.spawnCollisionCheckRadius"

.SS "float RandomEnemy\&.spawnRad = 5"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
