.TH "RebindUISampleActionsModified.PlayerMainActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RebindUISampleActionsModified.PlayerMainActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerMainActions\fP (@\fBRebindUISampleActionsModified\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIPlayerMainActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBPlayerMainActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBCommandSlot0\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBCommandSlot1\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBCommandSlot2\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBCommandSlot3\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBSecondaryCommandSlot4\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBSecondaryCommandSlot5\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBTertiaryCommandSlotAxis6\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBTertiaryCommandSlotAxis7\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBStart\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBSelect\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBDPadAxisHorizontal\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBDPadAxisVertical\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBLeftStickAxisHorizontal\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBLeftStickAxisVertical\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBRightStickAxisHorizontal\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBRightStickAxisVertical\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RebindUISampleActionsModified\&.PlayerMainActions\&.PlayerMainActions (@\fBRebindUISampleActionsModified\fP wrapper)"

.SH "Member Function Documentation"
.PP 
.SS "void RebindUISampleActionsModified\&.PlayerMainActions\&.Disable ()"

.SS "void RebindUISampleActionsModified\&.PlayerMainActions\&.Enable ()"

.SS "InputActionMap RebindUISampleActionsModified\&.PlayerMainActions\&.Get ()"

.SS "static implicit RebindUISampleActionsModified\&.PlayerMainActions\&.operator InputActionMap (\fBPlayerMainActions\fP set)\fC [static]\fP"

.SS "void RebindUISampleActionsModified\&.PlayerMainActions\&.SetCallbacks (\fBIPlayerMainActions\fP instance)"

.SH "Property Documentation"
.PP 
.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.CommandSlot0\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.CommandSlot1\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.CommandSlot2\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.CommandSlot3\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.DPadAxisHorizontal\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.DPadAxisVertical\fC [get]\fP"

.SS "bool RebindUISampleActionsModified\&.PlayerMainActions\&.enabled\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.LeftStickAxisHorizontal\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.LeftStickAxisVertical\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.RightStickAxisHorizontal\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.RightStickAxisVertical\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.SecondaryCommandSlot4\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.SecondaryCommandSlot5\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.Select\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.Start\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.TertiaryCommandSlotAxis6\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.PlayerMainActions\&.TertiaryCommandSlotAxis7\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
