.TH "RebindUISampleActionsModified.IPlayerMainActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RebindUISampleActionsModified.IPlayerMainActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnCommandSlot0\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnCommandSlot1\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnCommandSlot2\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnCommandSlot3\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnSecondaryCommandSlot4\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnSecondaryCommandSlot5\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnTertiaryCommandSlotAxis6\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnTertiaryCommandSlotAxis7\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnStart\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnSelect\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnDPadAxisHorizontal\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnDPadAxisVertical\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnLeftStickAxisHorizontal\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnLeftStickAxisVertical\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnRightStickAxisHorizontal\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnRightStickAxisVertical\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnCommandSlot0 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnCommandSlot1 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnCommandSlot2 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnCommandSlot3 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnDPadAxisHorizontal (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnDPadAxisVertical (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnLeftStickAxisHorizontal (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnLeftStickAxisVertical (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnRightStickAxisHorizontal (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnRightStickAxisVertical (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnSecondaryCommandSlot4 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnSecondaryCommandSlot5 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnSelect (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnStart (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnTertiaryCommandSlotAxis6 (InputAction\&.CallbackContext context)"

.SS "void RebindUISampleActionsModified\&.IPlayerMainActions\&.OnTertiaryCommandSlotAxis7 (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
