.TH "RebindUISampleActionsModified.UIMainActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RebindUISampleActionsModified.UIMainActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUIMainActions\fP (@\fBRebindUISampleActionsModified\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIUIMainActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBUIMainActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBNavigate\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBSubmit\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBCancel\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBPoint\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBClick\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RebindUISampleActionsModified\&.UIMainActions\&.UIMainActions (@\fBRebindUISampleActionsModified\fP wrapper)"

.SH "Member Function Documentation"
.PP 
.SS "void RebindUISampleActionsModified\&.UIMainActions\&.Disable ()"

.SS "void RebindUISampleActionsModified\&.UIMainActions\&.Enable ()"

.SS "InputActionMap RebindUISampleActionsModified\&.UIMainActions\&.Get ()"

.SS "static implicit RebindUISampleActionsModified\&.UIMainActions\&.operator InputActionMap (\fBUIMainActions\fP set)\fC [static]\fP"

.SS "void RebindUISampleActionsModified\&.UIMainActions\&.SetCallbacks (\fBIUIMainActions\fP instance)"

.SH "Property Documentation"
.PP 
.SS "InputAction RebindUISampleActionsModified\&.UIMainActions\&.Cancel\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.UIMainActions\&.Click\fC [get]\fP"

.SS "bool RebindUISampleActionsModified\&.UIMainActions\&.enabled\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.UIMainActions\&.Navigate\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.UIMainActions\&.Point\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.UIMainActions\&.Submit\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
