.TH "RebindUISampleActionsModified.Vector2AxisActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RebindUISampleActionsModified.Vector2AxisActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector2AxisActions\fP (@\fBRebindUISampleActionsModified\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIVector2AxisActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBVector2AxisActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBNewaction\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBLeftStickAxis2D\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBRightStickAxis2D\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBDPadAxis2D\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RebindUISampleActionsModified\&.Vector2AxisActions\&.Vector2AxisActions (@\fBRebindUISampleActionsModified\fP wrapper)"

.SH "Member Function Documentation"
.PP 
.SS "void RebindUISampleActionsModified\&.Vector2AxisActions\&.Disable ()"

.SS "void RebindUISampleActionsModified\&.Vector2AxisActions\&.Enable ()"

.SS "InputActionMap RebindUISampleActionsModified\&.Vector2AxisActions\&.Get ()"

.SS "static implicit RebindUISampleActionsModified\&.Vector2AxisActions\&.operator InputActionMap (\fBVector2AxisActions\fP set)\fC [static]\fP"

.SS "void RebindUISampleActionsModified\&.Vector2AxisActions\&.SetCallbacks (\fBIVector2AxisActions\fP instance)"

.SH "Property Documentation"
.PP 
.SS "InputAction RebindUISampleActionsModified\&.Vector2AxisActions\&.DPadAxis2D\fC [get]\fP"

.SS "bool RebindUISampleActionsModified\&.Vector2AxisActions\&.enabled\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.Vector2AxisActions\&.LeftStickAxis2D\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.Vector2AxisActions\&.Newaction\fC [get]\fP"

.SS "InputAction RebindUISampleActionsModified\&.Vector2AxisActions\&.RightStickAxis2D\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
