.TH "SaveSystem" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaveSystem
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSavePlayer\fP (\fBPlayerMovement\fP playerMovement)"
.br
.ti -1c
.RI "static \fBPlayerData\fP \fBLoadPlayer\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBPlayerData\fP SaveSystem\&.LoadPlayer ()\fC [static]\fP"

.SS "static void SaveSystem\&.SavePlayer (\fBPlayerMovement\fP playerMovement)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
