.TH "SceneHandler" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRestartGame\fP ()"
.br
.ti -1c
.RI "void \fBMainMenu\fP ()"
.br
.ti -1c
.RI "void \fBQuit\fP ()"
.br
.ti -1c
.RI "void \fBLoadSceneByName\fP (string sceneName)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SceneHandler\&.LoadSceneByName (string sceneName)"

.SS "void SceneHandler\&.MainMenu ()"

.SS "void SceneHandler\&.Quit ()"

.SS "void SceneHandler\&.RestartGame ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
