.TH "SceneTransitioning" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneTransitioning
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBPreviousPosition\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBSceneTransition\fP (string name)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBprevScene\fP"
.br
.ti -1c
.RI "static string \fBcurrScene\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SceneTransitioning\&.SceneTransition (string name)"

.SS "virtual void SceneTransitioning\&.Start ()\fC [virtual]\fP"

.PP
Reimplemented in \fBPreviousPosition\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SceneTransitioning\&.currScene\fC [static]\fP"

.SS "string SceneTransitioning\&.prevScene\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
