.TH "SelfRepair" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SelfRepair
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlayerUpgrades\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetHealthRegenerationAmount\fP ()"
.br
.ti -1c
.RI "float \fBGetHealthRegenerationRate\fP ()"
.br
.ti -1c
.RI "int \fBGetAvailableHealthKits\fP ()"
.br
.ti -1c
.RI "float \fBGetHealthReplenishPercentage\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "int SelfRepair\&.GetAvailableHealthKits ()"

.SS "float SelfRepair\&.GetHealthRegenerationAmount ()"

.SS "float SelfRepair\&.GetHealthRegenerationRate ()"

.SS "float SelfRepair\&.GetHealthReplenishPercentage ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
