.TH "SetMaterialColorCommand" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetMaterialColorCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBInputCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecPress\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBnewColor\fP = Color\&.white"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void SetMaterialColorCommand\&.ExecPress ()\fC [virtual]\fP"

.PP
Reimplemented from \fBInputCommand\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color SetMaterialColorCommand\&.newColor = Color\&.white"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
