.TH "ShellExplosion" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShellExplosion
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayerMask \fBm_TankMask\fP"
.br
.ti -1c
.RI "ParticleSystem \fBm_ExplosionParticles\fP"
.br
.ti -1c
.RI "AudioSource \fBm_ExplosionAudio\fP"
.br
.ti -1c
.RI "float \fBm_MaxDamage\fP = 100f"
.br
.ti -1c
.RI "float \fBm_ExplosionForce\fP = 1000f"
.br
.ti -1c
.RI "float \fBm_MaxLifeTime\fP = 2f"
.br
.ti -1c
.RI "float \fBm_ExplosionRadius\fP = 5f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "AudioSource ShellExplosion\&.m_ExplosionAudio"

.SS "float ShellExplosion\&.m_ExplosionForce = 1000f"

.SS "ParticleSystem ShellExplosion\&.m_ExplosionParticles"

.SS "float ShellExplosion\&.m_ExplosionRadius = 5f"

.SS "float ShellExplosion\&.m_MaxDamage = 100f"

.SS "float ShellExplosion\&.m_MaxLifeTime = 2f"

.SS "LayerMask ShellExplosion\&.m_TankMask"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
