.TH "SimpleControls.GameplayActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleControls.GameplayActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameplayActions\fP (@\fBSimpleControls\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIGameplayActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBGameplayActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBfire\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBmove\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBlook\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SimpleControls\&.GameplayActions\&.GameplayActions (@\fBSimpleControls\fP wrapper)"

.SH "Member Function Documentation"
.PP 
.SS "void SimpleControls\&.GameplayActions\&.Disable ()"

.SS "void SimpleControls\&.GameplayActions\&.Enable ()"

.SS "InputActionMap SimpleControls\&.GameplayActions\&.Get ()"

.SS "static implicit SimpleControls\&.GameplayActions\&.operator InputActionMap (\fBGameplayActions\fP set)\fC [static]\fP"

.SS "void SimpleControls\&.GameplayActions\&.SetCallbacks (\fBIGameplayActions\fP instance)"

.SH "Property Documentation"
.PP 
.SS "bool SimpleControls\&.GameplayActions\&.enabled\fC [get]\fP"

.SS "InputAction SimpleControls\&.GameplayActions\&.fire\fC [get]\fP"

.SS "InputAction SimpleControls\&.GameplayActions\&.look\fC [get]\fP"

.SS "InputAction SimpleControls\&.GameplayActions\&.move\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
