.TH "SimpleController_UsingPlayerInput" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleController_UsingPlayerInput
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnMove\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnLook\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnFire\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBmoveSpeed\fP"
.br
.ti -1c
.RI "float \fBrotateSpeed\fP"
.br
.ti -1c
.RI "float \fBburstSpeed\fP"
.br
.ti -1c
.RI "GameObject \fBprojectile\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SimpleController_UsingPlayerInput\&.OnFire (InputAction\&.CallbackContext context)"

.SS "void SimpleController_UsingPlayerInput\&.OnGUI ()"

.SS "void SimpleController_UsingPlayerInput\&.OnLook (InputAction\&.CallbackContext context)"

.SS "void SimpleController_UsingPlayerInput\&.OnMove (InputAction\&.CallbackContext context)"

.SS "void SimpleController_UsingPlayerInput\&.Update ()"

.SH "Member Data Documentation"
.PP 
.SS "float SimpleController_UsingPlayerInput\&.burstSpeed"

.SS "float SimpleController_UsingPlayerInput\&.moveSpeed"

.SS "GameObject SimpleController_UsingPlayerInput\&.projectile"

.SS "float SimpleController_UsingPlayerInput\&.rotateSpeed"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
