.TH "SimpleController_UsingActionAsset" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleController_UsingActionAsset
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBmoveSpeed\fP"
.br
.ti -1c
.RI "float \fBrotateSpeed\fP"
.br
.ti -1c
.RI "float \fBburstSpeed\fP"
.br
.ti -1c
.RI "GameObject \fBprojectile\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SimpleController_UsingActionAsset\&.Awake ()"

.SS "void SimpleController_UsingActionAsset\&.OnDisable ()"

.SS "void SimpleController_UsingActionAsset\&.OnEnable ()"

.SS "void SimpleController_UsingActionAsset\&.OnGUI ()"

.SS "void SimpleController_UsingActionAsset\&.Update ()"

.SH "Member Data Documentation"
.PP 
.SS "float SimpleController_UsingActionAsset\&.burstSpeed"

.SS "float SimpleController_UsingActionAsset\&.moveSpeed"

.SS "GameObject SimpleController_UsingActionAsset\&.projectile"

.SS "float SimpleController_UsingActionAsset\&.rotateSpeed"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
