.TH "SimpleControls.IGameplayActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleControls.IGameplayActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnFire\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnMove\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnLook\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SimpleControls\&.IGameplayActions\&.OnFire (InputAction\&.CallbackContext context)"

.SS "void SimpleControls\&.IGameplayActions\&.OnLook (InputAction\&.CallbackContext context)"

.SS "void SimpleControls\&.IGameplayActions\&.OnMove (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
