.TH "Sound" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sound
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "AudioClip \fBclip\fP"
.br
.ti -1c
.RI "bool \fBloop\fP = false"
.br
.ti -1c
.RI "bool \fBisAllowMultiAudioSrcInstance\fP = false"
.br
.ti -1c
.RI "float \fBvolume\fP = 1f"
.br
.ti -1c
.RI "float \fBpitch\fP = 1f"
.br
.ti -1c
.RI "float \fBinitialVolume\fP"
.br
.ti -1c
.RI "AudioSource \fBsource\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "AudioClip Sound\&.clip"

.SS "float Sound\&.initialVolume"

.SS "bool Sound\&.isAllowMultiAudioSrcInstance = false"

.SS "bool Sound\&.loop = false"

.SS "string Sound\&.name"

.SS "float Sound\&.pitch = 1f"

.SS "AudioSource Sound\&.source"

.SS "float Sound\&.volume = 1f"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
