.TH "SpawnFlockManager" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpawnFlockManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject[] \fBobjPrefabs\fP"
.br
.ti -1c
.RI "int \fBflockCount\fP"
.br
.ti -1c
.RI "List< GameObject > \fBallObjsInFlock\fP"
.br
.ti -1c
.RI "Vector3 \fBboundLimits\fP = new Vector3(5, 5, 5)"
.br
.ti -1c
.RI "Vector3 \fBgoalPos\fP"
.br
.ti -1c
.RI "bool \fBisUseNavAgentInstead\fP"
.br
.ti -1c
.RI "float \fBminSpeed\fP"
.br
.ti -1c
.RI "float \fBmaxSpeed\fP"
.br
.ti -1c
.RI "float \fBrotationSpeed\fP = 4\&.0f"
.br
.ti -1c
.RI "float \fBneighbourDistance\fP = 3f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "List<GameObject> SpawnFlockManager\&.allObjsInFlock"

.SS "Vector3 SpawnFlockManager\&.boundLimits = new Vector3(5, 5, 5)"

.SS "int SpawnFlockManager\&.flockCount"

.SS "Vector3 SpawnFlockManager\&.goalPos"

.SS "bool SpawnFlockManager\&.isUseNavAgentInstead"

.SS "float SpawnFlockManager\&.maxSpeed"

.SS "float SpawnFlockManager\&.minSpeed"

.SS "float SpawnFlockManager\&.neighbourDistance = 3f"

.SS "GameObject [] SpawnFlockManager\&.objPrefabs"

.SS "float SpawnFlockManager\&.rotationSpeed = 4\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
