.TH "StdioCommon" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdioCommon
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBStringUppercaseFirstLetter\fP (string str)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static string StdioCommon\&.StringUppercaseFirstLetter (string str)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
