.TH "storage" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
storage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBItemContainer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBSetInventoryUpgrade\fP (\fBInventory\fP inventoryUpgrade)"
.br
.ti -1c
.RI "List< \fBitemSlots\fP > \fBGetListOfItemsInInventory\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void storage\&.Awake ()\fC [virtual]\fP"

.PP
Reimplemented from \fBItemContainer\fP\&.
.SS "List< \fBitemSlots\fP > storage\&.GetListOfItemsInInventory ()"

.SS "void storage\&.SetInventoryUpgrade (\fBInventory\fP inventoryUpgrade)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
