.TH "SyncTextWithTextMeshPro" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncTextWithTextMeshPro
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBtext\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBtext_TMPro\fP"
.br
.ti -1c
.RI "string \fBremoveString\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string SyncTextWithTextMeshPro\&.removeString"

.SS "Text SyncTextWithTextMeshPro\&.text"

.SS "TextMeshProUGUI SyncTextWithTextMeshPro\&.text_TMPro"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
