.TH "TankMovement" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TankMovement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBm_PlayerNumber\fP = 1"
.br
.ti -1c
.RI "float \fBm_Speed\fP = 12f"
.br
.ti -1c
.RI "float \fBm_TurnSpeed\fP = 180f"
.br
.ti -1c
.RI "AudioSource \fBm_MovementAudio\fP"
.br
.ti -1c
.RI "AudioClip \fBm_EngineIdling\fP"
.br
.ti -1c
.RI "AudioClip \fBm_EngineDriving\fP"
.br
.ti -1c
.RI "float \fBm_PitchRange\fP = 0\&.2f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "AudioClip TankMovement\&.m_EngineDriving"

.SS "AudioClip TankMovement\&.m_EngineIdling"

.SS "AudioSource TankMovement\&.m_MovementAudio"

.SS "float TankMovement\&.m_PitchRange = 0\&.2f"

.SS "int TankMovement\&.m_PlayerNumber = 1"

.SS "float TankMovement\&.m_Speed = 12f"

.SS "float TankMovement\&.m_TurnSpeed = 180f"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
