.TH "TankShooting" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TankShooting
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBm_PlayerNumber\fP = 1"
.br
.ti -1c
.RI "Rigidbody \fBm_Shell\fP"
.br
.ti -1c
.RI "Transform \fBm_FireTransform\fP"
.br
.ti -1c
.RI "Slider \fBm_AimSlider\fP"
.br
.ti -1c
.RI "AudioSource \fBm_ShootingAudio\fP"
.br
.ti -1c
.RI "AudioClip \fBm_ChargingClip\fP"
.br
.ti -1c
.RI "AudioClip \fBm_FireClip\fP"
.br
.ti -1c
.RI "float \fBm_MinLaunchForce\fP = 15f"
.br
.ti -1c
.RI "float \fBm_MaxLaunchForce\fP = 30f"
.br
.ti -1c
.RI "float \fBm_MaxChargeTime\fP = 0\&.75f"
.br
.ti -1c
.RI "bool \fBm_Fired\fP"
.br
.ti -1c
.RI "bool \fBm_FireButtonPressedThisFrame\fP"
.br
.ti -1c
.RI "bool \fBm_FireButtonReleasedThisFrame\fP"
.br
.ti -1c
.RI "bool \fBm_FireButtonDown\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Slider TankShooting\&.m_AimSlider"

.SS "AudioClip TankShooting\&.m_ChargingClip"

.SS "bool TankShooting\&.m_FireButtonDown"

.SS "bool TankShooting\&.m_FireButtonPressedThisFrame"

.SS "bool TankShooting\&.m_FireButtonReleasedThisFrame"

.SS "AudioClip TankShooting\&.m_FireClip"

.SS "bool TankShooting\&.m_Fired"

.SS "Transform TankShooting\&.m_FireTransform"

.SS "float TankShooting\&.m_MaxChargeTime = 0\&.75f"

.SS "float TankShooting\&.m_MaxLaunchForce = 30f"

.SS "float TankShooting\&.m_MinLaunchForce = 15f"

.SS "int TankShooting\&.m_PlayerNumber = 1"

.SS "Rigidbody TankShooting\&.m_Shell"

.SS "AudioSource TankShooting\&.m_ShootingAudio"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
