.TH "TanksInputActions.UIActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TanksInputActions.UIActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUIActions\fP (@\fBTanksInputActions\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIUIActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBUIActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBNavigate\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBSubmit\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBCancel\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBPoint\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBClick\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TanksInputActions\&.UIActions\&.UIActions (@\fBTanksInputActions\fP wrapper)"

.SH "Member Function Documentation"
.PP 
.SS "void TanksInputActions\&.UIActions\&.Disable ()"

.SS "void TanksInputActions\&.UIActions\&.Enable ()"

.SS "InputActionMap TanksInputActions\&.UIActions\&.Get ()"

.SS "static implicit TanksInputActions\&.UIActions\&.operator InputActionMap (\fBUIActions\fP set)\fC [static]\fP"

.SS "void TanksInputActions\&.UIActions\&.SetCallbacks (\fBIUIActions\fP instance)"

.SH "Property Documentation"
.PP 
.SS "InputAction TanksInputActions\&.UIActions\&.Cancel\fC [get]\fP"

.SS "InputAction TanksInputActions\&.UIActions\&.Click\fC [get]\fP"

.SS "bool TanksInputActions\&.UIActions\&.enabled\fC [get]\fP"

.SS "InputAction TanksInputActions\&.UIActions\&.Navigate\fC [get]\fP"

.SS "InputAction TanksInputActions\&.UIActions\&.Point\fC [get]\fP"

.SS "InputAction TanksInputActions\&.UIActions\&.Submit\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
