.TH "TanksInputActions.IUIActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TanksInputActions.IUIActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnNavigate\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnSubmit\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnCancel\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnPoint\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnClick\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TanksInputActions\&.IUIActions\&.OnCancel (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IUIActions\&.OnClick (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IUIActions\&.OnNavigate (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IUIActions\&.OnPoint (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IUIActions\&.OnSubmit (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
