.TH "TanksInputActions.IPlayerActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TanksInputActions.IPlayerActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnGas\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnBrake\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnTurret\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnFire\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnPause\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TanksInputActions\&.IPlayerActions\&.OnBrake (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IPlayerActions\&.OnFire (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IPlayerActions\&.OnGas (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IPlayerActions\&.OnPause (InputAction\&.CallbackContext context)"

.SS "void TanksInputActions\&.IPlayerActions\&.OnTurret (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
