.TH "TanksInputActions.PlayerActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TanksInputActions.PlayerActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerActions\fP (@\fBTanksInputActions\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIPlayerActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBPlayerActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBGas\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBBrake\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBTurret\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBFire\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBPause\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TanksInputActions\&.PlayerActions\&.PlayerActions (@\fBTanksInputActions\fP wrapper)"

.SH "Member Function Documentation"
.PP 
.SS "void TanksInputActions\&.PlayerActions\&.Disable ()"

.SS "void TanksInputActions\&.PlayerActions\&.Enable ()"

.SS "InputActionMap TanksInputActions\&.PlayerActions\&.Get ()"

.SS "static implicit TanksInputActions\&.PlayerActions\&.operator InputActionMap (\fBPlayerActions\fP set)\fC [static]\fP"

.SS "void TanksInputActions\&.PlayerActions\&.SetCallbacks (\fBIPlayerActions\fP instance)"

.SH "Property Documentation"
.PP 
.SS "InputAction TanksInputActions\&.PlayerActions\&.Brake\fC [get]\fP"

.SS "bool TanksInputActions\&.PlayerActions\&.enabled\fC [get]\fP"

.SS "InputAction TanksInputActions\&.PlayerActions\&.Fire\fC [get]\fP"

.SS "InputAction TanksInputActions\&.PlayerActions\&.Gas\fC [get]\fP"

.SS "InputAction TanksInputActions\&.PlayerActions\&.Pause\fC [get]\fP"

.SS "InputAction TanksInputActions\&.PlayerActions\&.Turret\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
