.TH "C:/_SSDSPEEDUP/2021/clone/gps1_manadesigner/GPS1-Manadesigner/Assets/Samples/Input System/1.0.2/Tanks Demo/TanksDemo/TanksInputActions.cs" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/clone/gps1_manadesigner/GPS1-Manadesigner/Assets/Samples/Input System/1.0.2/Tanks Demo/TanksDemo/TanksInputActions.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTanksInputActions\fP"
.br
.ti -1c
.RI "struct \fBTanksInputActions\&.PlayerActions\fP"
.br
.ti -1c
.RI "struct \fBTanksInputActions\&.UIActions\fP"
.br
.ti -1c
.RI "interface \fBTanksInputActions\&.IPlayerActions\fP"
.br
.ti -1c
.RI "interface \fBTanksInputActions\&.IUIActions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
