.TH "TankManager" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TankManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBDisableControl\fP ()"
.br
.ti -1c
.RI "void \fBEnableControl\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBm_PlayerColor\fP"
.br
.ti -1c
.RI "Transform \fBm_SpawnPoint\fP"
.br
.ti -1c
.RI "int \fBm_PlayerNumber\fP"
.br
.ti -1c
.RI "string \fBm_ColoredPlayerText\fP"
.br
.ti -1c
.RI "GameObject \fBm_Instance\fP"
.br
.ti -1c
.RI "int \fBm_Wins\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TankManager\&.DisableControl ()"

.SS "void TankManager\&.EnableControl ()"

.SS "void TankManager\&.Reset ()"

.SS "void TankManager\&.Setup ()"

.SH "Member Data Documentation"
.PP 
.SS "string TankManager\&.m_ColoredPlayerText"

.SS "GameObject TankManager\&.m_Instance"

.SS "Color TankManager\&.m_PlayerColor"

.SS "int TankManager\&.m_PlayerNumber"

.SS "Transform TankManager\&.m_SpawnPoint"

.SS "int TankManager\&.m_Wins"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
