.TH "TestDialogue" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestDialogue
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartUpdating\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP = 0"
.br
.ti -1c
.RI "string \fBnoticeToAllTechs\fP = 'Leave the last element in every dialogue boxes empty or there'll be an \fBindex\fP boundary error\&.'"
.br
.ti -1c
.RI "string[] \fBdayOne\fP"
.br
.ti -1c
.RI "string[] \fBdayTwo\fP"
.br
.ti -1c
.RI "string[] \fBdayFive\fP"
.br
.ti -1c
.RI "string[] \fBdayFourteen\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBTestDialogue\fP \fBinstance\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TestDialogue\&.StartUpdating ()"

.SH "Member Data Documentation"
.PP 
.SS "string [] TestDialogue\&.dayFive"
\fBInitial value:\fP
.PP
.nf
= new string[]
    {
        "Oh, hmm\&. Things have been… hectic around here\&. :Liam",
        "Liam looks tired, as if he hasn’t had a good night’s sleep lately\&. :You",
        "Research has been coming along well at least\&. Good progress\&. We’re catching up with them\&. :Liam",
        "A long breath of relief escapes from him\&. :You",
        "Liam takes out his clipboard and looks through a few papers\&.",
        "They’re almost at the end of the Continental Region\&. :Liam",
        " "
    }
.fi
.SS "string [] TestDialogue\&.dayFourteen"
\fBInitial value:\fP
.PP
.nf
= new string[]
    {
        "Well, it’s the final day\&. :Liam McCoy",
        "Liam’s voice is stoic despite the exhaustion weighing him down\&. :",
        "He takes out his clipboard, but he doesn’t even look at it to know what to say next\&.",
        "It’s approximately 20 hours before they reach the bottom\&. Maybe even less\&. :Liam McCoy",
        "His eyes stare intensely into yours\&. : ",
        "It’s now or never\&. This is your last shot\&. :Liam McCoy",
        "Liam claps a hand on your shoulder, firmly\&. : ",
        "Go out there and prove that you’re really the Navy’s finest\&. : Liam McCoy",
        " "
    }
.fi
.SS "string [] TestDialogue\&.dayOne"
\fBInitial value:\fP
.PP
.nf
= new string[]
    {
        "As you enter the room you were in the day before, you see Liam pacing around frantically\&. :You",
        "There you are, finally! :Liam",
        "He doesn’t seem to be very happy\&. :You",
        "You’re not late, are you? You ask Liam\&.",
        "No, no, it’s-- ugh\&. :Liam",
        "It’s clear that he’s stressed out of his mind, restless feet walking back and forth, restless fingers clicking on his pen\&. :You",
        "The USSR\&. We’ve just received intel they’re inbound to the bottom in 14 days\&. 14 days! That’s barely enough time to do anything\&. I was expecting soon, but- :Liam",
        "The panic in his voice is thick, so unlike what you’ve seen of him yesterday\&. :You",
        "You try reassuring him that you’ll do your best, and this calms him, somewhat\&.",
        "Okay\&. Okay\&. :Liam",
        "Liam takes a deep breath and gathers his composure\&. Then, he stares straight into your eyes, deathly serious\&. :You",
        "If you’re really the Navy’s top diver, then you better start now if we’re going to stand a chance\&. :Liam",
        "You tell him that you’ve got this and hurriedly get changed into your gear\&. :You",
        "Liam clasps a firm grip onto your shoulder, and nudges you towards the submarine docking station\&.",
        "We’re counting on you\&. :Liam",
        " "
    }
.fi
.SS "string [] TestDialogue\&.dayTwo"
\fBInitial value:\fP
.PP
.nf
= new string[]
    {
        "Well, not much to update, really\&. The USSR is making steady progress\&. :Liam",
        "With the current projections and the speed they’re going, they’ll reach there in 2 weeks, as we’ve speculated\&.",
        "Maybe even less\&.",
        "Liam lets out an exhausted sigh\&. The news has taken a toll on him\&. :You",
        "There’s no point worrying about this, in any case\&. We’ll do what we have to do\&. :Liam",
        "He’s extremely bad at hiding his worry, even with his arms folded\&. A lone finger taps against his arm in apprehensive energy\&. :You",
        "Just keep at it with what you’re doing, and we’ll be fine\&. :Liam",
        "Liam looks at you, a subtle expression of concern mingled with a hint of hope\&. :You",
        " "
    }
.fi
.SS "int TestDialogue\&.index = 0"

.SS "\fBTestDialogue\fP TestDialogue\&.instance\fC [static]\fP"

.SS "string TestDialogue\&.noticeToAllTechs = 'Leave the last element in every dialogue boxes empty or there'll be an \fBindex\fP boundary error\&.'"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
