.TH "TextAnimation" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextAnimation
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBchoices\fP"
.br
.ti -1c
.RI "GameObject \fBtext\fP"
.br
.ti -1c
.RI "GameObject \fBcoverHover\fP"
.br
.ti -1c
.RI "GameObject \fBpressEnter\fP"
.br
.ti -1c
.RI "float \fBtextDelay\fP = 0\&.1f"
.br
.ti -1c
.RI "string \fBfullText\fP"
.br
.ti -1c
.RI "bool \fBfinishText\fP = false"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GameObject TextAnimation\&.choices"

.SS "GameObject TextAnimation\&.coverHover"

.SS "bool TextAnimation\&.finishText = false"

.SS "string TextAnimation\&.fullText"

.SS "GameObject TextAnimation\&.pressEnter"

.SS "GameObject TextAnimation\&.text"

.SS "float TextAnimation\&.textDelay = 0\&.1f"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
