.TH "TimedParamStateBehavior" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimedParamStateBehavior
.SH SYNOPSIS
.br
.PP
.PP
Inherits StateMachineBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStateEnter\fP (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"
.br
.ti -1c
.RI "override void \fBOnStateUpdate\fP (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"
.br
.ti -1c
.RI "override void \fBOnStateExit\fP (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSetParamStateData\fP \fBdata\fP"
.br
.ti -1c
.RI "float \fBStart\fP"
.br
.ti -1c
.RI "float \fBEnd\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void TimedParamStateBehavior\&.OnStateEnter (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"

.SS "override void TimedParamStateBehavior\&.OnStateExit (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"

.SS "override void TimedParamStateBehavior\&.OnStateUpdate (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"

.SH "Member Data Documentation"
.PP 
.SS "\fBSetParamStateData\fP TimedParamStateBehavior\&.data"

.SS "float TimedParamStateBehavior\&.End"

.SS "float TimedParamStateBehavior\&.Start"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
