.TH "TransformPosShake" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransformPosShake
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBstart\fP = false"
.br
.ti -1c
.RI "AnimationCurve \fBcurve\fP"
.br
.ti -1c
.RI "float \fBduration\fP = 1f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "AnimationCurve TransformPosShake\&.curve"

.SS "float TransformPosShake\&.duration = 1f"

.SS "bool TransformPosShake\&.start = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
