.TH "TransformAutoRelative" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransformAutoRelative
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBrelativeObj\fP"
.br
.ti -1c
.RI "bool \fBisSnapPosToObj\fP"
.br
.ti -1c
.RI "bool \fBisRelativePos\fP"
.br
.ti -1c
.RI "bool \fBisRelativeRot\fP"
.br
.ti -1c
.RI "bool \fBisRelativeScale\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool TransformAutoRelative\&.isRelativePos"

.SS "bool TransformAutoRelative\&.isRelativeRot"

.SS "bool TransformAutoRelative\&.isRelativeScale"

.SS "bool TransformAutoRelative\&.isSnapPosToObj"

.SS "Transform TransformAutoRelative\&.relativeObj"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
