.TH "TriggerTransitionTuto" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriggerTransitionTuto
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.ti -1c
.RI "void \fBOnTriggerEnter2D\fP (Collider2D collision)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBoutpostTransition\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void TriggerTransitionTuto\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.SS "void TriggerTransitionTuto\&.OnTriggerEnter2D (Collider2D collision)"

.SH "Member Data Documentation"
.PP 
.SS "Transform TriggerTransitionTuto\&.outpostTransition"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
