.TH "Turbine" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Turbine
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlayerUpgrades\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetTurbineSpeed\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "float Turbine\&.GetTurbineSpeed ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
