.TH "TutoManager" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TutoManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTutorial\fP \fBTutoSequence\fP (int order)"
.br
.ti -1c
.RI "void \fBNextTutorial\fP (int onSequence)"
.br
.ti -1c
.RI "void \fBTutoComplete\fP ()"
.br
.ti -1c
.RI "void \fBEndTuto\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBTutorial\fP > \fBtutorials\fP = new List<\fBTutorial\fP>()"
.br
.ti -1c
.RI "Text \fBdialogue\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTutoManager\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TutoManager\&.EndTuto ()"

.SS "void TutoManager\&.NextTutorial (int onSequence)"

.SS "void TutoManager\&.TutoComplete ()"

.SS "\fBTutorial\fP TutoManager\&.TutoSequence (int order)"

.SH "Member Data Documentation"
.PP 
.SS "Text TutoManager\&.dialogue"

.SS "List<\fBTutorial\fP> TutoManager\&.tutorials = new List<\fBTutorial\fP>()"

.SH "Property Documentation"
.PP 
.SS "\fBTutoManager\fP TutoManager\&.instance\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
