.TH "TutoOutpostDialogue" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TutoOutpostDialogue
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBcoverPanel\fP"
.br
.ti -1c
.RI "GameObject \fBscientist\fP"
.br
.ti -1c
.RI "int \fBindex\fP = 0"
.br
.ti -1c
.RI "string \fBnoticeToAllTechs\fP = 'Leave the last element in every dialogue boxes empty or there'll be an \fBindex\fP boundary error\&.'"
.br
.ti -1c
.RI "string[] \fBtutorial\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBTutoOutpostDialogue\fP \fBinstance\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GameObject TutoOutpostDialogue\&.coverPanel"

.SS "int TutoOutpostDialogue\&.index = 0"

.SS "\fBTutoOutpostDialogue\fP TutoOutpostDialogue\&.instance\fC [static]\fP"

.SS "string TutoOutpostDialogue\&.noticeToAllTechs = 'Leave the last element in every dialogue boxes empty or there'll be an \fBindex\fP boundary error\&.'"

.SS "GameObject TutoOutpostDialogue\&.scientist"

.SS "string [] TutoOutpostDialogue\&.tutorial"
\fBInitial value:\fP
.PP
.nf
= new string[]
    {
        "A quiet, content hum from Liam\&. :You",
        "Pointing at the shelf and wooden counter that was definitely not here from before, he gives you a serious look\&.",
        "This is where you’ll be handing in your ‘haul of the day’\&. :Liam",
        "You see him do air quotes when he says that\&. :You",
        "We need a certain amount of specimens to be able to complete research on a specific submarine component\&. :Liam",
        "Once you turn them in, we’ll be able to hand you the research results, which, in your case, is an upgraded component to help you navigate the ocean better\&.",
        "I’ve set up something to help you get into the routine\&. ",
        "Liam jabs a finger at the only component on the shelf-- the Oxygen Tank\&. :You",
        "Click on it to see what upgrades are available for it\&. :Liam",
        "If you hover over it, you’ll see the details of what and how many of each resource you’ll need to exchange to obtain the upgrade\&.",
        "Since you have enough resources for this, click on exchange\&.",
        "After that, you’re done\&. We’ll handle the rest for you\&.",
        "The upgrade will be available during your next dive, so basically the next day\&.",
        "Liam tilts his head questioningly at you\&. :You",
        "Got it? :Liam",
        "You nod\&. :You",
        "The tension from his shoulders seems to disappear when you did that\&.",
        "Good\&. If you’ll excuse me, I’ll be going back to work\&. :Liam",
        "He doesn’t spare another moment before taking his leave\&. :You",
        "See you tomorrow\&. :Liam",
        "You are left to your own devices, unsupervised\&. :You",
        "You spend the remaining time of your day checking if your submarine is in good order and touring around the outpost\&.",
        "So far, it’s off to a great start, you think\&. ",
        " "
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
