.TH "Tutorial" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tutorial
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBButtonTuto\fP, \fBCloseButtonTuto\fP, \fBContinueNextTuto\fP, \fBHoldKeyInputTuto\fP, \fBKeyInputTuto\fP, and \fBTriggerTransitionTuto\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBCheckIfHappening\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsequence\fP"
.br
.ti -1c
.RI "string \fBtutoDialogue\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Tutorial\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented in \fBButtonTuto\fP, \fBCloseButtonTuto\fP, \fBContinueNextTuto\fP, \fBHoldKeyInputTuto\fP, \fBKeyInputTuto\fP, and \fBTriggerTransitionTuto\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Tutorial\&.sequence"

.SS "string Tutorial\&.tutoDialogue"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
