.TH "UI_SkillTree" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI_SkillTree
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBBeginPurchase\fP ()"
.br
.ti -1c
.RI "void \fBStartBuyingUpgrade\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierTurbineStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierTurbineStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierTurbineStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierTurbineStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierWeaponStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierWeaponStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierWeaponStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierWeaponStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierHullStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierHullStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierHullStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierHullStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierSelfRepairStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierSelfRepairStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierSelfRepairStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierSelfRepairStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierOxygenTankStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierOxygenTankStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierOxygenTankStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierOxygenTankStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierInventoryStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenLowTierInventoryStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierInventoryStage1Button\fP ()"
.br
.ti -1c
.RI "void \fBChosenHighTierInventoryStage2Button\fP ()"
.br
.ti -1c
.RI "void \fBSetPlayerSkills\fP (\fBPlayerSkills\fP playerSkills)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBeginPurchase\fP \fBbeginPurchase\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "delegate void UI_SkillTree\&.BeginPurchase ()"

.SS "void UI_SkillTree\&.ChosenHighTierHullStage1Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierHullStage2Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierInventoryStage1Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierInventoryStage2Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierOxygenTankStage1Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierOxygenTankStage2Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierSelfRepairStage1Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierSelfRepairStage2Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierTurbineStage1Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierTurbineStage2Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierWeaponStage1Button ()"

.SS "void UI_SkillTree\&.ChosenHighTierWeaponStage2Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierHullStage1Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierHullStage2Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierInventoryStage1Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierInventoryStage2Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierOxygenTankStage1Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierOxygenTankStage2Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierSelfRepairStage1Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierSelfRepairStage2Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierTurbineStage1Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierTurbineStage2Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierWeaponStage1Button ()"

.SS "void UI_SkillTree\&.ChosenLowTierWeaponStage2Button ()"

.SS "void UI_SkillTree\&.SetPlayerSkills (\fBPlayerSkills\fP playerSkills)"

.SS "void UI_SkillTree\&.StartBuyingUpgrade ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBBeginPurchase\fP UI_SkillTree\&.beginPurchase"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
