.TH "UICommandList" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UICommandList
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddCommand\fP (\fBICommandOWS\fP command)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void UICommandList\&.AddCommand (\fBICommandOWS\fP command)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
