.TH "UIHPSliderColor" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIHPSliderColor
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBUIColorTransition\fP { \fBHigh\fP, \fBMed\fP, \fBLow\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCurrColorTransitionBySliderValue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBhigh\fP = Color\&.green"
.br
.ti -1c
.RI "Color \fBmed\fP = Color\&.yellow"
.br
.ti -1c
.RI "Color \fBlow\fP = new Color(1\&.0f, 0\&.64f, 0\&.0f)"
.br
.ti -1c
.RI "\fBUIColorTransition\fP \fBcurrColorTransition\fP"
.br
.ti -1c
.RI "Slider \fBslider\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUIHPSliderColor\&.UIColorTransition\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHigh \fP\fP
.TP
\fB\fIMed \fP\fP
.TP
\fB\fILow \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "void UIHPSliderColor\&.SetCurrColorTransitionBySliderValue ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBUIColorTransition\fP UIHPSliderColor\&.currColorTransition"

.SS "Color UIHPSliderColor\&.high = Color\&.green"

.SS "Color UIHPSliderColor\&.low = new Color(1\&.0f, 0\&.64f, 0\&.0f)"

.SS "Color UIHPSliderColor\&.med = Color\&.yellow"

.SS "Slider UIHPSliderColor\&.slider"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
