.TH "UIToggleSaveToPlayerPrefs" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIToggleSaveToPlayerPrefs
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Toggle \fBtoggleComp\fP"
.br
.ti -1c
.RI "string \fBpPrefsName\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string UIToggleSaveToPlayerPrefs\&.pPrefsName"

.SS "Toggle UIToggleSaveToPlayerPrefs\&.toggleComp"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
