.TH "UnityEngine.PostProcessing.GrainModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.GrainModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBcolored\fP"
.br
.ti -1c
.RI "float \fBintensity\fP"
.br
.ti -1c
.RI "float \fBsize\fP"
.br
.ti -1c
.RI "float \fBluminanceContribution\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.PostProcessing\&.GrainModel\&.Settings\&.colored"

.SS "float UnityEngine\&.PostProcessing\&.GrainModel\&.Settings\&.intensity"

.SS "float UnityEngine\&.PostProcessing\&.GrainModel\&.Settings\&.luminanceContribution"

.SS "float UnityEngine\&.PostProcessing\&.GrainModel\&.Settings\&.size"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.GrainModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
