.TH "UnityEngine.PostProcessing.DepthOfFieldModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.DepthOfFieldModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfocusDistance\fP"
.br
.ti -1c
.RI "float \fBaperture\fP"
.br
.ti -1c
.RI "float \fBfocalLength\fP"
.br
.ti -1c
.RI "bool \fBuseCameraFov\fP"
.br
.ti -1c
.RI "\fBKernelSize\fP \fBkernelSize\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.PostProcessing\&.DepthOfFieldModel\&.Settings\&.aperture"

.SS "float UnityEngine\&.PostProcessing\&.DepthOfFieldModel\&.Settings\&.focalLength"

.SS "float UnityEngine\&.PostProcessing\&.DepthOfFieldModel\&.Settings\&.focusDistance"

.SS "\fBKernelSize\fP UnityEngine\&.PostProcessing\&.DepthOfFieldModel\&.Settings\&.kernelSize"

.SS "bool UnityEngine\&.PostProcessing\&.DepthOfFieldModel\&.Settings\&.useCameraFov"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.DepthOfFieldModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
