.TH "UnityEngine.PostProcessing.MotionBlurComponent.FrameBlendingFilter" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.MotionBlurComponent.FrameBlendingFilter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrameBlendingFilter\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.ti -1c
.RI "void \fBPushFrame\fP (CommandBuffer cb, RenderTargetIdentifier source, int width, int height, Material material)"
.br
.ti -1c
.RI "void \fBBlendFrames\fP (CommandBuffer cb, float strength, RenderTargetIdentifier source, RenderTargetIdentifier destination, Material material)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.PostProcessing\&.MotionBlurComponent\&.FrameBlendingFilter\&.FrameBlendingFilter ()"

.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.MotionBlurComponent\&.FrameBlendingFilter\&.BlendFrames (CommandBuffer cb, float strength, RenderTargetIdentifier source, RenderTargetIdentifier destination, Material material)"

.SS "void UnityEngine\&.PostProcessing\&.MotionBlurComponent\&.FrameBlendingFilter\&.Dispose ()"

.SS "void UnityEngine\&.PostProcessing\&.MotionBlurComponent\&.FrameBlendingFilter\&.PushFrame (CommandBuffer cb, RenderTargetIdentifier source, int width, int height, Material material)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
