.TH "UnityEngine.PostProcessing.PostProcessingComponentCommandBuffer< T >" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingComponentCommandBuffer< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract CameraEvent \fBGetCameraEvent\fP ()"
.br
.ti -1c
.RI "abstract string \fBGetName\fP ()"
.br
.ti -1c
.RI "abstract void \fBPopulateCommandBuffer\fP (CommandBuffer cb)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "abstract CameraEvent \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer\fP< T >\&.GetCameraEvent ()\fC [pure virtual]\fP"

.PP
Implemented in \fBUnityEngine\&.PostProcessing\&.AmbientOcclusionComponent\fP, \fBUnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\fP, \fBUnityEngine\&.PostProcessing\&.FogComponent\fP, \fBUnityEngine\&.PostProcessing\&.MotionBlurComponent\fP, and \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionComponent\fP\&.
.SS "abstract string \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer\fP< T >\&.GetName ()\fC [pure virtual]\fP"

.PP
Implemented in \fBUnityEngine\&.PostProcessing\&.AmbientOcclusionComponent\fP, \fBUnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\fP, \fBUnityEngine\&.PostProcessing\&.FogComponent\fP, \fBUnityEngine\&.PostProcessing\&.MotionBlurComponent\fP, and \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionComponent\fP\&.
.SS "abstract void \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer\fP< T >\&.PopulateCommandBuffer (CommandBuffer cb)\fC [pure virtual]\fP"

.PP
Implemented in \fBUnityEngine\&.PostProcessing\&.AmbientOcclusionComponent\fP, \fBUnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\fP, \fBUnityEngine\&.PostProcessing\&.FogComponent\fP, \fBUnityEngine\&.PostProcessing\&.MotionBlurComponent\fP, and \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
