.TH "UnityEngine.PostProcessing.ColorGradingModel.TonemappingSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.TonemappingSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTonemapper\fP \fBtonemapper\fP"
.br
.ti -1c
.RI "float \fBneutralBlackIn\fP"
.br
.ti -1c
.RI "float \fBneutralWhiteIn\fP"
.br
.ti -1c
.RI "float \fBneutralBlackOut\fP"
.br
.ti -1c
.RI "float \fBneutralWhiteOut\fP"
.br
.ti -1c
.RI "float \fBneutralWhiteLevel\fP"
.br
.ti -1c
.RI "float \fBneutralWhiteClip\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTonemappingSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.neutralBlackIn"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.neutralBlackOut"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.neutralWhiteClip"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.neutralWhiteIn"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.neutralWhiteLevel"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.neutralWhiteOut"

.SS "\fBTonemapper\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.tonemapper"

.SH "Property Documentation"
.PP 
.SS "\fBTonemappingSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.TonemappingSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
