.TH "UnityEngine.PostProcessing.ScreenSpaceReflectionModel" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ScreenSpaceReflectionModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIntensitySettings\fP"
.br
.ti -1c
.RI "struct \fBReflectionSettings\fP"
.br
.ti -1c
.RI "struct \fBScreenEdgeMask\fP"
.br
.ti -1c
.RI "struct \fBSettings\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSSRResolution\fP { \fBHigh\fP = 0, \fBLow\fP = 2 }"
.br
.ti -1c
.RI "enum \fBSSRReflectionBlendType\fP { \fBPhysicallyBased\fP, \fBAdditive\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReset\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSettings\fP \fBsettings\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.SSRReflectionBlendType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPhysicallyBased \fP\fP
.TP
\fB\fIAdditive \fP\fP
.SS "enum \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.SSRResolution\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHigh \fP\fP
.TP
\fB\fILow \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.Reset ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.settings\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
