.TH "UnityEngine.PostProcessing.ColorGradingModel.LinearWheelsSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.LinearWheelsSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBlift\fP"
.br
.ti -1c
.RI "Color \fBgamma\fP"
.br
.ti -1c
.RI "Color \fBgain\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBLinearWheelsSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Color UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LinearWheelsSettings\&.gain"

.SS "Color UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LinearWheelsSettings\&.gamma"

.SS "Color UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LinearWheelsSettings\&.lift"

.SH "Property Documentation"
.PP 
.SS "\fBLinearWheelsSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LinearWheelsSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
