.TH "UnityEngine.PostProcessing.GraphicsUtils" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.GraphicsUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBBlit\fP (Material material, int pass)"
.br
.ti -1c
.RI "static void \fBClearAndBlit\fP (Texture source, RenderTexture destination, Material material, int pass, bool clearColor=true, bool clearDepth=false)"
.br
.ti -1c
.RI "static void \fBDestroy\fP (\fBUnityObject\fP obj)"
.br
.ti -1c
.RI "static void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBisLinearColorSpace\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBsupportsDX11\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Texture2D \fBwhiteTexture\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Mesh \fBquad\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void UnityEngine\&.PostProcessing\&.GraphicsUtils\&.Blit (Material material, int pass)\fC [static]\fP"

.SS "static void UnityEngine\&.PostProcessing\&.GraphicsUtils\&.ClearAndBlit (Texture source, RenderTexture destination, Material material, int pass, bool clearColor = \fCtrue\fP, bool clearDepth = \fCfalse\fP)\fC [static]\fP"

.SS "static void UnityEngine\&.PostProcessing\&.GraphicsUtils\&.Destroy (\fBUnityObject\fP obj)\fC [static]\fP"

.SS "static void UnityEngine\&.PostProcessing\&.GraphicsUtils\&.Dispose ()\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "bool UnityEngine\&.PostProcessing\&.GraphicsUtils\&.isLinearColorSpace\fC [static]\fP, \fC [get]\fP"

.SS "Mesh UnityEngine\&.PostProcessing\&.GraphicsUtils\&.quad\fC [static]\fP, \fC [get]\fP"

.SS "bool UnityEngine\&.PostProcessing\&.GraphicsUtils\&.supportsDX11\fC [static]\fP, \fC [get]\fP"

.SS "Texture2D UnityEngine\&.PostProcessing\&.GraphicsUtils\&.whiteTexture\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
