.TH "UnityEngine.PostProcessing.ColorGradingModel.CurvesSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.CurvesSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColorGradingCurve\fP \fBmaster\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBred\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBgreen\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBblue\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBhueVShue\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBhueVSsat\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBsatVSsat\fP"
.br
.ti -1c
.RI "\fBColorGradingCurve\fP \fBlumVSsat\fP"
.br
.ti -1c
.RI "int \fBe_CurrentEditingCurve\fP"
.br
.ti -1c
.RI "bool \fBe_CurveY\fP"
.br
.ti -1c
.RI "bool \fBe_CurveR\fP"
.br
.ti -1c
.RI "bool \fBe_CurveG\fP"
.br
.ti -1c
.RI "bool \fBe_CurveB\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBCurvesSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.blue"

.SS "int UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.e_CurrentEditingCurve"

.SS "bool UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.e_CurveB"

.SS "bool UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.e_CurveG"

.SS "bool UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.e_CurveR"

.SS "bool UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.e_CurveY"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.green"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.hueVShue"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.hueVSsat"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.lumVSsat"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.master"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.red"

.SS "\fBColorGradingCurve\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.satVSsat"

.SH "Property Documentation"
.PP 
.SS "\fBCurvesSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.CurvesSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
