.TH "UnityEngine.PostProcessing.TrackballAttribute" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.TrackballAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackballAttribute\fP (string \fBmethod\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBmethod\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.PostProcessing\&.TrackballAttribute\&.TrackballAttribute (string method)"

.SH "Member Data Documentation"
.PP 
.SS "readonly string UnityEngine\&.PostProcessing\&.TrackballAttribute\&.method"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
