.TH "UnityEngine.InputSystem.Samples" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.Samples
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBInGameHints\fP"
.br
.ti -1c
.RI "namespace \fBRebindUI\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputActionVisualizer\fP"
.br
.RI "A component for debugging purposes that adds an on-screen display which shows activity on an input action over time (\fBInputActionVisualizer\&.Visualization\&.Interaction\fP) or an action's current value (\fBInputActionVisualizer\&.Visualization\&.Value\fP)\&. "
.ti -1c
.RI "class \fBInputControlVisualizer\fP"
.br
.RI "A component for debugging purposes that adds an on-screen display which shows activity on an input control over time\&. "
.ti -1c
.RI "class \fBInputVisualizer\fP"
.br
.RI "Base class for \fBInputActionVisualizer\fP and \fBInputControlVisualizer\fP\&. "
.ti -1c
.RI "class \fBVisualizationHelpers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
