.TH "UnityEngine.PostProcessing.PostProcessingContext" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingContext
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInterrupt\fP ()"
.br
.ti -1c
.RI "\fBPostProcessingContext\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPostProcessingProfile\fP \fBprofile\fP"
.br
.ti -1c
.RI "Camera \fBcamera\fP"
.br
.ti -1c
.RI "\fBMaterialFactory\fP \fBmaterialFactory\fP"
.br
.ti -1c
.RI "\fBRenderTextureFactory\fP \fBrenderTextureFactory\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBinterrupted\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisGBufferAvailable\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisHdr\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBwidth\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBheight\fP\fC [get]\fP"
.br
.ti -1c
.RI "Rect \fBviewport\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.PostProcessingContext\&.Interrupt ()"

.SS "\fBPostProcessingContext\fP UnityEngine\&.PostProcessing\&.PostProcessingContext\&.Reset ()"

.SH "Member Data Documentation"
.PP 
.SS "Camera UnityEngine\&.PostProcessing\&.PostProcessingContext\&.camera"

.SS "\fBMaterialFactory\fP UnityEngine\&.PostProcessing\&.PostProcessingContext\&.materialFactory"

.SS "\fBPostProcessingProfile\fP UnityEngine\&.PostProcessing\&.PostProcessingContext\&.profile"

.SS "\fBRenderTextureFactory\fP UnityEngine\&.PostProcessing\&.PostProcessingContext\&.renderTextureFactory"

.SH "Property Documentation"
.PP 
.SS "int UnityEngine\&.PostProcessing\&.PostProcessingContext\&.height\fC [get]\fP"

.SS "bool UnityEngine\&.PostProcessing\&.PostProcessingContext\&.interrupted\fC [get]\fP"

.SS "bool UnityEngine\&.PostProcessing\&.PostProcessingContext\&.isGBufferAvailable\fC [get]\fP"

.SS "bool UnityEngine\&.PostProcessing\&.PostProcessingContext\&.isHdr\fC [get]\fP"

.SS "Rect UnityEngine\&.PostProcessing\&.PostProcessingContext\&.viewport\fC [get]\fP"

.SS "int UnityEngine\&.PostProcessing\&.PostProcessingContext\&.width\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
