.TH "UnityEngine.PostProcessing.PostProcessingProfile" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBuiltinDebugViewsModel\fP \fBdebugViews\fP = new \fBBuiltinDebugViewsModel\fP()"
.br
.ti -1c
.RI "\fBFogModel\fP \fBfog\fP = new \fBFogModel\fP()"
.br
.ti -1c
.RI "\fBAntialiasingModel\fP \fBantialiasing\fP = new \fBAntialiasingModel\fP()"
.br
.ti -1c
.RI "\fBAmbientOcclusionModel\fP \fBambientOcclusion\fP = new \fBAmbientOcclusionModel\fP()"
.br
.ti -1c
.RI "\fBScreenSpaceReflectionModel\fP \fBscreenSpaceReflection\fP = new \fBScreenSpaceReflectionModel\fP()"
.br
.ti -1c
.RI "\fBDepthOfFieldModel\fP \fBdepthOfField\fP = new \fBDepthOfFieldModel\fP()"
.br
.ti -1c
.RI "\fBMotionBlurModel\fP \fBmotionBlur\fP = new \fBMotionBlurModel\fP()"
.br
.ti -1c
.RI "\fBEyeAdaptationModel\fP \fBeyeAdaptation\fP = new \fBEyeAdaptationModel\fP()"
.br
.ti -1c
.RI "\fBBloomModel\fP \fBbloom\fP = new \fBBloomModel\fP()"
.br
.ti -1c
.RI "\fBColorGradingModel\fP \fBcolorGrading\fP = new \fBColorGradingModel\fP()"
.br
.ti -1c
.RI "\fBUserLutModel\fP \fBuserLut\fP = new \fBUserLutModel\fP()"
.br
.ti -1c
.RI "\fBChromaticAberrationModel\fP \fBchromaticAberration\fP = new \fBChromaticAberrationModel\fP()"
.br
.ti -1c
.RI "\fBGrainModel\fP \fBgrain\fP = new \fBGrainModel\fP()"
.br
.ti -1c
.RI "\fBVignetteModel\fP \fBvignette\fP = new \fBVignetteModel\fP()"
.br
.ti -1c
.RI "\fBDitheringModel\fP \fBdithering\fP = new \fBDitheringModel\fP()"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBAmbientOcclusionModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.ambientOcclusion = new \fBAmbientOcclusionModel\fP()"

.SS "\fBAntialiasingModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.antialiasing = new \fBAntialiasingModel\fP()"

.SS "\fBBloomModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.bloom = new \fBBloomModel\fP()"

.SS "\fBChromaticAberrationModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.chromaticAberration = new \fBChromaticAberrationModel\fP()"

.SS "\fBColorGradingModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.colorGrading = new \fBColorGradingModel\fP()"

.SS "\fBBuiltinDebugViewsModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.debugViews = new \fBBuiltinDebugViewsModel\fP()"

.SS "\fBDepthOfFieldModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.depthOfField = new \fBDepthOfFieldModel\fP()"

.SS "\fBDitheringModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.dithering = new \fBDitheringModel\fP()"

.SS "\fBEyeAdaptationModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.eyeAdaptation = new \fBEyeAdaptationModel\fP()"

.SS "\fBFogModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.fog = new \fBFogModel\fP()"

.SS "\fBGrainModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.grain = new \fBGrainModel\fP()"

.SS "\fBMotionBlurModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.motionBlur = new \fBMotionBlurModel\fP()"

.SS "\fBScreenSpaceReflectionModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.screenSpaceReflection = new \fBScreenSpaceReflectionModel\fP()"

.SS "\fBUserLutModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.userLut = new \fBUserLutModel\fP()"

.SS "\fBVignetteModel\fP UnityEngine\&.PostProcessing\&.PostProcessingProfile\&.vignette = new \fBVignetteModel\fP()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
