.TH "UnityEngine.PostProcessing.EyeAdaptationModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.EyeAdaptationModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBlowPercent\fP"
.br
.ti -1c
.RI "float \fBhighPercent\fP"
.br
.ti -1c
.RI "float \fBminLuminance\fP"
.br
.ti -1c
.RI "float \fBmaxLuminance\fP"
.br
.ti -1c
.RI "float \fBkeyValue\fP"
.br
.ti -1c
.RI "bool \fBdynamicKeyValue\fP"
.br
.ti -1c
.RI "\fBEyeAdaptationType\fP \fBadaptationType\fP"
.br
.ti -1c
.RI "float \fBspeedUp\fP"
.br
.ti -1c
.RI "float \fBspeedDown\fP"
.br
.ti -1c
.RI "int \fBlogMin\fP"
.br
.ti -1c
.RI "int \fBlogMax\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBEyeAdaptationType\fP UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.adaptationType"

.SS "bool UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.dynamicKeyValue"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.highPercent"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.keyValue"

.SS "int UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.logMax"

.SS "int UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.logMin"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.lowPercent"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.maxLuminance"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.minLuminance"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.speedDown"

.SS "float UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.speedUp"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
