.TH "UnityEngine.PostProcessing.EyeAdaptationModel" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.EyeAdaptationModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSettings\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEyeAdaptationType\fP { \fBProgressive\fP, \fBFixed\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReset\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSettings\fP \fBsettings\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.EyeAdaptationType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIProgressive \fP\fP
.TP
\fB\fIFixed \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.Reset ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.EyeAdaptationModel\&.settings\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
