.TH "UnityEngine.InputSystem.Samples.VisualizationHelpers.RingBuffer< TValue >" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.Samples.VisualizationHelpers.RingBuffer< TValue >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingBuffer\fP (int size)"
.br
.ti -1c
.RI "ref TValue \fBAppend\fP (TValue value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TValue[] \fBarray\fP"
.br
.ti -1c
.RI "int \fBhead\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ref TValue \fBthis[int index]\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.RingBuffer\fP< TValue >\&.\fBRingBuffer\fP (int size)"

.SH "Member Function Documentation"
.PP 
.SS "ref TValue \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.RingBuffer\fP< TValue >\&.Append (TValue value)"

.SH "Member Data Documentation"
.PP 
.SS "TValue [] \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.RingBuffer\fP< TValue >\&.array"

.SS "int \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.RingBuffer\fP< TValue >\&.count"

.SS "int \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.RingBuffer\fP< TValue >\&.head"

.SH "Property Documentation"
.PP 
.SS "ref TValue \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.RingBuffer\fP< TValue >\&.this[int index]\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
