.TH "UnityEditor.PostProcessing.ReflectionUtils" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PostProcessing.ReflectionUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static FieldInfo \fBGetFieldInfoFromPath\fP (object source, string path)"
.br
.ti -1c
.RI "static string \fBGetFieldPath< T, TValue >\fP (Expression< Func< T, TValue > > expr)"
.br
.ti -1c
.RI "static object \fBGetFieldValue\fP (object source, string name)"
.br
.ti -1c
.RI "static object \fBGetFieldValueFromPath\fP (object source, ref Type baseType, string path)"
.br
.ti -1c
.RI "static object \fBGetParentObject\fP (string path, object obj)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static FieldInfo UnityEditor\&.PostProcessing\&.ReflectionUtils\&.GetFieldInfoFromPath (object source, string path)\fC [static]\fP"

.SS "static string UnityEditor\&.PostProcessing\&.ReflectionUtils\&.GetFieldPath< T, TValue > (Expression< Func< T, TValue > > expr)\fC [static]\fP"

.SS "static object UnityEditor\&.PostProcessing\&.ReflectionUtils\&.GetFieldValue (object source, string name)\fC [static]\fP"

.SS "static object UnityEditor\&.PostProcessing\&.ReflectionUtils\&.GetFieldValueFromPath (object source, ref Type baseType, string path)\fC [static]\fP"

.SS "static object UnityEditor\&.PostProcessing\&.ReflectionUtils\&.GetParentObject (string path, object obj)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
