.TH "UnityEngine.PostProcessing.ColorGradingModel.ColorWheelsSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.ColorWheelsSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColorWheelMode\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBLogWheelsSettings\fP \fBlog\fP"
.br
.ti -1c
.RI "\fBLinearWheelsSettings\fP \fBlinear\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBColorWheelsSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBLinearWheelsSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ColorWheelsSettings\&.linear"

.SS "\fBLogWheelsSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ColorWheelsSettings\&.log"

.SS "\fBColorWheelMode\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ColorWheelsSettings\&.mode"

.SH "Property Documentation"
.PP 
.SS "\fBColorWheelsSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ColorWheelsSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
