.TH "UnityEngine.InputSystem.Samples.RebindUI.GamepadIconsExample.GamepadIcons" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.Samples.RebindUI.GamepadIconsExample.GamepadIcons
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Sprite \fBGetSprite\fP (string controlPath)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBbuttonSouth\fP"
.br
.ti -1c
.RI "Sprite \fBbuttonNorth\fP"
.br
.ti -1c
.RI "Sprite \fBbuttonEast\fP"
.br
.ti -1c
.RI "Sprite \fBbuttonWest\fP"
.br
.ti -1c
.RI "Sprite \fBstartButton\fP"
.br
.ti -1c
.RI "Sprite \fBselectButton\fP"
.br
.ti -1c
.RI "Sprite \fBleftTrigger\fP"
.br
.ti -1c
.RI "Sprite \fBrightTrigger\fP"
.br
.ti -1c
.RI "Sprite \fBleftShoulder\fP"
.br
.ti -1c
.RI "Sprite \fBrightShoulder\fP"
.br
.ti -1c
.RI "Sprite \fBdpad\fP"
.br
.ti -1c
.RI "Sprite \fBdpadUp\fP"
.br
.ti -1c
.RI "Sprite \fBdpadDown\fP"
.br
.ti -1c
.RI "Sprite \fBdpadLeft\fP"
.br
.ti -1c
.RI "Sprite \fBdpadRight\fP"
.br
.ti -1c
.RI "Sprite \fBleftStick\fP"
.br
.ti -1c
.RI "Sprite \fBrightStick\fP"
.br
.ti -1c
.RI "Sprite \fBleftStickPress\fP"
.br
.ti -1c
.RI "Sprite \fBrightStickPress\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.GetSprite (string controlPath)"

.SH "Member Data Documentation"
.PP 
.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.buttonEast"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.buttonNorth"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.buttonSouth"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.buttonWest"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.dpad"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.dpadDown"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.dpadLeft"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.dpadRight"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.dpadUp"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.leftShoulder"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.leftStick"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.leftStickPress"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.leftTrigger"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.rightShoulder"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.rightStick"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.rightStickPress"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.rightTrigger"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.selectButton"

.SS "Sprite UnityEngine\&.InputSystem\&.Samples\&.RebindUI\&.GamepadIconsExample\&.GamepadIcons\&.startButton"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
