.TH "UnityEngine.PostProcessing.GetSetAttribute" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.GetSetAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetSetAttribute\fP (string \fBname\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBname\fP"
.br
.ti -1c
.RI "bool \fBdirty\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.PostProcessing\&.GetSetAttribute\&.GetSetAttribute (string name)"

.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.PostProcessing\&.GetSetAttribute\&.dirty"

.SS "readonly string UnityEngine\&.PostProcessing\&.GetSetAttribute\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
