.TH "UnityEngine.PostProcessing.BuiltinDebugViewsModel.MotionVectorsSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.BuiltinDebugViewsModel.MotionVectorsSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBsourceOpacity\fP"
.br
.ti -1c
.RI "float \fBmotionImageOpacity\fP"
.br
.ti -1c
.RI "float \fBmotionImageAmplitude\fP"
.br
.ti -1c
.RI "float \fBmotionVectorsOpacity\fP"
.br
.ti -1c
.RI "int \fBmotionVectorsResolution\fP"
.br
.ti -1c
.RI "float \fBmotionVectorsAmplitude\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBMotionVectorsSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.motionImageAmplitude"

.SS "float UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.motionImageOpacity"

.SS "float UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.motionVectorsAmplitude"

.SS "float UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.motionVectorsOpacity"

.SS "int UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.motionVectorsResolution"

.SS "float UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.sourceOpacity"

.SH "Property Documentation"
.PP 
.SS "\fBMotionVectorsSettings\fP UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.MotionVectorsSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
