.TH "UnityEngine.PostProcessing.BuiltinDebugViewsComponent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.BuiltinDebugViewsComponent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer< BuiltinDebugViewsModel >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override DepthTextureMode \fBGetCameraFlags\fP ()"
.br
.ti -1c
.RI "override CameraEvent \fBGetCameraEvent\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "override void \fBPopulateCommandBuffer\fP (CommandBuffer cb)"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override CameraEvent UnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\&.GetCameraEvent ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer< BuiltinDebugViewsModel >\fP\&.
.SS "override DepthTextureMode UnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\&.GetCameraFlags ()"

.SS "override string UnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\&.GetName ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer< BuiltinDebugViewsModel >\fP\&.
.SS "override void UnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\&.OnDisable ()"

.SS "override void UnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\&.PopulateCommandBuffer (CommandBuffer cb)\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer< BuiltinDebugViewsModel >\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool UnityEngine\&.PostProcessing\&.BuiltinDebugViewsComponent\&.active\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
