.TH "UnityEngine.PostProcessing.TaaComponent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.TaaComponent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< AntialiasingModel >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override DepthTextureMode \fBGetCameraFlags\fP ()"
.br
.ti -1c
.RI "void \fBResetHistory\fP ()"
.br
.ti -1c
.RI "void \fBSetProjectionMatrix\fP (Func< Vector2, Matrix4x4 > jitteredFunc)"
.br
.ti -1c
.RI "void \fBRender\fP (RenderTexture source, RenderTexture destination)"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override DepthTextureMode UnityEngine\&.PostProcessing\&.TaaComponent\&.GetCameraFlags ()"

.SS "override void UnityEngine\&.PostProcessing\&.TaaComponent\&.OnDisable ()"

.SS "void UnityEngine\&.PostProcessing\&.TaaComponent\&.Render (RenderTexture source, RenderTexture destination)"

.SS "void UnityEngine\&.PostProcessing\&.TaaComponent\&.ResetHistory ()"

.SS "void UnityEngine\&.PostProcessing\&.TaaComponent\&.SetProjectionMatrix (Func< Vector2, Matrix4x4 > jitteredFunc)"

.SH "Property Documentation"
.PP 
.SS "override bool UnityEngine\&.PostProcessing\&.TaaComponent\&.active\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
