.TH "UnityEngine.InputSystem.InputRecorder.ChangeEvent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.InputRecorder.ChangeEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< Change >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
