.TH "UnityEngine.PostProcessing.VignetteModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.VignetteModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMode\fP \fBmode\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP"
.br
.ti -1c
.RI "Vector2 \fBcenter\fP"
.br
.ti -1c
.RI "float \fBintensity\fP"
.br
.ti -1c
.RI "float \fBsmoothness\fP"
.br
.ti -1c
.RI "float \fBroundness\fP"
.br
.ti -1c
.RI "Texture \fBmask\fP"
.br
.ti -1c
.RI "float \fBopacity\fP"
.br
.ti -1c
.RI "bool \fBrounded\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Vector2 UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.center"

.SS "Color UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.color"

.SS "float UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.intensity"

.SS "Texture UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.mask"

.SS "\fBMode\fP UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.mode"

.SS "float UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.opacity"

.SS "bool UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.rounded"

.SS "float UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.roundness"

.SS "float UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.smoothness"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.VignetteModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
