.TH "UnityEngine.PostProcessing.AntialiasingModel.FxaaQualitySettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.AntialiasingModel.FxaaQualitySettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBsubpixelAliasingRemovalAmount\fP"
.br
.ti -1c
.RI "float \fBedgeDetectionThreshold\fP"
.br
.ti -1c
.RI "float \fBminimumRequiredLuminance\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBFxaaQualitySettings\fP[] \fBpresets\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.PostProcessing\&.AntialiasingModel\&.FxaaQualitySettings\&.edgeDetectionThreshold"

.SS "float UnityEngine\&.PostProcessing\&.AntialiasingModel\&.FxaaQualitySettings\&.minimumRequiredLuminance"

.SS "\fBFxaaQualitySettings\fP [] UnityEngine\&.PostProcessing\&.AntialiasingModel\&.FxaaQualitySettings\&.presets\fC [static]\fP"

.SS "float UnityEngine\&.PostProcessing\&.AntialiasingModel\&.FxaaQualitySettings\&.subpixelAliasingRemovalAmount"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
