.TH "UnityEngine.PostProcessing.PostProcessingBehaviour" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingBehaviour
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBResetTemporalEffects\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPostProcessingProfile\fP \fBprofile\fP"
.br
.ti -1c
.RI "Func< Vector2, Matrix4x4 > \fBjitteredMatrixFunc\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.PostProcessingBehaviour\&.ResetTemporalEffects ()"

.SH "Member Data Documentation"
.PP 
.SS "Func<Vector2, Matrix4x4> UnityEngine\&.PostProcessing\&.PostProcessingBehaviour\&.jitteredMatrixFunc"

.SS "\fBPostProcessingProfile\fP UnityEngine\&.PostProcessing\&.PostProcessingBehaviour\&.profile"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
