.TH "UnityEngine.PostProcessing.PostProcessingModel" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingModel
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEngine\&.PostProcessing\&.AmbientOcclusionModel\fP, \fBUnityEngine\&.PostProcessing\&.AntialiasingModel\fP, \fBUnityEngine\&.PostProcessing\&.BloomModel\fP, \fBUnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\fP, \fBUnityEngine\&.PostProcessing\&.ChromaticAberrationModel\fP, \fBUnityEngine\&.PostProcessing\&.ColorGradingModel\fP, \fBUnityEngine\&.PostProcessing\&.DepthOfFieldModel\fP, \fBUnityEngine\&.PostProcessing\&.DitheringModel\fP, \fBUnityEngine\&.PostProcessing\&.EyeAdaptationModel\fP, \fBUnityEngine\&.PostProcessing\&.FogModel\fP, \fBUnityEngine\&.PostProcessing\&.GrainModel\fP, \fBUnityEngine\&.PostProcessing\&.MotionBlurModel\fP, \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\fP, \fBUnityEngine\&.PostProcessing\&.UserLutModel\fP, and \fBUnityEngine\&.PostProcessing\&.VignetteModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBReset\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnValidate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void UnityEngine\&.PostProcessing\&.PostProcessingModel\&.OnValidate ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.PostProcessing\&.ColorGradingModel\fP\&.
.SS "abstract void UnityEngine\&.PostProcessing\&.PostProcessingModel\&.Reset ()\fC [pure virtual]\fP"

.PP
Implemented in \fBUnityEngine\&.PostProcessing\&.AmbientOcclusionModel\fP, \fBUnityEngine\&.PostProcessing\&.AntialiasingModel\fP, \fBUnityEngine\&.PostProcessing\&.BloomModel\fP, \fBUnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\fP, \fBUnityEngine\&.PostProcessing\&.ChromaticAberrationModel\fP, \fBUnityEngine\&.PostProcessing\&.ColorGradingModel\fP, \fBUnityEngine\&.PostProcessing\&.DepthOfFieldModel\fP, \fBUnityEngine\&.PostProcessing\&.DitheringModel\fP, \fBUnityEngine\&.PostProcessing\&.EyeAdaptationModel\fP, \fBUnityEngine\&.PostProcessing\&.FogModel\fP, \fBUnityEngine\&.PostProcessing\&.GrainModel\fP, \fBUnityEngine\&.PostProcessing\&.MotionBlurModel\fP, \fBUnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\fP, \fBUnityEngine\&.PostProcessing\&.UserLutModel\fP, and \fBUnityEngine\&.PostProcessing\&.VignetteModel\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool UnityEngine\&.PostProcessing\&.PostProcessingModel\&.enabled\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
