.TH "UnityEngine.PostProcessing.PostProcessingComponentRenderTexture< T >" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingComponentRenderTexture< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBPrepare\fP (Material material)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "virtual void \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture\fP< T >\&.Prepare (Material material)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.PostProcessing\&.ChromaticAberrationComponent\fP, \fBUnityEngine\&.PostProcessing\&.ColorGradingComponent\fP, \fBUnityEngine\&.PostProcessing\&.DitheringComponent\fP, \fBUnityEngine\&.PostProcessing\&.GrainComponent\fP, \fBUnityEngine\&.PostProcessing\&.UserLutComponent\fP, and \fBUnityEngine\&.PostProcessing\&.VignetteComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
