.TH "UnityEngine.PostProcessing.PostProcessingComponent< T >" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingComponent< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentBase\fP\&.
.PP
Inherited by \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentCommandBuffer< T >\fP, and \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP (\fBPostProcessingContext\fP pcontext, T pmodel)"
.br
.ti -1c
.RI "override \fBPostProcessingModel\fP \fBGetModel\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBmodel\fP\fC [getset]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override \fBPostProcessingModel\fP \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent\fP< T >\&.GetModel ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentBase\fP\&.
.SS "virtual void \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent\fP< T >\&.Init (\fBPostProcessingContext\fP pcontext, T pmodel)\fC [virtual]\fP"

.SH "Property Documentation"
.PP 
.SS "T \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent\fP< T >\&.model\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
