.TH "UnityEditor.PostProcessing.PostProcessingModelEditorAttribute" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PostProcessing.PostProcessingModelEditorAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPostProcessingModelEditorAttribute\fP (Type \fBtype\fP, bool \fBalwaysEnabled\fP=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Type \fBtype\fP"
.br
.ti -1c
.RI "readonly bool \fBalwaysEnabled\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.PostProcessing\&.PostProcessingModelEditorAttribute\&.PostProcessingModelEditorAttribute (Type type, bool alwaysEnabled = \fCfalse\fP)"

.SH "Member Data Documentation"
.PP 
.SS "readonly bool UnityEditor\&.PostProcessing\&.PostProcessingModelEditorAttribute\&.alwaysEnabled"

.SS "readonly Type UnityEditor\&.PostProcessing\&.PostProcessingModelEditorAttribute\&.type"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
