.TH "UnityEngine.PostProcessing.RenderTextureFactory" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.RenderTextureFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderTextureFactory\fP ()"
.br
.ti -1c
.RI "RenderTexture \fBGet\fP (RenderTexture baseRenderTexture)"
.br
.ti -1c
.RI "RenderTexture \fBGet\fP (int width, int height, int depthBuffer=0, RenderTextureFormat format=RenderTextureFormat\&.ARGBHalf, RenderTextureReadWrite rw=RenderTextureReadWrite\&.Default, FilterMode filterMode=FilterMode\&.Bilinear, TextureWrapMode wrapMode=TextureWrapMode\&.Clamp, string name='FactoryTempTexture')"
.br
.ti -1c
.RI "void \fBRelease\fP (RenderTexture rt)"
.br
.ti -1c
.RI "void \fBReleaseAll\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.PostProcessing\&.RenderTextureFactory\&.RenderTextureFactory ()"

.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.RenderTextureFactory\&.Dispose ()"

.SS "RenderTexture UnityEngine\&.PostProcessing\&.RenderTextureFactory\&.Get (int width, int height, int depthBuffer = \fC0\fP, RenderTextureFormat format = \fCRenderTextureFormat\&.ARGBHalf\fP, RenderTextureReadWrite rw = \fCRenderTextureReadWrite\&.Default\fP, FilterMode filterMode = \fCFilterMode\&.Bilinear\fP, TextureWrapMode wrapMode = \fCTextureWrapMode\&.Clamp\fP, string name = \fC'FactoryTempTexture'\fP)"

.SS "RenderTexture UnityEngine\&.PostProcessing\&.RenderTextureFactory\&.Get (RenderTexture baseRenderTexture)"

.SS "void UnityEngine\&.PostProcessing\&.RenderTextureFactory\&.Release (RenderTexture rt)"

.SS "void UnityEngine\&.PostProcessing\&.RenderTextureFactory\&.ReleaseAll ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
