.TH "UnityEngine.PostProcessing.PostProcessingComponentBase" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.PostProcessingComponentBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual DepthTextureMode \fBGetCameraFlags\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "abstract \fBPostProcessingModel\fP \fBGetModel\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPostProcessingContext\fP \fBcontext\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "abstract bool \fBactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual DepthTextureMode UnityEngine\&.PostProcessing\&.PostProcessingComponentBase\&.GetCameraFlags ()\fC [virtual]\fP"

.SS "abstract \fBPostProcessingModel\fP UnityEngine\&.PostProcessing\&.PostProcessingComponentBase\&.GetModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBUnityEngine\&.PostProcessing\&.PostProcessingComponent< T >\fP\&.
.SS "virtual void UnityEngine\&.PostProcessing\&.PostProcessingComponentBase\&.OnDisable ()\fC [virtual]\fP"

.SS "virtual void UnityEngine\&.PostProcessing\&.PostProcessingComponentBase\&.OnEnable ()\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBPostProcessingContext\fP UnityEngine\&.PostProcessing\&.PostProcessingComponentBase\&.context"

.SH "Property Documentation"
.PP 
.SS "abstract bool UnityEngine\&.PostProcessing\&.PostProcessingComponentBase\&.active\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
