.TH "UnityEngine.PostProcessing.ColorGradingModel.LogWheelsSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.LogWheelsSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBslope\fP"
.br
.ti -1c
.RI "Color \fBpower\fP"
.br
.ti -1c
.RI "Color \fBoffset\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBLogWheelsSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Color UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LogWheelsSettings\&.offset"

.SS "Color UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LogWheelsSettings\&.power"

.SS "Color UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LogWheelsSettings\&.slope"

.SH "Property Documentation"
.PP 
.SS "\fBLogWheelsSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.LogWheelsSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
