.TH "UnityEngine.PostProcessing.DepthOfFieldComponent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.DepthOfFieldComponent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< DepthOfFieldModel >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override DepthTextureMode \fBGetCameraFlags\fP ()"
.br
.ti -1c
.RI "void \fBPrepare\fP (RenderTexture source, Material uberMaterial, bool antialiasCoC)"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override DepthTextureMode UnityEngine\&.PostProcessing\&.DepthOfFieldComponent\&.GetCameraFlags ()"

.SS "override void UnityEngine\&.PostProcessing\&.DepthOfFieldComponent\&.OnDisable ()"

.SS "void UnityEngine\&.PostProcessing\&.DepthOfFieldComponent\&.Prepare (RenderTexture source, Material uberMaterial, bool antialiasCoC)"

.SH "Property Documentation"
.PP 
.SS "override bool UnityEngine\&.PostProcessing\&.DepthOfFieldComponent\&.active\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
