.TH "UnityEngine.PostProcessing.ColorGradingCurve" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingCurve
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorGradingCurve\fP (AnimationCurve \fBcurve\fP, float zeroValue, bool loop, Vector2 bounds)"
.br
.ti -1c
.RI "void \fBCache\fP ()"
.br
.ti -1c
.RI "float \fBEvaluate\fP (float t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AnimationCurve \fBcurve\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.PostProcessing\&.ColorGradingCurve\&.ColorGradingCurve (AnimationCurve curve, float zeroValue, bool loop, Vector2 bounds)"

.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.ColorGradingCurve\&.Cache ()"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingCurve\&.Evaluate (float t)"

.SH "Member Data Documentation"
.PP 
.SS "AnimationCurve UnityEngine\&.PostProcessing\&.ColorGradingCurve\&.curve"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
