.TH "UnityEngine.InputSystem.Samples.VisualizationHelpers.ScalarVisualizer< TValue >" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.Samples.VisualizationHelpers.ScalarVisualizer< TValue >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ValueVisualizer< TValue >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScalarVisualizer\fP (int numSamples=10)"
.br
.ti -1c
.RI "override void \fBOnDraw\fP (Rect rect)"
.br
.ti -1c
.RI "override void \fBAddSample\fP (object value, double time)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TValue \fBlimitMin\fP"
.br
.ti -1c
.RI "TValue \fBlimitMax\fP"
.br
.ti -1c
.RI "TValue \fBmin\fP"
.br
.ti -1c
.RI "TValue \fBmax\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.\fBScalarVisualizer\fP (int numSamples = \fC10\fP)"

.SH "Member Function Documentation"
.PP 
.SS "override void \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.AddSample (object value, double time)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ValueVisualizer< TValue >\fP\&.
.SS "override void \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.OnDraw (Rect rect)\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.Visualizer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "TValue \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.limitMax"

.SS "TValue \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.limitMin"

.SS "TValue \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.max"

.SS "TValue \fBUnityEngine\&.InputSystem\&.Samples\&.VisualizationHelpers\&.ScalarVisualizer\fP< TValue >\&.min"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
