.TH "UnityEngine.PostProcessing.MaterialFactory" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.MaterialFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterialFactory\fP ()"
.br
.ti -1c
.RI "Material \fBGet\fP (string shaderName)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.PostProcessing\&.MaterialFactory\&.MaterialFactory ()"

.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.MaterialFactory\&.Dispose ()"

.SS "Material UnityEngine\&.PostProcessing\&.MaterialFactory\&.Get (string shaderName)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
