.TH "UnityEngine.PostProcessing.DitheringComponent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.DitheringComponent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< DitheringModel >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBPrepare\fP (Material uberMaterial)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.PostProcessing\&.DitheringComponent\&.OnDisable ()"

.SS "override void UnityEngine\&.PostProcessing\&.DitheringComponent\&.Prepare (Material uberMaterial)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< DitheringModel >\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool UnityEngine\&.PostProcessing\&.DitheringComponent\&.active\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
