.TH "UnityEngine.PostProcessing.ColorGradingModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTonemappingSettings\fP \fBtonemapping\fP"
.br
.ti -1c
.RI "\fBBasicSettings\fP \fBbasic\fP"
.br
.ti -1c
.RI "\fBChannelMixerSettings\fP \fBchannelMixer\fP"
.br
.ti -1c
.RI "\fBColorWheelsSettings\fP \fBcolorWheels\fP"
.br
.ti -1c
.RI "\fBCurvesSettings\fP \fBcurves\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBBasicSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.Settings\&.basic"

.SS "\fBChannelMixerSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.Settings\&.channelMixer"

.SS "\fBColorWheelsSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.Settings\&.colorWheels"

.SS "\fBCurvesSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.Settings\&.curves"

.SS "\fBTonemappingSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.Settings\&.tonemapping"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
