.TH "UnityEngine.PostProcessing.AmbientOcclusionModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.AmbientOcclusionModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBintensity\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "\fBSampleCount\fP \fBsampleCount\fP"
.br
.ti -1c
.RI "bool \fBdownsampling\fP"
.br
.ti -1c
.RI "bool \fBforceForwardCompatibility\fP"
.br
.ti -1c
.RI "bool \fBambientOnly\fP"
.br
.ti -1c
.RI "bool \fBhighPrecision\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.ambientOnly"

.SS "bool UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.downsampling"

.SS "bool UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.forceForwardCompatibility"

.SS "bool UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.highPrecision"

.SS "float UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.intensity"

.SS "float UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.radius"

.SS "\fBSampleCount\fP UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.sampleCount"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
