.TH "UnityEngine.PostProcessing.UserLutComponent" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.UserLutComponent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< UserLutModel >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPrepare\fP (Material uberMaterial)"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.PostProcessing\&.UserLutComponent\&.OnGUI ()"

.SS "override void UnityEngine\&.PostProcessing\&.UserLutComponent\&.Prepare (Material uberMaterial)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.PostProcessing\&.PostProcessingComponentRenderTexture< UserLutModel >\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool UnityEngine\&.PostProcessing\&.UserLutComponent\&.active\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
