.TH "UnityEngine.PostProcessing.MotionBlurModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.MotionBlurModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBshutterAngle\fP"
.br
.ti -1c
.RI "int \fBsampleCount\fP"
.br
.ti -1c
.RI "float \fBframeBlending\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.PostProcessing\&.MotionBlurModel\&.Settings\&.frameBlending"

.SS "int UnityEngine\&.PostProcessing\&.MotionBlurModel\&.Settings\&.sampleCount"

.SS "float UnityEngine\&.PostProcessing\&.MotionBlurModel\&.Settings\&.shutterAngle"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.MotionBlurModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
