.TH "UnityEngine.PostProcessing.ColorGradingModel.BasicSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.BasicSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBpostExposure\fP"
.br
.ti -1c
.RI "float \fBtemperature\fP"
.br
.ti -1c
.RI "float \fBtint\fP"
.br
.ti -1c
.RI "float \fBhueShift\fP"
.br
.ti -1c
.RI "float \fBsaturation\fP"
.br
.ti -1c
.RI "float \fBcontrast\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBBasicSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.contrast"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.hueShift"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.postExposure"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.saturation"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.temperature"

.SS "float UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.tint"

.SH "Property Documentation"
.PP 
.SS "\fBBasicSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.BasicSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
