.TH "UnityEngine.PostProcessing.AmbientOcclusionModel" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.AmbientOcclusionModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSettings\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSampleCount\fP { \fBLowest\fP = 3, \fBLow\fP = 6, \fBMedium\fP = 10, \fBHigh\fP = 16 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReset\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSettings\fP \fBsettings\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.SampleCount\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILowest \fP\fP
.TP
\fB\fILow \fP\fP
.TP
\fB\fIMedium \fP\fP
.TP
\fB\fIHigh \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.Reset ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.AmbientOcclusionModel\&.settings\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
