.TH "UnityEngine.InputSystem" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSamples\fP"
.br
.ti -1c
.RI "namespace \fBUI\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputRecorder\fP"
.br
.RI "A wrapper component around InputEventTrace that provides an easy interface for recording input from a GameObject\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
