.TH "UnityEngine.PostProcessing.ScreenSpaceReflectionModel.ReflectionSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ScreenSpaceReflectionModel.ReflectionSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSSRReflectionBlendType\fP \fBblendType\fP"
.br
.ti -1c
.RI "\fBSSRResolution\fP \fBreflectionQuality\fP"
.br
.ti -1c
.RI "float \fBmaxDistance\fP"
.br
.ti -1c
.RI "int \fBiterationCount\fP"
.br
.RI "REFLECTIONS\&. "
.ti -1c
.RI "int \fBstepSize\fP"
.br
.ti -1c
.RI "float \fBwidthModifier\fP"
.br
.ti -1c
.RI "float \fBreflectionBlur\fP"
.br
.ti -1c
.RI "bool \fBreflectBackfaces\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBSSRReflectionBlendType\fP UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.blendType"

.SS "int UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.iterationCount"

.PP
REFLECTIONS\&. 
.SS "float UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.maxDistance"

.SS "bool UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.reflectBackfaces"

.SS "float UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.reflectionBlur"

.SS "\fBSSRResolution\fP UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.reflectionQuality"

.SS "int UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.stepSize"

.SS "float UnityEngine\&.PostProcessing\&.ScreenSpaceReflectionModel\&.ReflectionSettings\&.widthModifier"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
