.TH "UnityEngine.PostProcessing.AntialiasingModel" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.AntialiasingModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFxaaConsoleSettings\fP"
.br
.ti -1c
.RI "struct \fBFxaaQualitySettings\fP"
.br
.ti -1c
.RI "struct \fBFxaaSettings\fP"
.br
.ti -1c
.RI "struct \fBSettings\fP"
.br
.ti -1c
.RI "struct \fBTaaSettings\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMethod\fP { \fBFxaa\fP, \fBTaa\fP }"
.br
.ti -1c
.RI "enum \fBFxaaPreset\fP { \fBExtremePerformance\fP, \fBPerformance\fP, \fBDefault\fP, \fBQuality\fP, \fBExtremeQuality\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReset\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSettings\fP \fBsettings\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.PostProcessing\&.AntialiasingModel\&.FxaaPreset\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIExtremePerformance \fP\fP
.TP
\fB\fIPerformance \fP\fP
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIQuality \fP\fP
.TP
\fB\fIExtremeQuality \fP\fP
.SS "enum \fBUnityEngine\&.PostProcessing\&.AntialiasingModel\&.Method\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFxaa \fP\fP
.TP
\fB\fITaa \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.PostProcessing\&.AntialiasingModel\&.Reset ()\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.PostProcessing\&.PostProcessingModel\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.AntialiasingModel\&.settings\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
