.TH "UnityEngine.InputSystem.Samples.InGameHints.InGameHintsExample" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.Samples.InGameHints.InGameHintsExample
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnControlsChanged\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBhelpText\fP"
.br
.ti -1c
.RI "float \fBmoveSpeed\fP"
.br
.ti -1c
.RI "float \fBrotateSpeed\fP"
.br
.ti -1c
.RI "float \fBthrowForce\fP"
.br
.ti -1c
.RI "float \fBpickupDistance\fP"
.br
.ti -1c
.RI "float \fBholdDistance\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.Awake ()"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.OnControlsChanged ()"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.OnEnable ()"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.Update ()"

.SH "Member Data Documentation"
.PP 
.SS "Text UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.helpText"

.SS "float UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.holdDistance"

.SS "float UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.moveSpeed"

.SS "float UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.pickupDistance"

.SS "float UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.rotateSpeed"

.SS "float UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsExample\&.throwForce"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
