.TH "UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.IGameplayActions" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.IGameplayActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnMove\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnLook\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnPickUp\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnDrop\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnThrow\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsActions\&.IGameplayActions\&.OnDrop (InputAction\&.CallbackContext context)"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsActions\&.IGameplayActions\&.OnLook (InputAction\&.CallbackContext context)"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsActions\&.IGameplayActions\&.OnMove (InputAction\&.CallbackContext context)"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsActions\&.IGameplayActions\&.OnPickUp (InputAction\&.CallbackContext context)"

.SS "void UnityEngine\&.InputSystem\&.Samples\&.InGameHints\&.InGameHintsActions\&.IGameplayActions\&.OnThrow (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
