.TH "UnityEngine.PostProcessing.ColorGradingModel.ChannelMixerSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.ColorGradingModel.ChannelMixerSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBred\fP"
.br
.ti -1c
.RI "Vector3 \fBgreen\fP"
.br
.ti -1c
.RI "Vector3 \fBblue\fP"
.br
.ti -1c
.RI "int \fBcurrentEditingChannel\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBChannelMixerSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Vector3 UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ChannelMixerSettings\&.blue"

.SS "int UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ChannelMixerSettings\&.currentEditingChannel"

.SS "Vector3 UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ChannelMixerSettings\&.green"

.SS "Vector3 UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ChannelMixerSettings\&.red"

.SH "Property Documentation"
.PP 
.SS "\fBChannelMixerSettings\fP UnityEngine\&.PostProcessing\&.ColorGradingModel\&.ChannelMixerSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
