.TH "UnityEngine.PostProcessing.BuiltinDebugViewsModel.Settings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.BuiltinDebugViewsModel.Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMode\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBDepthSettings\fP \fBdepth\fP"
.br
.ti -1c
.RI "\fBMotionVectorsSettings\fP \fBmotionVectors\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBDepthSettings\fP UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.Settings\&.depth"

.SS "\fBMode\fP UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.Settings\&.mode"

.SS "\fBMotionVectorsSettings\fP UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.Settings\&.motionVectors"

.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP UnityEngine\&.PostProcessing\&.BuiltinDebugViewsModel\&.Settings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
