.TH "UnityEngine.PostProcessing.BloomModel.BloomSettings" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.PostProcessing.BloomModel.BloomSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBintensity\fP"
.br
.ti -1c
.RI "float \fBthreshold\fP"
.br
.ti -1c
.RI "float \fBsoftKnee\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "bool \fBantiFlicker\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBthresholdLinear\fP\fC [getset]\fP"
.br
.ti -1c
.RI "static \fBBloomSettings\fP \fBdefaultSettings\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.antiFlicker"

.SS "float UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.intensity"

.SS "float UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.radius"

.SS "float UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.softKnee"

.SS "float UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.threshold"

.SH "Property Documentation"
.PP 
.SS "\fBBloomSettings\fP UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.defaultSettings\fC [static]\fP, \fC [get]\fP"

.SS "float UnityEngine\&.PostProcessing\&.BloomModel\&.BloomSettings\&.thresholdLinear\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
