.TH "UpgradeDatabase" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpgradeDatabase
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerUpgrades\fP \fBGetUpgradeReference\fP (string upgradeID)"
.br
.ti -1c
.RI "\fBPlayerUpgrades\fP \fBGetUpgradeCopy\fP (string upgradeID)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBPlayerUpgrades\fP UpgradeDatabase\&.GetUpgradeCopy (string upgradeID)"

.SS "\fBPlayerUpgrades\fP UpgradeDatabase\&.GetUpgradeReference (string upgradeID)"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
