.TH "UpgradeSaveData" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpgradeSaveData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUpgradeSaveData\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBUpgradeID\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UpgradeSaveData\&.UpgradeSaveData (string id)"

.SH "Member Data Documentation"
.PP 
.SS "string UpgradeSaveData\&.UpgradeID"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
