.TH "UpgradeSaveIO" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpgradeSaveIO
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSaveUpgrades\fP (\fBInstalledUpgradeSaveData\fP upgrade, string filename)"
.br
.ti -1c
.RI "static \fBInstalledUpgradeSaveData\fP \fBLoadUpgrades\fP (string filename)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBInstalledUpgradeSaveData\fP UpgradeSaveIO\&.LoadUpgrades (string filename)\fC [static]\fP"

.SS "static void UpgradeSaveIO\&.SaveUpgrades (\fBInstalledUpgradeSaveData\fP upgrade, string filename)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
