.TH "UpgradeHolder" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpgradeHolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerSkills\fP \fBGetPlayerSkills\fP ()"
.br
.ti -1c
.RI "\fBstorage\fP \fBGetStorage\fP ()"
.br
.ti -1c
.RI "\fBTurbine\fP[] \fBGetTurbineUpgrades\fP ()"
.br
.ti -1c
.RI "\fBWeapon\fP[] \fBGetWeaponUpgrades\fP ()"
.br
.ti -1c
.RI "\fBHull\fP[] \fBGetHullUpgrades\fP ()"
.br
.ti -1c
.RI "\fBSelfRepair\fP[] \fBGetSelfRepairUpgrades\fP ()"
.br
.ti -1c
.RI "\fBOxygenTank\fP[] \fBGetOxygenTankUpgrades\fP ()"
.br
.ti -1c
.RI "\fBInventory\fP[] \fBGetInventoryUpgrades\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTurbine\fP \fBTurbineUpgrade\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBWeapon\fP \fBWeaponUpgrade\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBHull\fP \fBHullUpgrade\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBSelfRepair\fP \fBSelfRepairUpgrade\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBOxygenTank\fP \fBOxygenTankUpgrade\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBInventory\fP \fBInventoryUpgrade\fP\fC [getset]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBHull\fP[] UpgradeHolder\&.GetHullUpgrades ()"

.SS "\fBInventory\fP[] UpgradeHolder\&.GetInventoryUpgrades ()"

.SS "\fBOxygenTank\fP[] UpgradeHolder\&.GetOxygenTankUpgrades ()"

.SS "\fBPlayerSkills\fP UpgradeHolder\&.GetPlayerSkills ()"

.SS "\fBSelfRepair\fP[] UpgradeHolder\&.GetSelfRepairUpgrades ()"

.SS "\fBstorage\fP UpgradeHolder\&.GetStorage ()"

.SS "\fBTurbine\fP[] UpgradeHolder\&.GetTurbineUpgrades ()"

.SS "\fBWeapon\fP[] UpgradeHolder\&.GetWeaponUpgrades ()"

.SH "Property Documentation"
.PP 
.SS "\fBHull\fP UpgradeHolder\&.HullUpgrade\fC [get]\fP, \fC [set]\fP"

.SS "\fBInventory\fP UpgradeHolder\&.InventoryUpgrade\fC [get]\fP, \fC [set]\fP"

.SS "\fBOxygenTank\fP UpgradeHolder\&.OxygenTankUpgrade\fC [get]\fP, \fC [set]\fP"

.SS "\fBSelfRepair\fP UpgradeHolder\&.SelfRepairUpgrade\fC [get]\fP, \fC [set]\fP"

.SS "\fBTurbine\fP UpgradeHolder\&.TurbineUpgrade\fC [get]\fP, \fC [set]\fP"

.SS "\fBWeapon\fP UpgradeHolder\&.WeaponUpgrade\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
