.TH "Vector3Common" 3 "Sun Dec 12 2021" "10,000 meters below" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector3Common
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBGetForwardSpeed\fP (Vector3 velocity)"
.br
.ti -1c
.RI "static float \fBGetAbsForwardSpeed\fP (Vector3 velocity)"
.br
.ti -1c
.RI "static Vector3 \fBGetDirectionFrom2Pos\fP (Vector3 origin, Vector3 target)"
.br
.ti -1c
.RI "static bool \fBisZero\fP (this float value)"
.br
.RI "Checks whether value is near to zero within a tolerance\&. "
.ti -1c
.RI "static Vector3 \fBonlyX\fP (this Vector3 vector3)"
.br
.RI "Returns a copy of given vector with only X component of the vector\&. "
.ti -1c
.RI "static Vector3 \fBonlyY\fP (this Vector3 vector3)"
.br
.RI "Returns a copy of given vector with only Y component of the vector\&. "
.ti -1c
.RI "static Vector3 \fBonlyZ\fP (this Vector3 vector3)"
.br
.RI "Returns a copy of given vector with only Z component of the vector\&. "
.ti -1c
.RI "static Vector3 \fBonlyXZ\fP (this Vector3 vector3)"
.br
.RI "Returns a copy of given vector with only X and Z components of the vector\&. "
.ti -1c
.RI "static bool \fBisZero\fP (this Vector3 vector3)"
.br
.RI "Checks whether vector is near to zero within a tolerance\&. "
.ti -1c
.RI "static bool \fBisExceeding\fP (this Vector3 vector3, float magnitude)"
.br
.RI "Checks whether vector is exceeding the magnitude within a small error tolerance\&. "
.ti -1c
.RI "static Vector3 \fBnormalized\fP (this Vector3 vector3, out float magnitude)"
.br
.RI "Returns a copy of given vector with a magnitude of 1, and outs its magnitude before normalization\&. "
.ti -1c
.RI "static Vector3 \fBclamped\fP (this Vector3 vector3, out float magnitude)"
.br
.RI "Returns a copy of given vector with its magnitude clamped to 0 and 1, and outs its magnitude before clamp\&. "
.ti -1c
.RI "static Vector3 \fBclampedTo\fP (this Vector3 vector3, float maxLength)"
.br
.RI "Returns a copy of given vector with its magnitude clamped to maxLength\&. "
.ti -1c
.RI "static Vector3 \fBrelativeTo\fP (this Vector3 vector3, Transform target, bool onlyLateral=true)"
.br
.RI "Transform a given vector to be relative to target transform\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static Vector3 Vector3Common\&.clamped (this Vector3 vector3, out float magnitude)\fC [static]\fP"

.PP
Returns a copy of given vector with its magnitude clamped to 0 and 1, and outs its magnitude before clamp\&. 
.SS "static Vector3 Vector3Common\&.clampedTo (this Vector3 vector3, float maxLength)\fC [static]\fP"

.PP
Returns a copy of given vector with its magnitude clamped to maxLength\&. 
.SS "static float Vector3Common\&.GetAbsForwardSpeed (Vector3 velocity)\fC [static]\fP"

.SS "static Vector3 Vector3Common\&.GetDirectionFrom2Pos (Vector3 origin, Vector3 target)\fC [static]\fP"

.SS "static float Vector3Common\&.GetForwardSpeed (Vector3 velocity)\fC [static]\fP"

.SS "static bool Vector3Common\&.isExceeding (this Vector3 vector3, float magnitude)\fC [static]\fP"

.PP
Checks whether vector is exceeding the magnitude within a small error tolerance\&. 
.SS "static bool Vector3Common\&.isZero (this float value)\fC [static]\fP"

.PP
Checks whether value is near to zero within a tolerance\&. 
.SS "static bool Vector3Common\&.isZero (this Vector3 vector3)\fC [static]\fP"

.PP
Checks whether vector is near to zero within a tolerance\&. 
.SS "static Vector3 Vector3Common\&.normalized (this Vector3 vector3, out float magnitude)\fC [static]\fP"

.PP
Returns a copy of given vector with a magnitude of 1, and outs its magnitude before normalization\&. If the vector is too small to be normalized a zero vector will be returned\&. 
.SS "static Vector3 Vector3Common\&.onlyX (this Vector3 vector3)\fC [static]\fP"

.PP
Returns a copy of given vector with only X component of the vector\&. 
.SS "static Vector3 Vector3Common\&.onlyXZ (this Vector3 vector3)\fC [static]\fP"

.PP
Returns a copy of given vector with only X and Z components of the vector\&. 
.SS "static Vector3 Vector3Common\&.onlyY (this Vector3 vector3)\fC [static]\fP"

.PP
Returns a copy of given vector with only Y component of the vector\&. 
.SS "static Vector3 Vector3Common\&.onlyZ (this Vector3 vector3)\fC [static]\fP"

.PP
Returns a copy of given vector with only Z component of the vector\&. 
.SS "static Vector3 Vector3Common\&.relativeTo (this Vector3 vector3, Transform target, bool onlyLateral = \fCtrue\fP)\fC [static]\fP"

.PP
Transform a given vector to be relative to target transform\&. Eg: Use to perform movement relative to camera's view direction\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 10,000 meters below from the source code\&.
